### ISSUE TITLE
Documentation: Wrong Log File Location

### ISSUE THREAD

**Issue by toshi0383** [realm/realm-mobile-platform#10]
Currently the document says:

> Log path (set in configuration.yml); defaults to /var/realm-sync.log

https://realm.io/jp/docs/realm-object-server/#logging

On Ubuntu the path was actually `/var/log/realm-sync.log`.

**Comment by teotwaki** [comment]
Hi @toshi0383,

Thanks for reporting this. Actually, I already have a PR open for it, so it should be fixed soon.

**Comment by sorenvind** [comment]
Thanks for your report @toshi0383. We have now fixed this bug on the website.

**Comment by toshi0383** [comment]
Nice, but, I still see this... ?

> Log path (set in configuration.yml); defaults to /var/realm-sync.log

**Comment by sorenvind** [comment]
@toshi0383 Thanks for reporting that! It turns out to only be fixed on the english version here: https://realm.io/docs/realm-object-server/#logging. I'll make sure we get the other languages updated as well. Sorry for the inconvenience!
