### ISSUE TITLE
Please provide recent config inside this repository.

### ISSUE THREAD

**Issue by molind** [realm/realm-mobile-platform#101]
Many of users of realm-mobile-platform, I believe, decided to launch it inside a container. And it's very convenient to have configuration files in separate volume along with https certificate and key. But tricky part is to handling config file changes when realm-object-server is installed. In my case I upgraded from beta-4.11 to beta-6.0. There is a lot of new features and new section of config. And I have to build and run my container outside the docker compose, just to get recent config from /etc/realm/configuration.yml and copy missing parts to my persistent volume.

Please keep config file inside of this repository so we could track changes and update it in convenient way.

**Comment by istx25** [comment]
Hi @molind. Thank you for reaching out with this suggestion. I'll have someone (whose more experienced in this area) review what you've shared and respond with a follow-up soon. We appreciate your patience while we do this.

**Comment by istx25** [comment]
@molind: I've assigned this to @radu-tutueanu who should be able to look into this more. :-)
