### ISSUE TITLE
Official docker image?

### ISSUE THREAD

**Issue by molind** [realm/realm-mobile-platform#102]
Any chance you release an official docker image for realm object server?

And may be you could add an alpine flavored version of that docker image?

Check https://hub.docker.com/r/library/nginx/ for advanced Dockerfile examples.

My `Dockerfile` is pretty simple right now:
```
FROM ubuntu:16.04

EXPOSE 9080

RUN apt-get update && \
    apt-get -y install curl

# Setup Realm's PackageCloud repository
RUN curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | bash

# Install the Realm Object Server
RUN apt-get -y install realm-object-server-developer

# Enable and start the service
# RUN systemctl enable realm-object-server

# Start the service
# CMD systemctl start realm-object-server

CMD /usr/bin/realm-object-server -c /etc/realm/configuration.yml
```

**Comment by istx25** [comment]
Thank you for reaching out, @molind. This feature is already being tracked over on issue #44. Feel free to monitor that issue for this feature request.
