### ISSUE TITLE
Is the 1.0 Release the Same as 1.0.0-BETA-6.0-97?

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-mobile-platform#103]
I just did `sudo apt-get update` and then `sudo apt-get upgrade realm-object-server-developer` on my Ubuntu server and I get the following response:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
realm-object-server-developer is already the newest version (1.0.0-BETA-6.0-97).
```
Is ***-6.0-97** the same build as the 1.0 release?

Thanks!

**Comment by ewerx** [comment]
I'm on an earlier beta and I get the same output:

`realm-object-server-developer is already the newest version (1.0.0-BETA-4.11-449).`

**Comment by teotwaki** [comment]
Could you list what repository you have installed? Thanks.

**Comment by ArifADS** [comment]
Same as @ewerx 

`realm-object-server-developer is already the newest version (1.0.0-BETA-4.11-449).`

**Comment by ewerx** [comment]
I have `/etc/apt/sources.list.d/realm_realm.list` which contains:
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/realm/realm

deb https://packagecloud.io/realm/realm/ubuntu/ xenial main
deb-src https://packagecloud.io/realm/realm/ubuntu/ xenial main
```

**Comment by alebsack** [comment]
@cliftonlabrum You can get around this by simply removing your existing package and installing the new one:

```
sudo service realm-object-server stop
sudo apt-get remove realm-object-server-developer
sudo apt-get install realm-object-server-developer
sudo service realm-object-server start
```

@ewerx and @ArifADS can you please create a new issue regarding version `1.0.0-BETA-4.11-449`?

**Comment by ewerx** [comment]
Thanks that worked. The new issue is #109

**Comment by istx25** [comment]
Since @alebsack shared a viable solution for this issue and a new issue has been filed regarding `1.0.0-BETA-4.11-449`, I'm going to close this one.
