### ISSUE TITLE
Congratulations on Shipping 1.0 and Thank You

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-mobile-platform#104]
I know this isn't a real issue, but I just want to congratulate the Realm team on the Realm Object Server 1.0 release and tell them thank you for all their hard work.

I have used Dropbox, Parse, SQLite, the Dropbox Datastore, CloudKit, FireBase, and probably others, and *nothing* has compared to how elegant Realm is. 

- The code is intuitive and beautiful
- The sync platform is crazy-fast and reliable
- Offline-first is exactly what I need
- Queries are mind-blowingly quick (even with huge numbers of records)

I really couldn't be more impressed. Here's to Realm's continued success!

**Thank you!**

**Comment by istx25** [comment]
Hey @cliftonlabrum! Thanks so much for the kind words!! 😸  Please feel free to also send off any feedback or things you've seen that could be improved. ❤️

**Comment by bmunkholm** [comment]
Thanks a ton Clifton! This is one of the issues I actually don't mind having open a while longer so I have something great to look at tomorrow as well :-)

**Comment by istx25** [comment]
Sounds good to me. ❤️

**Comment by Montrazul** [comment]
Yes. Congratulations! Realm and Realm Mobile Platform are great!

**Comment by teotwaki** [comment]
Thanks a lot for the great feedback. This is one of the things that makes it great to work on a product like this.
