### ISSUE TITLE
Unable to locate Package on CentOS 6

### ISSUE THREAD

**Issue by 4Face** [realm/realm-mobile-platform#105]
Edit by @teotwaki: This issue was modified to only reflect the CentOS6 issue. See below for more information.

-------------------------------

Hi everyone, I've tried to install RMP un Ubuntu, but it sais realm-object-server-de it's not avaible, but realm-object-server-developer is avaible, so I solved installing it.
But on CentOS repository both of em are unavaible, how to fix that?

```
yum --disablerepo="*" --enablerepo="realm_realm" list available
Available Packages
nodejs.x86_64                 1:4.5.0-1nodesource.el6                realm_realm
yaml-cpp.x86_64               0.5.3-4.el6                            realm_realm
```

**Comment by istx25** [comment]
Hi @4Face. Thank you for reaching out for support. I'll have someone look into your question and respond with a solution or follow-up questions as soon as possible. We appreciate your patience.

**Comment by pvroosendaal** [comment]
Having the same issue here;
"No package realm-object-server-developer available" when trying the following on centos6:
sudo yum -y install realm-object-server-developer

**Comment by teotwaki** [comment]
Hi,

We had an issue specific to CentOS6 and decided to withhold that package until we have a fix for it. We appear to run into a heisenbug segfault triggered by some optimisation in GCC 4.9 on EL6. This is fairly high on our priority list.

Regarding Ubuntu, the package is published, and is called `realm-object-server-developer`. The name was misspelled on our website, and that has been fixed.

- https://realm.io/docs/get-started/installation/linux/
- https://github.com/realm/realm-mobile-platform/issues/106

I'll rename the issue to just track the CentOS6 thing, considering the Ubuntu one is fixed.

**Comment by 4Face** [comment]
Can you update us when there is some news please?

**Comment by teotwaki** [comment]
Hi @4Face,

Yes, I'll update you as soon as I have more information. This is high on our priority list, and should probably be fixed in our next bugfix release.

Thanks,

**Comment by teotwaki** [comment]
No idea what reverted my title change last time. \o/

**Comment by istx25** [comment]
Weeiiirrddd.

**Comment by 4Face** [comment]
Sorry if I may bother you, is it possible to have the last (bug affected) version? I just need to do some internal test for my app.

**Comment by teotwaki** [comment]
@4Face I'll see if I can get that to you. Could you drop me a line at help@realm.io?

Thanks

**Comment by radu-tutueanu** [comment]
Closing this issue as we due publish packages for centOS 6 now.
