### ISSUE TITLE
Possible correction needed in ROS documentation

### ISSUE THREAD

**Issue by istx25** [realm/realm-mobile-platform#106]
https://realm.io/docs/get-started/installation/linux/

Someone reported a problem with the documentation for the Realm Object Server saying `sudo apt-get install realm-object-server-de` gave back an error but `sudo apt-get install realm-object-server-developer` works perfectly.

Is this accurate? Should it be `-developer` or `-de`?

**Comment by bigfish24** [comment]
It is `-developer`. I will update website. This section is accurate: https://realm.io/docs/realm-object-server/

**Comment by istx25** [comment]
Sounds good. :)

**Comment by teotwaki** [comment]
This was fixed.
