### ISSUE TITLE
Updating to Version 1.0

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#107]
The [updating instructions](https://realm.io/docs/realm-object-server/#macos-1) to version 1.0 are saying that I simply have to:

`Upgrades to the macOS version of the Object Server are delivered by a new macOS download bundle from Realm`

But what do I have to do if I want to keep my admin and user informations? I tried copying the old user_data folder to the new realm mobile platform but that obviously didnt work (had to recreate admin and no users were shown)

So what do I have to do to perform a prober update? Not a reinstallation!

The realm mobile platform version I want to upgrade from is:

`Realm Mobile Platform 1.0.0-BETA-4.11`

**Comment by teotwaki** [comment]
Hi @Montrazul,

We indeed didn't anticipate people wanting to keep their data on the macOS developer platform. We have, however, full and automated upgrade paths on Linux.

As you noticed, you have to keep a few more files than what you tried. I'll get somebody to give you an exact list of files that needs to be copied over, and we will update the docs on the website as well.

Thanks for reporting,

**Comment by radu-tutueanu** [comment]
There was a change in the directory structure prior to 1.0:

**Comment by radu-tutueanu** [comment]
Hello, @Montrazul . There was a slight change in the directory structure in 1.0.
Here are the instructions for the upgrade 
1. Download the 1.0.0 ROS from https://static.realm.io/downloads/object-server/realm-object-server-bundled_node_darwin-developer-1.0.0.tar.gz
2. Extract the archive. Do not start the server
3. Create a the user_data folder in the 1.0 ROS, at `/object-server/root_dir/0/`
`mkdir -p $(path_to_ROS_1_0)/object-server/root_dir/0/user_data`
3. Copy the contents of the user_data directory from the 4.11 ROS to the directory created at step 3.
`cp -R $(path_to_ROS_4_11)/object-server/root_dir/user_data/* to $(path_to_ROS_1_0)/object-server/root_dir/0/user_data/*`
4. Start the server.

Thank you for reporting and please let me know if you you have any issues with it.

**Comment by Montrazul** [comment]
thx!
