### ISSUE TITLE
Unable to upgrade realm-object-server-developer from 1.0.0-BETA-4.11-449

### ISSUE THREAD

**Issue by ewerx** [realm/realm-mobile-platform#109]
Forked from #103

```
$ sudo apt-get update
Hit:1 http://mirrors.digitalocean.com/ubuntu xenial InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu xenial-updates InRelease
Hit:3 http://repos.sonar.digitalocean.com/apt main InRelease
Get:4 http://mirrors.digitalocean.com/ubuntu xenial-backports InRelease [102 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:6 https://packagecloud.io/realm/realm/ubuntu xenial InRelease
Fetched 204 kB in 1s (145 kB/s)
Reading package lists... Done
~$ sudo apt-get upgrade realm-object-server-developer
Reading package lists... Done
Building dependency tree
Reading state information... Done
realm-object-server-developer is already the newest version (1.0.0-BETA-4.11-449).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

`/etc/apt/sources.list.d/realm_realm.list` contains:
```
# this file was generated by packagecloud.io for
# the repository at https://packagecloud.io/realm/realm

deb https://packagecloud.io/realm/realm/ubuntu/ xenial main
deb-src https://packagecloud.io/realm/realm/ubuntu/ xenial main
```

Workaround:

```
sudo service realm-object-server stop
sudo apt-get remove realm-object-server-developer
sudo apt-get install realm-object-server-developer
sudo service realm-object-server start
```

**Comment by ArifADS** [comment]
I did the workaround and now my realms won't sync u.u

**Comment by cliftonlabrum** [comment]
@ArifADS Did the installation overwrite your `configuration.yml` file? You might check it to see if it still has your settings in it.

**Comment by bigfish24** [comment]
@ArifADS what version of the client are you using? (assuming you are still having issues?)

**Comment by ArifADS** [comment]
@cliftonlabrum I don't think the update overwrite it, But I have not made any manual change there, but the admin token and admin accounts for website worked the same, but Realm Browser doesn't show any Realms and my clients aren't syncing but they can Log Out and Log In

@bigfish24 v2.3 on client ( I updated the client and the server at the same time but any of the client versions wanted to sync), I'm compiling v2.4 right now

**Comment by bigfish24** [comment]
@ArifADS can you provide server-side and client logs to show if the clients are being rejected from connecting?

**Comment by ArifADS** [comment]
@bigfish24 a few days ago I was testing with a newly created SyncUser/Realm and since updating to 2.4 the sync is working, I will test now with old SyncUsers/Realms to see if it's working too now.

**Comment by teotwaki** [comment]
Seems like this isn't an issue anymore.
