### ISSUE TITLE
Removing/Uninstalling Realm Object Server from server - does not clean all artefacts

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-mobile-platform#110]
`Ubuntu 16.041`

I followed the instructions to uninstall ROS from my server and the rebooted the server for good measure.

I then re-installed ROS.

All the previous users and realm files remained listed in the dashboard.  The admin key was also the same.

Using some old code I then attempted to open an existing Realm and received this error.
`2017-01-21 07:23:07.680 Realm_Owner[15765:2716462] Sync: Connection[1]: Connection closed due to error reported by server: Bad server file identifier (IDENT) (207)`

The main point of this issue ticket is that uninstalling does not remove ALL artefacts.  I was actually trying to start over.

**Comment by teotwaki** [comment]
Hi @ianbradbury-bizzibody,

This is to be expected. When a package is uninstalled, its configuration and runtime files are not be removed. If you'd like to do so, please use the `purge` option of `apt-get`. Please see [this answer](http://askubuntu.com/questions/231562/what-is-the-difference-between-apt-get-purge-and-apt-get-remove#231568) for more details.

If you'd like to completely clean your system, please run the following commands:

```sh
sudo apt-get remove --purge --auto-remove realm-object-server-developer
sudo rm -rf /var/lib/realm

# optionally, reinstall
sudo apt-get install realm-object-server-developer
```

**Comment by ianbradbury-bizzibody** [comment]
Thanks @teotwaki.  Appreciated.
