### ISSUE TITLE
Getting duplicates when the app has existing data

### ISSUE THREAD

**Issue by MattW86** [realm/realm-mobile-platform#111]
Hi,
In my app, I have some default data that I set up when the app is launched for the first time and that gets uploaded to the ROS. The problem is that if I delete the app and reinstall it, I will receive the data from ROS and my default data will be configured as well so I will have duplicates. What can be done to avoid this?

**Comment by bigfish24** [comment]
@MattW86 we support [primary keys](https://realm.io/docs/realm-object-server/#primary-keys) so you can upsert. Furthermore, we even support default values where you can create an object with a default, but if there is already a synced object with the same primary key that has updated values, the merge algorithm we "combine" the two objects, but keep the updated values.

The trick is that our docs are not very explicit on how to set default values. To do so, either the default value has to be hardcoded:

```swift
class Settings: Object {
  dynamic var id = 0
  dynamic var aSetting = "defaultValue"
```
or you have to use the [`create` method](https://realm.io/docs/swift/latest/#creating-and-updating-objects-with-primary-keys) to pass in the values:

```swift
// Assuming a "Settings" with a primary key of `0` already exists.
try! realm.write {
  realm.create(Settings.self, value: ["id": 0, "aSetting": "defaultValue"], update: true)
}
```

In either case, if the user already created a `Settings` object with an updated value for `aSetting` that is on the server, when this merges with the local `Settings` object with default values, the `aSetting` update value will win over the default value.

**Comment by MattW86** [comment]
@bigfish24 Thanks very much :) Almost perfect.. I have one small issue though. If I set the primary keys manually like ..

```
    NSMutableArray *defaults = [[NSMutableArray alloc] init];
    [defaults addObject:@{@"name" : @"name1", @"id" : @"48b9fc77-e94b-4f1b-94fc-a57fab5ec420"}];
    [defaults addObject:@{@"name" : @"name2", @"id" : @"6dedb9cc-c71f-4655-b94a-5eef45689cc6"}];
    
    for (NSDictionary *item in defaults) {
        MWDefaultName *defaultName = [[MWDefaultName alloc] initWithValue:item];
        [self.realm addObject:defaultName];
    }
```
everything is fine. ROS knows all the objects that have been created by the device and updates correctly.

However, if primary keys are created like the following way
```
+ (NSDictionary *)defaultPropertyValues {
    return @{ @"id" : [[NSUUID UUID] UUIDString] };
}
```
then I will end up having duplicates since they have different primary keys.. 

Is there a solution to this apart from setting primary keys manually?

**Comment by Montrazul** [comment]
For the first start of the app there is a new way of checking the initial synchronisation. 
Checkout the following: [Sync Progress Notifications](https://realm.io/news/realm-objc-swift-2.3/)

**Comment by istx25** [comment]
Thanks @MattW86 for following-up. I'll assign this to @bigfish24 so he can look into this further.

**Comment by MattW86** [comment]
Thanks. 

@Montrazul I think you are assuming that login is mandatory but that's not the scenario. It's optional.

**Comment by Montrazul** [comment]
It is still possible. You launch it for the first time. You have to have some kind of User, otherwise you could not sync the local realm with realm mobile platform. You can check first start with a simple boolean in the user defaults.
If it is first start just perform the following:

```
let credentials = SyncCredentials.usernamePassword(username: email, password: password, register: false);
let server = URL(string: HelperUrls.URL_SERVER)!;
        
SyncUser.logIn(with: credentials, server: server) { user, error in
    DispatchQueue.main.async {
                
    if let user = user {
        print("login success: \(user.identity!)");

        // create your default configuration
        self.setDefaultRealmConfiguration(user: user);

        REALM_Manager.getSharedInstance().getRealm().refresh(); 
        // I just refresh realm to make sure it is getting opened to trigger the sync
                    
        let session = user.session(for: self.getRealmURL())!;
                    
        self.notificationToken = session.addProgressNotification(for: .download, mode: .forCurrentlyOutstandingWork) { progress in
            if (progress.isTransferComplete) {
                print("login progress completed: \(user.identity!)");
                            
                // go to next view or load next view
            }
        }
    } else if let error = error {
        print("login failed: \(error)");
                    
        self.alert(message: "Anmeldung fehlgeschlagen.");
    }
}
```

**Comment by MattW86** [comment]
@Montrazul I think you are misunderstanding the potential issue here. 
Let's say I,
1. launch the app for first time
2. there is no existing user, so defaults are created on device with unique primary keys
3. register to ROS, user is created so we sync defaults
4. log out and delete the app
5. re-download and launch the app
everything is fine up to this point
6. there is no existing user, so defaults are created once again with unique primary keys
7. login 
8. as far as ROS is concerned, I have data to sync from device to ROS and from ROS to device since default data on the server have different primary keys then the ones that were created on device and as far as I am concerned, I have duplicates.

**Comment by Montrazul** [comment]
And that is the point. Do the sync first (without creating defaults) if the syncing is done (you get notified when its done with the code I posted above) check if data is empty. If it is empty create your defaults.

**Comment by MattW86** [comment]
So you are saying that I have to force users to register / login first. Sorry that's not an option for me. As mentioned, it's optional.

**Comment by Montrazul** [comment]
No! I did not say that :D

Listen: You always have the `SyncUser`. Otherwise you are NOT able to synchronize data. I dont know how your mechanics work for default username and default password but anyway, without a `SyncUser` you cant sync, so you have to have one.

If you open up the connection to the realm mobile platform you simply have to trigger a sync and use the notification token to get notified when syncing is done. after the syncing check if your values exists or not. If they not exists create your default values. 

It does not matter if you have a reigster/login or not. You need a `SyncUser` anyway.

**Comment by MattW86** [comment]
@Montrazul I appreciate your help but I am really not sure what you are talking about. What do you mean "I always have SyncUser". You have to login in order to have SyncUser or am I wrong? Even in the example you provided above, you are logging in.

**Comment by Montrazul** [comment]
@MattW86 Yes, maybe we have som misunderstandings here. 

You said login or register is optinal for your application. But if that is true, you cant use realm mobile platform because for that you need to register and login. You cannot use realm mobile platform without a register and login.

So when you say it is optinal maybe you mean, that you have a local realm when the user does not want to register/login and dont want to synchronize his data. But that would mean that you have two different realm databases because a local realm database file is something different than a synced realm.

But even that is possible. I also did that before. In an older version of my app I used a local realm database. After that I wanted to use realm mobile platform so I had to do a little bit of work to copy the data from one realm (the local realm) to the syncronized realm.

So maybe this is what you mean by "optional". If you dont register / login you cant use synced realm at all.

**Comment by MattW86** [comment]
@Montrazul 
Correct :) 
register / login is optional therefore synchronization is optional.

**Comment by Montrazul** [comment]
Ok. So the process is the following:

1. The User does not Register / Login so a local realm is used
2. Later the User decides to Register / Login
2.1. Create a SyncUser for the realm mobile platform
2.2. Copy the the data from the local realm file to the synced realm
2.3. Delete local realm file

To prevent any cases of duplicates:

1. At first do NOT create user defaults
2. Get user data from local realm or synced realm first!
3. Check if these data is empty
3.1. If it is empty: create user defaults
3.2. If it is not empty: everything is fine.

Right now there is no option to fully downloade a synced realm. The only thing existing are the realm sync notifications. But I have a problem with it right now. You can read that here: [issue #116](https://github.com/realm/realm-mobile-platform/issues/116#issuecomment-275684036)

**Comment by MattW86** [comment]
@Montrazul If you simply delete the local realm, you will still have the SyncUser so you can do all those thing. But if you log out & delete the app or you use another device after 2.3 then you have no SyncUser and defaults will be created with unique primary keys.

**Comment by Montrazul** [comment]
So you mean even when the user already reigstered and logged in on a device and he deletes the app and reinstalls it, the register and login is optional again? That would not make any sense because the user would lose hes data.

**Comment by MattW86** [comment]
@Montrazul as mentioned many times, yes that's the scenario. I am not sure what you are tying to say. If login is optional in the first place, why not optional second time? We are building an offline-first app and that totally makes sense for us. If the user wants his data back after reinstalling the app or perhaps on a new device, he has to login. As simple as that. We are trying to find out the best solution to avoid duplicates for the default data that come with the app.

**Comment by Montrazul** [comment]
But anyway he loses data so that does not make any sense to me. So If that is the scenario (I repeat, no sense at all), you ofcourse have to delete your duplicates by yourself.

**Comment by MattW86** [comment]
@Montrazul Nope :) he doesn't lose anything I promise you as long as he logs into the app later on. You keep misunderstanding the issue :)

**Comment by MattW86** [comment]
lol how do you find out what is duplicated if primary keys are different?

**Comment by Montrazul** [comment]
Ok so maybe it would be good to completely explain your scenario without any missing points. Your explanation for now delivers too much missing informations and so too much room for confusion.

**Comment by MattW86** [comment]
I think explaining it 100 times should be sufficient.

**Comment by Montrazul** [comment]
Are you having an answer until now? No? So it seems not to be sufficient.

**Comment by MattW86** [comment]
I do have an answer if you read everything you will find out. I am looking for a more elegant solution. Definitely not from you though.

**Comment by Montrazul** [comment]
I dont know if you will get that with the attitude you are showing.

**Comment by MattW86** [comment]
Definitely not from geniuses like you!

**Comment by Montrazul** [comment]
I reported your behaviour to github :)

**Comment by MattW86** [comment]
@Montrazul Thanks for deleting all the nonsense you wrote..

**Comment by Montrazul** [comment]
@MattW86 Wasnt nonsense at all since I am able to handle local realm files and synced realm files with register / login or without and not having duplicate entries ;)

**Comment by MattW86** [comment]
@Montrazul  Sure but we are talking about my issue here not your great app :)

**Comment by Montrazul** [comment]
But it is not an issue. You can achiev your goals by simple programming. It is help what you need not issue reporting.

**Comment by MattW86** [comment]
@Montrazul dont put your personal thoughts here.. "simple" is not my thing..

**Comment by Montrazul** [comment]
You should try it with simple. Very often it is the best solution since the opposite of simple (complicated) does not seem to fit your programming skills.

**Comment by MattW86** [comment]
@Montrazul  lol. I like the cockiness. maybe you should read the post before suggesting some stupid solutions.

**Comment by Montrazul** [comment]
:)

**Comment by bigfish24** [comment]
Jumping in here. Let's keep this civil. Haven't yet read through to help with the request, but want to make sure we don't continue an argument. We need to link to this but Realm had a code of conduct we expect everyone to follow: https://realm.io/conduct/

**Comment by AndyDentFree** [comment]
@MattW86 Your situation with offline-first and delayed login makes a lot of sense from a user point of view. Can you please tease out the details a bit more of how you see it working for the _new_ data they enter offline - is there any overlap with old data?

Variations I can see happening, most requiring the PK matches you noted:

1. No overlap - old data should be restored and visible as well as new (sounds unlikely given your PK discussions).
2. Old data should be restored but updated with locally **entered** newer data.
3. Old data replaces default/empty new data (typical when defaults are generated at startup).
4. User-controlled merge required.

Also, a cross-cutting concern is that how you merge may vary depending on data being shared with _others_ vs shared with _yourself alone_. (eg: I'm a multi-device ~ab~ user of Evernote so share with myself mostly.)

Have I missed anything?

I'm interested because, although we've not yet released RMP for Xamarin, we already have similar discussions going with sophisticated users (I'm a Realm dev on the Xamarin team).

**Comment by MattW86** [comment]
Hi @AndyDentFree. You have hard to answer questions :) 

The scenario I have in mind is something like this..

(Assuming I have sync defaults previously)
1. I am offline on a new device 
2. I edit defaults
3. I create new objects
4. I login
5. I am expecting to see  "**the new objects and old data should be restored but updated with locally entered newer data.**" 

On the other hand if 
1. I am offline on a new device 
2. I **do not** edit the defaults
3. I create new objects
4. I login
5. I am expecting to see "**the new objects and old data replaces default/empty new data**" 

As for the shared data, it should be the same I believe. Last Updated objects will win the merge.

**Comment by gritzko** [comment]
@MattW86 How do you identify users? By their e-mail?

**Comment by AndyDentFree** [comment]
@MattW86 I try to think of complicated ways to fail before people run into them ;-)

Thanks for the feedback, it makes lots of sense. I'm mulling over the implications still but I think the partial answer is that you will need _some_ kind of application logic to cope with this, for PK generation.

We have some stuff being discussed internally but I think you still manage to break all our proposals :-(

For your default data, I think you still need to have a set of manual PKs so you guarantee them staying the same from one install to the next. Then, I think the ROS sync will obey historical order of changes.

**Comment by MattW86** [comment]
@gritzko yes email at the moment. 

@AndyDentFree Sorry to break your proposals :) 
I believe you are right. Manual is the safest way to go.

**Comment by MattW86** [comment]
@AndyDentFree  Here is the current behavior with the new manual PK approach..
1. I am offline on a new device
2. I edit defaults
3. I create new objects
4. I login
5. defaults are not updated but old data are restored from ROS
6. new objects are gone 
7. I logout
8. Offline updated defaults are back
9. New objects are back

So I am guessing there is no merge mechanism but instead a new realm file is created after logging in. Can you please clarify?

**Comment by AndyDentFree** [comment]
If a _new realm file is created after logging in._ then that is most likely application logic somehow as that would be an extremely unlikely Realm bug. Are you calling plain `Realm.GetInstance()` anywhere?

**Comment by MattW86** [comment]
I see. So what is the reason behind the behavior I am getting?

**Comment by AndyDentFree** [comment]
> I was able to reproduce the same behavior in the RealmDraw project

Can you please clarify this - the RealmDraw project shouldn't work offline at all.

Note that there is **no** unique data in RealmDraw so it's possible to have completely duplicate paths.

Can you please either post some code here or mail it to support@realm.io.

**Comment by MattW86** [comment]
> Can you please clarify this - the RealmDraw project shouldn't work offline at all.

I slightly modified the Objective-C Code to make it work offline and online.

> Note that there is no unique data in RealmDraw so it's possible to have completely duplicate paths.

Sorry for the confusion. Maybe I should open a new thread. I was referring to the merge mechanism. 
If I am offline and create new objects, after logging in, they are gone. I have to log out to see them. 
If I am logged in and create new objects, after logging out, they are gone. I have to login to see them.

That's the reason why I was thinking multiple realm files could be used in the background but you clarified that that's not the case.

**Comment by AndyDentFree** [comment]
>That's the reason why I was thinking multiple realm files could be used in the background but you clarified that that's not the case.

Just to clarify that - there is nothing stopping you opening mutiple Realm files - they work independently. You can have a mixture of synchronised and purely local Realms active at the same time in the same app - a local Realm is commonly used for local settings for example.

>If I am offline and create new objects, after logging in, they are gone. 

That makes me wonder if, inadvertently, you are creating your `RLMConfiguration` differently so you have both a synchronised and local Realm - we really need to see some code ;-)

**Comment by MattW86** [comment]
Here is what I am doing.

```
+ (void)configureRealmForSyncUser:(RLMSyncUser *)syncUser {
    RLMRealmConfiguration *defaultConfig = [RLMRealmConfiguration defaultConfiguration];
    if (syncUser) {
        RLMSyncConfiguration *syncConfig = [[RLMSyncConfiguration alloc] initWithUser:syncUser realmURL:self.syncURL];
        defaultConfig.syncConfiguration = syncConfig;
    }
    [RLMRealmConfiguration setDefaultConfiguration:defaultConfig];
}
```

Hope this helps :)

**Comment by jpsim** [comment]
You really shouldn't be changing the default Realm configuration multiple times during your app's lifetime. Rather than doing that, you should use the RLMRealm constructor passing a new RLMRealmConfiguration, which will drastically simplify your code and avoid race conditions when setting global mutable state.

**Comment by MattW86** [comment]
@jpsim Thanks for the feedback. I will edit it and keep you updated.

**Comment by MattW86** [comment]
@jpsim everything is working as expected. Thanks for your help.. Closing this issue as the original question has already been answered.
