### ISSUE TITLE
Add Confirmation Dialog to Delete User Action

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-mobile-platform#114]
Right now you can click the trash can icon next to a user on the Users page and it will instantly delete a user. It would be safer to have a prompt to confirm if you really want to delete it.

> Are you sure you want to delete user `<userId>`? **Cancel** /  **Delete**

A basic JavaScript confirmation dialog would do.

![image](https://cloud.githubusercontent.com/assets/2513753/22351389/e11e70c6-e3d4-11e6-9a6d-2004e7c6903e.png)

Thanks!

**Comment by bigfish24** [comment]
Thanks for suggesting, and I agree! We will work to add this in an upcoming version.

**Comment by teotwaki** [comment]
Fixed in next release.
