### ISSUE TITLE
Adding Property to Realm does not work

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#115]
Im working with realm mobile platform version 1.0 and realm database version 2.3.
Today I wanted to add a new property, so I did:

```
....
let checkedDreams = RealmOptional<Bool>(true);
...
init() {
    ...
    self.checkedDreams.value = true;
    ...
}
...
```

And I also increased the default realm configuration schema version from `2` to `3`.

When I now start the app the new field is existing locally but it is `nil` so the default value is not set. The realm mobile platform did not add the new property! I thought additive property changes for `RealmSwift` are working the way I did it but obviously I did forget something.

**Comment by bigfish24** [comment]
Is the property not visible in the browser? The property likely was added but the fact that a default value isn't set seems like application logic that is wrong.

**Comment by Montrazul** [comment]
I also guess that this is the problem but that would lead to the question: Why is the default value not working?

**Comment by bigfish24** [comment]
Do you know that your logic is correct and the line in unit is actually run?

**Comment by bigfish24** [comment]
One way to verify that how you are adding properties is working, is to add a property but not bump the schema version, which will cause an error to throw when opening the Realm.

**Comment by Montrazul** [comment]
That is what I am asking. Is my logic correct? I just added a simple new property to the schema. The code I posted above is everything I changed. And it is not working. 

I tested it with another property:

```
...
dynamic var name: String! = "";
...
init() {
    ...
    self.name = "bigfish24";
    ...
}
...
```

Adding of this example property was working and it instantly appeared in the realm browser.

**Comment by Montrazul** [comment]
I verified the adding of the property. When I do not increase the schema version it crashes with:

> REALM_ASSERT(rlmSchema.objectSchema.count == schema.size());

So the property adding seems to work. Only the default value is ignored.

**Comment by bigfish24** [comment]
Ok, can you verify that when you create a Realm object your `init()` method and added line is being called?

**Comment by Montrazul** [comment]
When I create an Object it is called, yes. I dont know what is happening in the background with realm when you add a new property to the schema for already existing objects. I dont know if that calls the `init()` method again (but I guess no, because that would override the properties with default values) but for that I defined:

`let checkedDreams = RealmOptional<Bool>(true);`

So that the default value is `true`.

**Comment by bigfish24** [comment]
Ah, that clarifies. When you add a new property and you want to apply default values to all the existing objects, you would need to do that manually. With a standalone Realm you would do this in the migration block, but a sync Realm doesn't use this, so instead you can just run your own "block" after opening to apply changes to existing objects.

**Comment by Montrazul** [comment]
Ok. Thank you for pointing that out.
