### ISSUE TITLE
New sync progress notifications arent working as expected

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#116]
I read this [article](https://realm.io/news/realm-objc-swift-2.3/) where it was written that with the new sync progress notification you can check for an initial sync first before presenting view elements. So I tried it out with the following code:

```
func loginOnline(email: String, password: String) {
        let credentials = SyncCredentials.usernamePassword(username: email, password: password, register: false);
        let server = URL(string: HelperUrls.URL_SERVER)!;
        
        SyncUser.logIn(with: credentials, server: server) { user, error in
            DispatchQueue.main.async {
                
                if let user = user {
                    print("login success: \(user.identity!)");

                    self.setDefaultRealmConfiguration(user: user);

                    REALM_Manager.getSharedInstance().getRealm().refresh();
                    
                    let session = user.session(for: self.getRealmURL())!;
                    
                    self.notificationToken = session.addProgressNotification(for: .download, mode: .reportIndefinitely) { progress in
                        if (progress.isTransferComplete) {
                            print("login progress completed: \(user.identity!)");
                            
                            self.notificationToken.stop();
                            
                            self.goToNextView();
                        }
                    }
                } else if let error = error {
                    print("login failed: \(error)");
                    
                    self.alert(message: "Anmeldung fehlgeschlagen.");
                }
            }
        }
    }
```

So as you can see I want to wait for the progress notification to tell me when the transfer is complete and only if it is complete I go to the next view. The timing is working:

```
login success: ...userid....
login progress completed: ...userid....
```

And after that the next view is presented. But when I do that the next view is empty that means the data is not yet 100% saved and updated. I have to restart my application to see the changes. Isnt it possible to trigger the transfer complete when the data is 100% written to disk and available for building the view?

**Comment by bigfish24** [comment]
The issue I think is the use of `.reportIndefinitely`. You should try `.forCurrentlyOutstandingWork` instead.

The reason being when you setup a notification with the setting `.forCurrentlyOutstandingWork`, the moment that is called, the outstanding data that is waiting to download ends up being what the progress is based on.

For example if you had 100 bytes to download when you call this, then the notification will fire, passing progress with X/100 bytes as the math, eventually leading to 100% completion.

Whereas, with `.reportIndefinitely` if additional data is synced by other devices, the remaining data to download would continue to change... thus the progress math could end up never reaching 100%. As a result, if you want to track progress of a specific event/task/time period, use `.forCurrentlyOutstandingWork` or if you just want to show a spinner that represents activity use: `.reportIndefinitely`.

**Comment by Montrazul** [comment]
If I do change it to `.forCurrentlyOutstandingWork` the app crashes at the line `self.notificationToken.stop()` with:

```
fatal error: unexpectedly found nil while unwrapping an Optional value

2017-01-27 15:48:11.351032 VKB360[1996:981902] fatal error: unexpectedly found nil while unwrapping an Optional value
```

**Comment by bigfish24** [comment]
Interesting, can you breakpoint on errors and figure out what value is `nil` that shouldn't be? I believe it does stop it automatically (@austinzheng could you please verify this comment).

**Comment by Montrazul** [comment]
The notificationToken itself is nil.

**Comment by bigfish24** [comment]
Aha, well I guess that answers the question on whether it removes it. Austin implemented this feature, so will look for his guidance on whether we should expect this behavior. For now, just remove the line?

**Comment by Montrazul** [comment]
Just deleting `notificationToken.stop()` seems to work. But I get it would be better to verify if this behaviour is intentionally.

**Comment by austinzheng** [comment]
Hello,

The token returned by `addProgressNotification(for:, mode:)` might correctly be `nil` in some cases (see [here](https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Sync.swift#L592)), so it's best to store it as an optional and use the `?.` operator to call `stop()` on it. However, the sample code in our documentation doesn't make this clear at all, so I'll change it. Sorry for the inconvenience and thanks for bringing this to our attention.

**Comment by Montrazul** [comment]
Ok I tested it with `forCurrentlyOutstandingWork` and the optinal notification token. It still does not work. The data still is not 100% loaded and updated on the realm so that the view can get those data. Still have to restart the app so that the changes take effect.

**Comment by bigfish24** [comment]
Ok, let us look into it and get back to you after the weekend. Sorry about this!

**Comment by ArifADS** [comment]
I'm having the same problem, if you addProgressNotification just after creating the Synced Realm object (before it actually makes the connection to endpoint) it will notificate progress with 0 transferable bytes, ex `Progress(transferredBytes: 0, transferrableBytes: 0)`, which makes `progress.fractionTransferred` return NaN and `progress.isTransferComplete` return `true`.

I'm too waiting for this to make decision in the flow of the app, my workaround was simply making it `.reportIndefinitely` and ignoring notifications with`transferrableBytes ` == 0, but thats a problem when realms are actually new and empty

**Comment by Montrazul** [comment]
Yes, that is not really a workaround since, as you already mentioned, an empty new realm would mean that you will never get to the breakpoint.

**Comment by Montrazul** [comment]
any news on that?

**Comment by Montrazul** [comment]
@ArifADS You are totally right. If I connect to realm mobile platform for the first time and when I use the progress notification the `isTransferComplete` is `true` instantly

```
self.notificationToken = session.addProgressNotification(for: .download, mode: .reportIndefinitely) { progress in
                        self.notificationToken = session.addProgressNotification(for: .download, mode: .reportIndefinitely) { progress in
    print("=================================PROGRESS=============================================");
    print("fraction transferred \(progress.fractionTransferred)");
    print("transferrable bytes \(progress.transferrableBytes)");
    print("transferred bytes \(progress.transferredBytes)");
                        
    if (progress.isTransferComplete) {
        print("login progress completed: \(user.identity!)");
                           
        self.notificationToken.stop();
                            
        self.presentSplitView();
    }
}
```

The output is:

```
=================================PROGRESS=============================================
fraction transferred NaN
transferrable bytes 0
transferred bytes 0
login progress completed: ...userid...
```

**Comment by bigfish24** [comment]
Small update on our end, we found a bug in the implementation that is causing this. Hope to have a fix in this week. cc @austinzheng

**Comment by jpsim** [comment]
Is this the same issue as realm/realm-cocoa#4623? If so, it'd be nice to consolidate.

**Comment by Montrazul** [comment]
It could be the same problem yes. At first start no download notifications because there are no bytes to transfer even if there has to be something to transfer.

**Comment by Redth** [comment]
Any progress here?  I'm trying to ensure my realm is sync'd locally in my app before i decide to show a particular UI or not.  It currently seems impossible to do this.

**Comment by morten-krogh** [comment]
There is progress here. I have merged a solution of this problem into the master branch of sync.
The higher levels of the RMP, however, still need to use the modified progress function before it 
is ready for users.

**Comment by nirinchev** [comment]
I believe @austinzheng's PR spearheads this effort for the bindings - once the design is approved, we'll propagate it across the rest of the SDKs.

**Comment by gritzko** [comment]
@nirinchev @austinzheng @cmelchior Guys, how is the progress? Did it propagate to the bindings? Time to close this issue?

**Comment by Redth** [comment]
This seems to work for me now
