### ISSUE TITLE
Unable to Create Realm Object Server Admin Account

### ISSUE THREAD

**Issue by CGrahamS** [realm/realm-mobile-platform#117]
After following the tutorial on how to [deploy](https://realm.io/docs/get-started/deployment/) a Realm Object Server onto a Digital Ocean Droplet with the Ubuntu distribution, I'm unable to register an admin account. 

- When I navigate to the Realm dashboard the dashboard navbar loads for a second at the top of the browser, displaying "{{$root.globals.currentUser.provider_id}}" on the right side of the navbar, where I'm assuming my account name would be displayed. 

- Next, the browser navigates to the login screen. 

- I haven't created an account yet, so I manually navigate to "**droplet-ip**:9080/#!/setup".

- Once there, I enter my desired account email and my password.

- The error message "An error occurred while setting up your account" displays and then I'm navigated back to the login page.

- Obviously, if I try to sign in I receive the "Login Failed: Email/Password combination incorrect." error message.

- I have checked that my server is running.

- Issue #75 is the closest related issue I found.

Thanks!

**Comment by bigfish24** [comment]
Sorry you ran into this issue, we will assist next week to sort it out.

**Comment by alebsack** [comment]
Hi @CGrahamS.  Can you please provide the version of Realm Object Server that you're using?  Also, any logs you can provide would be helpful.  You can find the log file under `/var/log/realm-object-server.log`.

**Comment by CGrahamS** [comment]
Hi @alebsack! I rebuilt my droplet and got the server working. Not exactly sure what went wrong, but I don't think I can retrieve that log any more. 

Thanks for getting back to me!

**Comment by alebsack** [comment]
@CGrahamS Thank you for trying out Realm!  If you see this again, feel free to reopen the issue.
