### ISSUE TITLE
Access token expired error 

### ISSUE THREAD

**Issue by gregiii** [realm/realm-mobile-platform#121]
## Goals

What do you want to achieve?

I am trying to migrate user data from our self-hosted parse-server to realm-object-server professional trial edition using the nodejs sdk. There are around 9K records that were needed to be copied over.

## Expected Results

What did you expected to happen?

The Parse SDK provides for a query which can enumerate through all records sequentially in  a forEach loop. For each object in the loop, I create a new Realm object and save it inside a write transaction. Since the Realm Sync User is logged in as administrator (using username and password, not admin token), I expected to finish moving all 9K records.

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash
The script is able to create 2,600 objects, then crashes with this error:

Connection[1]: Received: ERROR(error_code=202, message_size=20, try_again=0, session_ident=1)
Connection[1]: Connection closed due to error reported by server: Access token expired (202)
Segmentation fault: 11

On the server side:

2017-02-01T02:52:57.538Z - info: sync-server: Connection[25]: Connection from 127.0.0.1:38618
2017-02-01T02:52:57.538Z - info: sync-server: Connection[25]: Received: HTTP request(protocol_version=16)
2017-02-01T02:52:57.758Z - info: sync-server: Connection[25]: Session[1]: Session initiated (session_ident=1).
2017-02-01T02:52:57.758Z - info: sync-server: Connection[25]: Session[1]: Received: BIND(server_path=/d9acec7667fade1e3de1c1a99d5fa97f/realm-shared, signed_user_token='...DEUlnj9/IIjRsP/BsBpqP6GwblUA==', need_file_ident_pair=0)
2017-02-01T02:52:57.759Z - info: sync-server: Connection[25]: Session[1]: Received: IDENT(server_file_ident=5737314655680686778, client_file_ident=1, client_file_ident_secret=617907718509412642, scan_server_version=6866, scan_client_version=8983, latest_server_version=6866, latest_server_session_ident=2168576748072332250)
2017-02-01T02:53:58.811Z - error: sync-server: Connection[25]: Session[1]: Received UPLOAD message while session token had expired
2017-02-01T02:53:58.811Z - info: sync-server: Connection[25]: Session[1]: Session terminated (session_ident=1).
2017-02-01T02:53:58.812Z - info: sync-server: Connection[25]: Sending: ERROR(error_code=202, message_size=20, try_again=0, session_ident=1)
2017-02-01T02:53:58.812Z - info: sync-server: Connection[25]: Connection closed by client: End of input

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample
var User = require('./models/User');
var Group = require('./models/Group');
var GroupMember = require('./models/GroupMember');

Realm.Sync.User.login(AUTH_URL, ADMIN_USERNAME, ADMIN_PASSWORD, (error, user) => {

  if (error) {
    console.log(error);
    return;
  }

  var realm = new Realm({
    sync: {
      user: user,
      url: SERVER_URL,
    },
    schema: [User.schema, Group.schema, GroupMember.schema]
  });

  var query = new Parse.Query("CircleMember");
  let counter = 0;

    query.each(function(circleMember) {
      realm.write( function() {
        
        var values = GroupMember.fromParse(circleMember, realm);

        var newObject = realm.create('GroupMember',values,true);

        console.log(++counter + ": Created new GroupMember "  + newObject.objectId);
      });

    },{useMasterKey:true});

});

## Version of Realm and Tooling

Realm Object Server Version:  1.0.0-164
Flavor: / Professional /

Server OS & Version:  Ubuntu 16.04

Client SDK Version: 1.0.0-professional

Client OS & Version: MacOS Sierra

**Comment by radu-tutueanu** [comment]
Hello, @gregiii,

Thank you for reporting the issue. I opened an issue in our JS binding https://github.com/realm/realm-js/issues/827.

Until we release a fix, there are a couple of ways you can work around that:

1) Set the Access token expiration time to a long time in the server config:

uncomment line 65 in /etc/realm/configuration.yml and set it to 10 years:
`access_token: 315360000`

OR
2) Use the admin access token, not the admin username and password:

You will find the user token in /etc/realm/admin_token.base64

Sample code using it:

```
const adminToken = "...:..."
const user = Realm.Sync.User.adminUser(adminToken);

var realm = new Realm({
sync: {
user: user,
url: SERVER_URL,
},
schema: [User.schema, Group.schema, GroupMember.schema]
});

```
-------
A small observation:

It is better from a performance standpoint if you do a single write transaction in the loop you posted:

```
realm.write( function() {
  query.each(function(circleMember) {  
    var values = GroupMember.fromParse(circleMember, realm);
    var newObject = realm.create('GroupMember',values,true);
    console.log(++counter + ": Created new GroupMember "  + newObject.objectId);
  },{useMasterKey:true});
});
```

Let me know if you have any more questions.

**Comment by radu-tutueanu** [comment]
I would recommend using the admin access token, not the admin username and password. 
Increasing the access token expiration time should be done with care and never in production environments.

**Comment by gregiii** [comment]
Thanks @radu-tutueanu . Using the admin access token solved the issue. 

However I'm a bit lost from what's stated in the Realm Mobile Platform Enterprise Edition README:

While it is recommended to use an admin-token for read-only access on the server-side, you would need to use an admin-user for now when global read-write access on the server-side is desired.
That is due to a current limitation around the Global Event Listener. If you use an admin-token to create a new Realm on the server-side, it won't be tracked in the admin-Realm (/__admin), but the Global Event Listener relies on the information tracked there to observe new Realms. 

Also in the javascript docs:
Note that this bypasses the authentication service of the Realm Object Server. That means new Realms created in this way won’t be tracked internally, leaving them unavailable for notifications via the global listener API.
We only recommend the admin token for server-side use, such as querying or writing to existing synchronized Realms or with the event-handling.

I'm creating this realm in the root path, then give read/write permissions to all users. Then I will have a global event listener running so that it can trigger actions based on what user's write on the realm.(Example: when a user posts an urgent message for another user, the server needs to send an http request to Twilio to send an SMS). 

So maybe I should initially create the realm using an admin user, then later on populate it with data using the admin token ?

**Comment by mrackwitz** [comment]
Hey @gregiii, glad that you read our docs so closely and so got our attention on that, these infos aren't up to date anymore. I'll ensure to update our docs accordingly.

**Comment by gregiii** [comment]
Thanks, @mrackwitz for the clarification.

**Comment by radu-tutueanu** [comment]
Update: the issue was fixed in the latest release(RMP 1.0.3) and there shouldn't be any need for the workaround if you use the latest node sdk.

**Comment by mabecth** [comment]
How would you use the admin token in Realm 2.0? I cannot find /etc/realm/admin_token.base64.

**Comment by nirinchev** [comment]
Please, avoid reviving issues that have been closed for almost a year just because they tangentially relate to your question.

In ROS 2.0 you can find the admin token in `%path-to-ros%/data/keys/admin.json`.
