### ISSUE TITLE
Lost Users after updating to 1.0.2

### ISSUE THREAD

**Issue by ArifADS** [realm/realm-mobile-platform#123]
## Goals
Update from ROS 1.0.0 to ROS 1.0.2 

## Expected Results

Update, having all my users data and Admin Account intact, getting few token errors, get realm browser list my new realms.

## Actual Results

The ROS Web made me create a new Admin Account, after that all my Users and Realms listed in Web were deleted, it doesn't enlist the old ones, clients can't login with their usernames.

I could still connect to the Realm with Open Realm URL in Realm Browser. `realm://<address>/<UserId>/userRealm`

## Version of Realm and Tooling

Realm Object Server Version: 1.0.0 to 1.0.2
Flavor: Developer

Server OS & Version: ? Ubuntu AWS

Client SDK Version: 2.4.2

Client OS & Version: iOS 10.2.1

**Comment by radu-tutueanu** [comment]
Hello, @ArifADS !

Sorry to hear your troubles. Our migration script from 1.0.0 does not delete any files, we will try to help you recover the data.

We need more information in order to do that.

1. Did you install 1.0.0 from scratch or was it an update from a previous version?

2. Can you share the output of the following commands:
`ls -alh /var/lib/realm/object-server/0/user_data/`
`ls -alh /var/lib/realm/object-server/user_data/`

3. Can you please share the configuration file present at `/etc/realm/configuration.yml`

4. What was the upgrade procedure that you used?

Thank you,

Radu

**Comment by ArifADS** [comment]
1. No, i'm using ROS since it first version, I was once stuck in 1.0.0-BETA-4.11-449 so I followed #109  workaround and updated to 1.0.0, which broke some syncing, but got it working again when updating my Client to 2.4.

2. Of Course, `ls -alh /var/lib/realm/object-server/0/user_data/`:
`total 216K
drwxr-xr-x 28 realm realm 4.0K Feb  2 16:39 .
drwxr-xr-x  4 realm realm 4.0K Jan 20 15:46 ..
drwxr-xr-x  3 realm realm 4.0K Jan 23 02:57 0de5faa120cede7ca350037e7d87f199
drwxr-xr-x  4 realm realm 4.0K Feb  1 20:52 19da75ef03fb418ed0f09dc2f432c4b9
drwxr-xr-x  3 realm realm 4.0K Feb  1 15:16 3a5fc9e88bfff7523e4ce0f1d03dde61
drwxr-xr-x  3 realm realm 4.0K Feb  2 16:36 3ac429d86ef0930c711b67ae1bf092b9
drwxr-xr-x  3 realm realm 4.0K Feb  1 22:15 3d3db29a18bd1f23142ab78233fe62a7
drwxr-xr-x  3 realm realm 4.0K Feb  2 16:30 71a8503fcdbbdc4db5e0155af195daa6
drwxr-xr-x  4 realm realm 4.0K Jan 23 03:02 742748e40093638063e1998e9d1a9532
drwxr-xr-x  3 realm realm 4.0K Jan 20 15:46 745f5b9baf4208d950150b0a0dd810a4
drwxr-xr-x  4 realm realm 4.0K Jan 20 15:52 93a048fdfdee58b12be6d798277c8743
drwxr-xr-x  4 realm realm 4.0K Feb  1 20:51 9c0e726f226af5010903a8d4ad899532
drwxr-xr-x  4 realm realm 4.0K Feb  1 21:00 a2ac6f8c1354e1f9d0274161e1838226
drwxr-xr-x  3 realm realm 4.0K Feb  2 16:23 a6be85bb9648fdf9de456294375ccfd6
drwxr-xr-x  4 realm realm 4.0K Feb  1 20:51 a6bfe5cc1afb5734792f41f9df5caeb9
drwxr-xr-x  3 realm realm 4.0K Feb  1 20:35 a76b9f8c7d2781a1cc7d43fbceb61b76
drwxr-xr-x  3 realm realm 4.0K Jan 20 15:46 a7ee354170446307e375ec8e900c22e7
drwxr-xr-x  3 realm realm 4.0K Jan 20 15:46 admin
-rw-r--r--  1 realm realm  80K Feb  2 16:44 __admin.realm
-rw-r--r--  1 realm realm 1.4K Feb  2 16:44 __admin.realm.lock
drwxr-xr-x  2 realm realm 4.0K Jan 20 15:46 __admin.realm.management
drwxr-xr-x  3 realm realm 4.0K Jan 20 15:46 __auth
drwxr-xr-x  4 realm realm 4.0K Jan 20 15:52 c4d2333131751fb21644a5d651b95ef2
drwxr-xr-x  3 realm realm 4.0K Feb  2 16:39 cc8e773fd486eadd4bc0d7ecdd8cbe0b
drwxr-xr-x  4 realm realm 4.0K Feb  1 17:24 d430adfa0c393d9dc6b1dbd0bd6aaef2
drwxr-xr-x  4 realm realm 4.0K Jan 20 19:39 d87f458af1f9b5b6f3a1501324fbea44
drwxr-xr-x  4 realm realm 4.0K Jan 20 17:27 e46a465d82af8f9834485e0b7ea872b2
drwxr-xr-x  3 realm realm 4.0K Feb  2 16:33 e565595cffd7202f1f4605d5f3586aa2
drwxr-xr-x  4 realm realm 4.0K Feb  1 20:35 fa4290cb3f6a56968bab721cfdbd323e
-rw-r--r--  1 realm realm  12K Feb  1 20:35 __permission.realm
-rw-r--r--  1 realm realm 1.4K Feb  1 20:43 __permission.realm.lock
drwxr-xr-x  2 realm realm 4.0K Jan 20 15:46 __permission.realm.management`

and (I had to use Sudo) `ls -alh /var/lib/realm/object-server/user_data/`:
`total 676K
drwxr-x--- 23 realm realm 4.0K Jan 11 20:28 .
drwxr-xr-x  6 realm realm 4.0K Jan 20 15:46 ..
drwxr-xr-x  3 realm realm 4.0K Dec  1 18:54 044595682eee387b657b78950c3a63ff
drwxr-xr-x  3 realm realm 4.0K Nov 16 18:32 07ccb2d8520713763f76c9cd16a44cf5
drwxr-xr-x  3 realm realm 4.0K Dec 12 21:57 29f867ce69b65f52a8a21a88f808322b
drwxr-xr-x  3 realm realm 4.0K Nov 16 21:22 37bd68cb2ec0056eb8e60ead340555de
drwxr-xr-x  3 realm realm 4.0K Dec 13 15:58 49aff9c85a5fd537edb23366db73d0b3
drwxr-xr-x  3 realm realm 4.0K Jan  3 22:01 4bcabd8859fa72c91d78cb8a4f4f730a
drwxr-xr-x  3 realm realm 4.0K Nov 16 17:11 742748e40093638063e1998e9d1a9532
drwxr-xr-x  3 realm realm 4.0K Jan 11 20:28 745f5b9baf4208d950150b0a0dd810a4
drwxr-xr-x  3 realm realm 4.0K Dec 12 21:11 7f016552c4d93f02887a2ca4d84dbe39
drwxr-xr-x  3 realm realm 4.0K Dec 30 20:03 93a048fdfdee58b12be6d798277c8743
drwxr-xr-x  3 realm realm 4.0K Nov 22 15:48 98b9c921e99fb3d1fa4b2df9193b4cb8
drwxr-xr-x  3 realm realm 4.0K Nov 15 19:03 9cb2f1026948128952f6c0b50eaa4db4
drwxr-xr-x  3 realm realm 4.0K Jan  3 21:51 a4316734f5733795465b6234c0d3c9be
drwxr-xr-x  3 realm realm 4.0K Nov 15 19:10 a7ee354170446307e375ec8e900c22e7
-rw-r--r--  1 realm realm 576K Jan 20 14:45 __admin.realm
-rw-r--r--  1 realm realm 1.4K Feb  1 20:45 __admin.realm.lock
drwxr-xr-x  2 realm realm 4.0K Nov 15 18:57 __admin.realm.management
drwxr-xr-x  3 realm realm 4.0K Nov 15 20:11 b11b9c2229a462678de47dfe4c15c967
drwxr-xr-x  3 realm realm 4.0K Jan 10 17:35 c4d2333131751fb21644a5d651b95ef2
drwxr-xr-x  3 realm realm 4.0K Jan  7 17:18 d430adfa0c393d9dc6b1dbd0bd6aaef2
drwxr-xr-x  3 realm realm 4.0K Dec  1 18:57 d87f458af1f9b5b6f3a1501324fbea44
drwxr-xr-x  3 realm realm 4.0K Dec 27 21:41 e46a465d82af8f9834485e0b7ea872b2
drwxr-xr-x  3 realm realm 4.0K Nov 29 22:36 edf199e7549d4a8b009e4aba577b32aa`

3. When updating to 1.0.2 the logs said something about updating this file, I checked if something was off, but looks ok to me:
`# Realm Object Server Configuration
#
# For each possible setting, the commented out values are the default values
# unless another default is mentioned explicitly.
#
# Paths specified in this file can be either absolute or relative.
# Relative paths are relative to the current working directory.


## ----------------------------------------------------------------------------
## The following options are MANDATORY, either by providing them in this file,
## or as command-line options:
## - storage: root_path
## - auth:public_key_path
## - auth:private_key_path
## ----------------------------------------------------------------------------


storage:
  ## The directory in which the realm server will store all its data files.
  ## This configuration option is MANDATORY.
  root_path: /var/lib/realm/object-server

## ----------------------------------------------------------------------------

auth:
  ## The path to the public and private keys (in PEM format) that will be used
  ## to validate identity tokens sent by clients.
  ## These configuration options are MANDATORY.
  public_key_path: /etc/realm/token-signature.pub
  private_key_path: /etc/realm/token-signature.key

  sync_hosts:
    ## The hosts for which the authentication service will consider itself
    ## authoritative. It will decline to process any kind of requests for Realm
    ## files at other URLs. Addresses specified here must include host and port
    ## (authority part of the URL according to RFC 3986) on which the sync
    ## server is externally reachable.

    ## Additionally if a proxy server for the given protocol is configured, it
    ## will also accept requests for Realm files at these hosts:
    # - ${proxy:http:listen_address}:${proxy:http:listen_port}
    # - ${proxy:https:listen_address}:${proxy:https:listen_port}

    ## The derived hosts will also include:
    ##    The aliases for local addresses with the following host names:
    ##     '127.0.0.1', 'localhost' and '::1'.
    ##    The addresses for each configured sync worker (Enterprise Edition)

  ttls:
    ## The validity duration for Refresh Tokens. This can be a fairly high
    ## value, ranging from a single day to multiple years, depending on
    ## individual needs. Whenever the Refresh Token expires, clients will be
    ## forced to delegate again to the authorizing party. If the credentials
    ## there can be revoked by the user or are not opaquely managed by the
    ## client, then this would force the user to manual intervention after the
    ## expiration. Depending on the use case, this can be either desired or
    ## should be prevented. This value is represented in seconds.
    ## Default: 10 years.
    # refresh_token: 315360000

    ## The validity duration for Access Tokens. This should be a fairly small
    ## number, especially if you are concerned with revocations being applied
    ## quickly. This value is represented in seconds. Default: 10 minutes
    # access_token: 600

  providers:
    ## Providers of authentication tokens. Each provider has a configuration
    ## object associated with it. If a provider is included here and its
    ## configuration is valid, it will be enabled.

    ## Possible providers: cloudkit, debug, google, facebook, realm, password
    ## Providers 'realm' and 'password' are always enabled:
    ## - The 'realm' provider is used to derive access tokens from a refresh token.
    ## - The 'password' provider is required for the dashboard to work. It supports
    ##   authentication through username/password and uses a PBKDF2 implementation.

    ## This enables login via CloudKit's user record name.
    # cloudkit:
      ## The key ID retrieved when adding the public key derived from the
      ## specified private_key_path in CloudKit's Server-to-Server Keys,
      ## available through the API Access settings in the CloudKit dashboard.
      # key_id: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'

      ## The path to the certificate.
      # private_key_path: 'cloudkit_eckey.pem'

      ## The container identifier in reverse domain name notation.
      # container: "iCloud.io.realm.exampleApp.ios"

      ## The environment in which CloudKit should be used. The default is
      ## 'development'. For the production deployment for apps on the AppStore
      ## you must specify 'production'.
      # environment: 'development'

    ## This enables authentication via a Google Sign-In access token for a
    ## specific app.
    # google:
      ## The client ID as retrieved when setting up the app in the Google
      ## Developer Console.
      # clientId: '012345678901-abcdefghijklmnopqrstvuvwxyz01234.apps.googleusercontent.com'

    ## This enables authentication via a Facebook access token for a specific app.
    ## This provider needs no configuration (uncommenting the next line enables it).
    # facebook: {}

## ----------------------------------------------------------------------------

proxy:
  ## Network settings for the externally accessible proxy module.
  ## This can be enabled for both HTTP and HTTPS traffic simultaneously, and
  ## forwards traffic to the sync and services internal modules.
  ## It is possible to disable and replace the proxy module by another reverse proxy.
  ##
  ## Note: The proxy module forwards traffic to the internal modules on the
  ## addresses and ports they listen on (as configured in the `network' section below).
  ##
  ## Shown below is a diagram of the default network configuration:
  ##
  ##                                                                     +----------------------+
  ##                                                                     |                      |
  ##                                                                     |     Sync module      |
  ##                                                                     |                      |
  ##                                                                     |      (internal)      |
  ##                                                                     |                      |
  ##                                                                 +-> |  Defaults:           |
  ## +----------------+             +---------------------------+    |   |   Listen: 127.0.0.1  |
  ## |                |             |                           |    |   |   Ports:             |
  ## |  Realm Client  +------+      |        Proxy module       |    |   |    WS: tcp/27800     |
  ## |                |      |      |                           |    |   |                      |
  ## +-----------------      |      |  (externally accessible)  |    |   +----------------------+
  ##                         +----> |                           |    |
  ##                                |  Defaults:                |    |
  ##                         +----> |   Listen: 0.0.0.0         +----+
  ##      +------------      |      |   Ports:                  |    |   +----------------------+
  ##      |           |      |      |    HTTP & WS: tcp/9080    |    |   |                      |
  ##      |  Browser  +------+      |    HTTPS & WSS: tcp/9443  |    |   |    Services module   |
  ##      |           |             |                           |    |   |                      |
  ##      +-----------+             +---------------------------+    |   |      (internal)      |
  ##                                                                 +-> |                      |
  ##                                                                     |  Defaults:           |
  ##                            Note: The proxy module can be            |   Listen: 127.0.0.1  |
  ##                                  replaced by NGINX or other         |    Ports:            |
  ##                                  reverse proxies                    |     HTTP: tcp/27080  |
  ##                                                                     |                      |
  ##                                                                     +----------------------+

  http:
    ## Whether or not to enable the HTTP proxy module. It enables multiplexing requests
    ## by forwarding incoming requests on a single port to all services.
    # enable: true

    ## The address/interface on which the HTTP proxy module should listen. This defaults
    ## to 127.0.0.1. If you wish to listen on all available interfaces,
    ## uncomment the following line.
    listen_address: '::'

    ## The port that the HTTP proxy module should bind to.
    # listen_port: 9080

  https:
    ## Whether or not to enable the HTTPS proxy module. It enables multiplexing requests
    ## by forwarding incoming requests on a single port to all services.
    ## Note that even if it enabled, the HTTPS proxy will only start if supplied
    ## with a valid pair of certificates through certificate_path and private_key_path below.
    # enable: false

    ## The path to the certificate and private keys (in PEM format) that will be used
    ## to set up the HTTPS server accepting connections.
    ## These configuration options are MANDATORY to start the HTTPS proxy module.
    # certificate_path: 'keys/https-proxy.crt'
    # private_key_path: 'keys/https-proxy.key'

    ## The address/interface on which the HTTPS proxy module should listen. This defaults
    ## to 127.0.0.1. If you wish to listen on all available interfaces,
    ## uncomment the following line.
    # listen_address: '::'

    ## The port that the HTTPS proxy module should bind to.
    # listen_port: 9443

## ----------------------------------------------------------------------------

network:
  ## Network settings for internal modules, to which traffic is forwarded from
  ## the proxy module. The proxy module will automatically forward traffic to the
  ## internal modules on the ports they are configured to listen on in this section.

  http:
    ## The address/interface on which the server should listen for HTTP
    ## services. This includes Dashboard and Authentication APIs.
    ## This defaults to 127.0.0.1. If you wish to listen on all available
    ## interfaces, uncomment the following line.
    # listen_address: '0.0.0.0'

    ## The port on which to listen for incoming requests to the Dashboard
    ## and authentication APIs. This defaults to 27080.
    # listen_port: 27080

## ----------------------------------------------------------------------------

sync:
  ## Enterprise Edition only:
  ## Synchronization service settings, including clustering and load balancing.

  servers:
    ## An array of entries describing the cluster configuration.
    ##
    ## If no servers are configured, a default entry is inserted with the
    ## following settings:
    ##   - id: '0'
    ##     address: '0.0.0.0'
    ##     port: 27800
    ##
    ## Each entry must contain the following entries:
    ##
    ##    'id': A unique string ID used to distinguish between backend servers.
    ##          This must remain stable, even if the particular backend server
    ##          is moved to a different address or port.
    ##
    ##    'address': The address of the cluster participant. If '0.0.0.0' or
    ##               '::', a sync server will be started on localhost (listening
    ##               on '127.0.0.1' or '::1', respectively). Otherwise, it is
    ##               assumed that the sync server is an external process,
    ##               potentially on a separate machine.
    ##
    ##    'port': The port on which to connect to the particular cluster node.
    ##            If address was '0.0.0.0' or '::', this is also the port number
    ##            on which the local cluster node will listen for connections.

## ----------------------------------------------------------------------------

logging:
  ## The logging level of the server.
  ##
  ## Note: This used to be an integer, but has been updated to be more
  ## descriptive. The integer values are no longer supported.
  ##
  ## Possible values (from most to least verbose):
  ##
  ##   all: no filtering
  ##   trace
  ##   debug
  ##   detail
  ##   info: good for production (default)
  ##   warn
  ##   error
  ##   fatal
  ##   off: all output suppressed
  # level: 'info'

  ## The file to which the synchronisation server should log. This should
  ## be a writable path from the perspective of the user under which the
  ## server runs. If no path is specified, the server will log to stdout.
  path: /var/log/realm-object-server.log

## ----------------------------------------------------------------------------

performance:
  ## The maximum number of Realm files that the server will have open
  ## concurrently (LRU cache). The default is 256.
  ## Only change this option if directed to by Realm support.
  # max_open_files: 256

## ----------------------------------------------------------------------------

backup:
  ## Enterprise Edition only:
  ## The backup is a server that delivers continuous backup of the Realms in
  ## storage.root_path specified above. The backup is delivered to all connected
  ## backup clients. Backup clients must be started separately with network
  ## configuration parameters matching those of the server.

  ## Whether or not to enable the backup server.
  enable: true

  network:
    ## The address/interface on which the backup server should listen. This
    ## defaults to 127.0.0.1. If you wish to listen on all available interfaces,
    ## uncomment the following line.
    # listen_address: '0.0.0.0'

    ## The port on which to listen. The backup server uses port 27810 by
    ## default. For most deployments, there should not be a need to change this.
    # listen_port: 27810

  logging:
    ## The logging level of the backup server.
    ## The values are identical to the logging levels described above.
    ## The default level is 'info'.
    # level: 'info'

    ## The file to which the synchronisation server should log. This should
    ## be a writable path from the perspective of the user under which the
    ## server runs. If no path is specified, the server will log to stdout.
    path: '/var/log/realm-object-server-backup-server.log'`

4.
`sudo apt-get update
sudo apt-get upgrade`
Maybe my mistake was not stopping first the process, but logs didn't show any errors about that, but you tell me.


PS. I think i'm kinda happy that this "clean up" happened since now Realm Browser shows me again the Realms when I connect to object server (before I had to copy the id and connect with 'open realm url')

**Comment by radu-tutueanu** [comment]
Thank you for the information. Sorry for the late reply, I was out of office.

To recap, the problem was that you lost all users between 1.0.0 and 1.0.2.

Pre 1.0 the ROS used `/var/lib/realm/object-server/user_data/` and after 1.0 it uses  `/var/lib/realm/object-server/0/user_data/`.
Did you copy data from /var/lib/realm/object-server/user_data/ to /var/lib/realm/object-server/0/user_data/ manually after 1.0 ?

If so, the upgrade procedure from 1.0.0 to 1.0.2 shouldn't have done anything.

If you want to recover your accounts, you can try the following:

1. move `/var/lib/realm/object-server/0/user_data/__admin.realm` to a safe location(might want to restore it in case something goes wrong.)
2. copy `/var/lib/realm/object-server/user_data/__admin.realm` to `/var/lib/realm/object-server/0/user_data/__admin.realm`
3. move /var/lib/realm/object-server/internal_data and /var/lib/realm/object-server/tmp to a safe location(so the folders are empty)
4. start the server

That should allow you to use the old accounts. Whatever accounts you have created in the meantime would be lost though.

Please let me know how that works out.

**Comment by rishabhparikh** [comment]
I'm having a similar problem, except without upgrading. This morning I saw that none of my users were able to log in, and when I went to my Object Server's dashboard, it asked me to create a new admin account. After I did, I see that all my users are gone. The realm files seem to still exist, but the Object Server doesn't seem to recognize them.

I was running v1.0.0. Looking through the logs I see that last night there was some kind of mass refresh that may have crashed the Object Server:

```
2017-03-01T23:39:13.714Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...jmmy+/A8PqvdPHbLDNItZJby10Mw==')
2017-03-01T23:39:55.986Z - info: sync-server: Connection[69510]: Session[1]: Received: REFRESH(signed_user_token='...a4Sr93fbtIcf6JYVXdehxbHPt5Fg==')
2017-03-01T23:40:03.607Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...iYfiU11foXDIoPu3EjO8Ryomha8A==')
2017-03-01T23:40:46.677Z - info: sync-server: Connection[69510]: Session[1]: Received: REFRESH(signed_user_token='...mHkYxyrxxBTmgK48LeaWndK6v+7A==')
2017-03-01T23:40:53.580Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...VILN4sLnZB80IkCwN5cF9cE4CeQA==')
2017-03-01T23:41:37.140Z - info: sync-server: Connection[69510]: Session[1]: Received: REFRESH(signed_user_token='...mgkPciiNnX9e1OpLpaWpAeGB4xYw==')
2017-03-01T23:41:43.624Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...XVpqK/zw1fl1QPwWJqtxbiUXT91g==')
2017-03-01T23:42:28.030Z - info: sync-server: Connection[69510]: Session[1]: Received: REFRESH(signed_user_token='...tkKtWEJKVXFl7fCn/QsuZmc7Y5Ew==')
2017-03-01T23:42:33.615Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...akI2WySYJtfBA1QcHJlEMEub7p6Q==')
2017-03-01T23:43:17.904Z - info: sync-server: Connection[69510]: Session[1]: Received: REFRESH(signed_user_token='...8QxgMAGu9ZBTc5xe+XuoK2hYzbyg==')
2017-03-01T23:43:23.629Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...zoZo9FiakMkIZobzQpQIl1v+WYTQ==') ...
```

Then a little later in the logs I see the Object Server appearing to restart for whatever reason. What's weird is it says Realm sync server started ([realm-core-2.3.0], [realm-sync-1.0.0-BETA-7.3]).

```
2017-03-02T01:16:51.854Z - info: sync-server: Connection[69510]: Session[1]: Received: REFRESH(signed_user_token='...yDgqxEdSvX4M6RwQJR+3JlPyKbFA==')
2017-03-02T01:16:57.682Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...dwSwn743BoFKv4CtcyXQvq1ECgxA==')
2017-03-02T01:17:19.024Z - warn: auth.password: Handle request failed with: InvalidCredentials: The provided credentials are invalid.: Given account: redacted@gmail.com
2017-03-02T01:17:22.422Z - info: sync-server: Connection[69579]: Session[1]: Received: REFRESH(signed_user_token='...c3Xs3XV0e9hA7t5cP9aA9OhmNONA==')
2017-03-02T01:17:28.069Z - warn: auth.password: Handle request failed with: InvalidCredentials: The provided credentials are invalid.: Given account: redacted@gmail.com
2017-03-02T01:17:37.049Z - warn: auth.password: Handle request failed with: InvalidCredentials: The provided credentials are invalid.: Given account: redacted@gmail.com
2017-03-02T01:17:42.689Z - info: sync-server: Connection[69510]: Session[1]: Received: REFRESH(signed_user_token='...+ZYAqjhMDNTS/UFMe1kuUkNDgmmQ==')
2017-03-02T01:17:42.696Z - warn: auth.password: Handle request failed with: InvalidCredentials: The provided credentials are invalid.: Given account: redacted@gmail.com
2017-03-02T01:17:47.573Z - info: sync-server: Connection[69565]: Session[1]: Received: REFRESH(signed_user_token='...fTMIpdQdqj49fHzLFvBchxoCZorA==')
2017-03-02T01:18:13.273Z - info: sync-server: Connection[69579]: Session[1]: Received: REFRESH(signed_user_token='...1qsR6x/QMedVZtAKOWopaedqQfVw==')
2017-03-02T01:18:57.140Z - info: Backup admin-Realm file written to /var/lib/realm/object-server/internal_data/oldAuth.realm.bak (in case of unexpected failures during the upgrade).
2017-03-02T01:18:57.236Z - info: Realm Object Server sync engine listening on 127.0.0.1:27800.
2017-03-02T01:18:57.268Z - info: permission: Seed permission-Realms
2017-03-02T01:18:57.290Z - info: Realm Object Server web server listening on 127.0.0.1:27080.
2017-03-02T01:18:57.295Z - info: http proxy listening on :::9080.
2017-03-02T01:18:57.303Z - info: The Realm Object Server requires an initial admin user to start. To continue, please open your web browser to access the dashboard at: http://127.0.0.1:27080 and register your user.
2017-03-02T01:18:57.305Z - info: sync-server: Realm sync server started ([realm-core-2.3.0], [realm-sync-1.0.0-BETA-7.3])
2017-03-02T01:18:57.305Z - info: sync-server: Directory holding persistent state: /var/lib/realm/object-server/0/user_data
2017-03-02T01:18:57.306Z - info: sync-server: Listening on 127.0.0.1:27800 (sync protocol version 16)
2017-03-02T01:18:57.306Z - info: client: Opening Realm file: /var/lib/realm/object-server/internal_data/auth.realm
2017-03-02T01:18:57.306Z - info: client: Connection[1]: Session[1]: Starting session for '/var/lib/realm/object-server/internal_data/auth.realm'
2017-03-02T01:18:57.306Z - info: client: Connection[1]: Resolving ':::9080'
2017-03-02T01:18:57.306Z - info: client: Connection[1]: Connecting to endpoint ':::9080' (1/1)
2017-03-02T01:18:57.306Z - error: client: Connection[1]: Failed to connect to endpoint ':::9080': Connection refused
2017-03-02T01:18:57.306Z - error: client: Connection[1]: Failed to connect to ':::9080': All endpoints failed
2017-03-02T01:18:57.306Z - info: client: Opening Realm file: ./realm-object-server/listener/__admin.realm
2017-03-02T01:18:57.306Z - info: client: Connection[2]: Session[1]: Starting session for './realm-object-server/listener/__admin.realm'
2017-03-02T01:18:57.306Z - info: client: Connection[2]: Resolving ':::9080'
2017-03-02T01:18:57.307Z - info: client: Connection[2]: Connecting to endpoint ':::9080' (1/1)
2017-03-02T01:18:57.307Z - error: client: Connection[2]: Failed to connect to endpoint ':::9080': Connection refused
2017-03-02T01:18:57.307Z - error: client: Connection[2]: Failed to connect to ':::9080': All endpoints failed
2017-03-02T01:18:57.307Z - info: client: Opening Realm file: /var/lib/realm/object-server/internal_data/permission/__auth.realm
2017-03-02T01:18:57.307Z - info: client: Connection[3]: Session[1]: Starting session for '/var/lib/realm/object-server/internal_data/permission/__auth.realm'
2017-03-02T01:18:57.314Z - info: client: Connection[3]: Resolving ':::9080'
2017-03-02T01:18:57.314Z - info: client: Connection[3]: Connecting to endpoint ':::9080' (1/1)
2017-03-02T01:18:57.314Z - error: client: Connection[3]: Failed to connect to endpoint ':::9080': Connection refused
2017-03-02T01:18:57.314Z - error: client: Connection[3]: Failed to connect to ':::9080': All endpoints failed
2017-03-02T01:18:57.314Z - info: client: Opening Realm file: /var/lib/realm/object-server/internal_data/permission/__global.realm
2017-03-02T01:18:57.314Z - info: client: Connection[4]: Session[1]: Starting session for '/var/lib/realm/object-server/internal_data/permission/__global.realm'
2017-03-02T01:18:57.314Z - info: client: Connection[4]: Resolving ':::9080'
```
I never tried upgrade from 1.0.0 so I'm not sure why this happened. I tried following the steps above but now I can't seem to even start the service. Starting with systemd gives me the following error. Upgrading and reinstalling seem to have no effect.

```
● realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: core-dump) since Thu 2017-03-02 11:37:08 UTC; 26min ago
  Process: 25732 ExecStart=/usr/bin/realm-object-server -c /etc/realm/configuration.yml (code=dumped, signal=ABRT)
 Main PID: 25732 (code=dumped, signal=ABRT)

Mar 02 11:37:08 ip-172-31-15-47 systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Mar 02 11:37:08 ip-172-31-15-47 systemd[1]: realm-object-server.service: Unit entered failed state.
Mar 02 11:37:08 ip-172-31-15-47 systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Mar 02 11:37:08 ip-172-31-15-47 systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Mar 02 11:37:08 ip-172-31-15-47 systemd[1]: Stopped Realm Object Server.
Mar 02 11:37:08 ip-172-31-15-47 systemd[1]: realm-object-server.service: Start request repeated too quickly.
Mar 02 11:37:08 ip-172-31-15-47 systemd[1]: Failed to start Realm Object Server.
```

This is a huge problem as this was my production realm object server instance with all of my customer's accounts. Any help restoring the object server would be much appreciated.

**Comment by teotwaki** [comment]
Hi @rishabhparikh,

This seems to be another issue, unrelated to the upgrade. Any chance you can ping me at help@realm.io so we can jump on a call?

Thanks.

**Comment by rishabhparikh** [comment]
Hey @teotwaki,

Just sent you an email. Thanks for your help.
