### ISSUE TITLE
Creating large number of records by bulk does not complete

### ISSUE THREAD

**Issue by gregiii** [realm/realm-mobile-platform#124]
## Goals

What do you want to achieve?

I'm trying to migrate a large amount of data, around 250K records from Parse database to Realm Object Server. More concretely, the records are Message objects with nested User and Group objects.

## Expected Results

What did you expected to happen?

I expected to see the Message objects in the Realm Browser written together with the nested objects User and Group.

## Actual Results

The script hangs when it reaches around 9K records. Also, some records did not have the embedded Group object , and some did not have the User object. 

I also tried saving only the string and date properties, so no querying involved. It ran up to around 29K records then the process just hanged.

There were no error messages both on the client and server side. The client process did not crash although pressing CTRL-C could not exit to the command prompt. I have to close the Terminal window.

I have also tried placing the query.each() block inside the realm.write() transaction block but then nothing happens and no records are saved at all.

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

## Code Sample

```
var MessageSchema = {
  name: 'Message',
  primaryKey: 'objectId',
  properties : {
    objectId: 'string',
    createdAt: 'date',
    updatedAt: 'date',
    group: 'Group',
    sender: 'User',
    text: 'string'
  }
}
```

```
var UserSchema = {
  name: 'User',
  primaryKey: 'objectId',
  properties : {
    objectId: 'string',
    createdAt: 'date',
    updatedAt: 'date',
    username: 'string',
    email: 'string',
    firstName: 'string',
    lastName: 'string'
  }
}
```

```
var GroupSchema = {
  name: 'Group',
  primaryKey: 'objectId',
  properties : {
    objectId: 'string',
    createdAt: 'date',
    updatedAt: 'date',
    name: 'string',  
  }
}
```

```
var admin_user = Realm.Sync.User.adminUser(Config.REALM_ADMIN_TOKEN);

var realm = new Realm({
  sync: {
    user: admin_user,
    url: Config.SERVER_URL,
  },
  schema: [UserSchema, GroupSchema, MessageSchema]
});

var query = new Parse.Query("Message");
query.each(function(message) {
  realm.write( function() {
    var values = Message.fromParse(message, realm);
     var newObject = realm.create('Message',values, true);
     console.log(++counter + ": Created new Message "  + newObject.objectId);
   });
});
```

Note that inside the function that converts the Parse object into a Realm object, I do a realm.objectWithPrimaryKey() query for the User and Group objects. The User and Group collections have been pre-populated already by previous scripts.

Here's a snippet of the conversion function:

```
var fromParse = function(object, realm) {
  var objectId = object.id;
  var values = {
      objectId: objectId,
      createdAt: object.get('createdAt'),
      updatedAt: object.get('updatedAt'),
      uuid: object.get('messageUUID')
  };

  if (object.get('text')) {
    values.text = object.get('text');
  }
  var pfSender = object.get('user');
  if(pfSender && pfSender.id) {
    var rlSender = realm.objectForPrimaryKey('User',pfSender.id);
  
    if (rlSender) {
      console.log("Message sent by " + rlSender.objectId);
      values.sender = rlSender;
    }
  }

 var pfGroup = object.get('circle');
  if(pfGroup && pfGroup.id) {
    var rlGroup = realm.objectForPrimaryKey('Group',pfGroup.id);
  
    if (rlGroup) {
      console.log("Message belongs to " + rlGroup.objectId + " group ");
      values.group = rlGroup;
    }
  }
  return values;
}
```

## Version of Realm and Tooling

Realm Object Server Version:  realm-object-server-professional (1.0.2-205)
Flavor:  Professional 

Server OS & Version: ?Ubuntu 16.04

Client SDK Version:  realm-1.0.2-professional node.js

Client OS & Version:  MacOS Sierra

**Comment by teotwaki** [comment]
Hi,

Thanks for the great issue report. Looks like we have everything we need to move ahead on this. My first suspicion is that you're hitting the 16MB commit size limit (this is a temporary thing, we're working on having that removed soon).

Could you try committing the transaction every once in a while (every couple thousand objects) to see whether that works around the issue?

In the meantime, I'll have someone try to reproduce this. Just so I know, how many users and groups do you have?

**Comment by gregiii** [comment]
There are basically two issues here. The first issue, the process not completing, I think is due to memory or CPU constraints. I was running on a t2.micro EC2 instance with 1 GB RAM and I saw CPU utilization go up to 100%. When I upgraded the instance to a t2.medium with 4GB RAM and 2 CPUs, the script was able to process all 250K records (around 4 hours of runtime). 

However, I still still saw some records having nil Group and User properties, especially the first 50 records or so. This was the second issue. What I did then was to do a query for all objects right after opening the realm and waiting a few seconds using a do-nothing for-loop before starting the to loop through all records:

```
var admin_user = Realm.Sync.User.adminUser(Config.REALM_ADMIN_TOKEN);

var realm = new Realm({
  sync: {
    user: admin_user,
    url: Config.SERVER_URL,
  },
  schema: [UserSchema, GroupSchema, MessageSchema]
});

var users = realm.object('User');
var groups = realm.object('Group');
sleep();

var query = new Parse.Query("Message");
query.each(function(message) {
  realm.write( function() {
    var values = Message.fromParse(message, realm);
     var newObject = realm.create('Message',values, true);
     console.log(++counter + ": Created new Message "  + newObject.objectId);
   });
});

function sleep() {
  for (var i = 0; i < 100000; i++) {
    for (var j = 0; j < 1000000; j++) {
      //console.log("Sleeping " + i);
    }
  }
}
```

I repeated this tests several times and I can confirm that without the initial query for all objects and without the delay before starting the processing of the records, the first 40-50 records will get null values for the objectForPrimaryKey() queries. After that, the rest of the 250K records will have their nested Group and User properties written.

I guess it takes a finite amount of time to populate the cache before you can start performing queries, and if you start querying before the cache is ready, you will get null even if the objects are actually in the collection at the server.

**Comment by teotwaki** [comment]
Am I correct in assuming that the users and groups are pre-populated in the Realm before running this script?

Is the local Realm primed, or are you starting from an empty database that has to be synced from the server?

If this is the case, we have an API that lets you check whether the sync download has finished, but I need to check whether that's available in your build, and will get back to you on that on Monday. In the meantime, you could probably use the collection notifications to know when the data is available.

https://realm.io/docs/javascript/latest/#collection-notifications

**Comment by gregiii** [comment]
@teotwaki ,

Yes, the users and groups are pre-populated. There are around 1,200 users and 1,500 groups. I guess I'm starting from a local database since this is a one-off script to fetch data from the Parse database.

I'll try the collection notifications as you suggested

**Comment by teotwaki** [comment]
@gregiii,

Just to confirm, the `waitForDownload` API isn't available yet in JS, so using the notifications is the right workaround at this time.

Have a nice weekend!

**Comment by bigfish24** [comment]
@gregiii did you have any luck?

**Comment by gregiii** [comment]
This is how I did the migration. The trick is to wait until the local realm file is "primed" with the objects that you will be querying. In my case, each Message object I'm migrating has a nested User and Group object, so I fire listeners for the two and wait until I get all of them in. One caveat: you have to know in advance more or less how many objects you are expecting. The doneWithGroups and doneWithUsers flag is to ensure that the runMigration() function is only run once, because the addListener callback can fire several times before it reaches your target number.

This could probably be better coded using javascript Promises, but I'm not good at making Promises :). This hack get's my job done until the waitForDownload API becomes available. 

```
var doneWithGroups = false;
var doneWithUsers = false;

realm.objects('Group').addListener(function(objects, changes) {
  console.log("Group: ", objects.length, " Insertions: ", changes.insertions.length);
  if (objects.length >= 1563 && !doneWithGroups) {
    doneWithGroups = true;
    console.log("Got all Groups. Getting users.");
    
    realm.objects('User').addListener(function(objects, changes) {
      console.log("Users: ", objects.length, " Insertions: ", changes.insertions.length);
      if (objects.length >= 1218 && !doneWithUsers) {
        doneWithUsers = true;
        console.log("Got all users. Running migration script now.");
        runMigration(realm, Parse, Message, Thread);
      }
    });
  }
});

function runMigration(realm, Parse, Message, Thread) {
 ...
}
```

**Comment by teotwaki** [comment]
@gregii Excellent to hear you got the migration finished!

Do you think we should close this issue and push more towards having the `waitForDownload` API available?

**Comment by gregiii** [comment]
@teotwaki Yes, sure. I'll close this issue now. Thanks for the help.
