### ISSUE TITLE
Multiple applications syncing via same database? 

### ISSUE THREAD

**Issue by jdmarshall90** [realm/realm-mobile-platform#132]
Does Realm Object Server support multiple applications syncing the same database? For instance, 2 separate iPhone apps and a macOS app sharing data.

**Comment by jdmarshall90** [comment]
To clarify, by "separate apps", I mean 2 of my apps on a single phone, not one app on multiple phones.

**Comment by MattW86** [comment]
Hi @jdmarshall90,
It is  possible as long as they both hit the same endpoint such as http://yourdomain.com:9080/~/RealmName. We have 2 versions of the same app, one free and one paid and they are using the same endpoint without any issues.

**Comment by bigfish24** [comment]
Following up and echoing @MattW86 that this is possible. The only limitation is that Realm Object Server doesn't support multiple apps from an authentication perspective. All the users across the apps are organized together in ROS, but each user will have his/her own unique path.

**Comment by jdmarshall90** [comment]
@bigfish24 could you elaborate please?

**Comment by bigfish24** [comment]
What I mean is that you can have multiple apps working with ROS as long as you don't need the users of each app to be fully isolated, such as to prevent username collisions. As long as that doesn't matter, then you can just point each app to the Realm backend and ROS will authenticate and create a unique user for each app's user, given them a unique path in the ROS for their synced Realms (`/~/myRealm`)

**Comment by jdmarshall90** [comment]
Hmm, in that case would the isolated apps be able to share data?

**Comment by jpsim** [comment]
Yes, what Adam is saying here is that users aren't scoped per application, they're scoped per Realm Object Server (ROS). So there's no difference between "User One" on "App A" and "User One" on "App B" as far as ROS is concerned. However, if they're both to share data via the same synchronized Realm, they'll need sync-compatible schemas (one must be a strict subset of the other, or exactly the same, across all versions).

One more thing to keep in mind, despite both app A and B potentially being on the same device, logged in with the same user, their local Realms won't be stored in the same file, so sync changes will need to go through ROS before they can be seen from the other app on the device.

**Comment by teotwaki** [comment]
In addition, this would also double the storage considerations required on the client.

I'm tentatively closing this, as I believe the initial question has been answered. Feel free to ping me if you need more details.
