### ISSUE TITLE
Realm not synching when switching into and then out of Airplane mode. 

### ISSUE THREAD

**Issue by joshuapinter** [realm/realm-mobile-platform#133]
Hey guys, 

Just testing the automatic synching and network handling with Realm JS and the server. 

When I go into airplane mode and make a change then turn off airplane mode to get network activity again I was under the assumption that Realm would notice the change in network availability and automatically sync the changes the were done offline upstream to the server (and vice versa). 

Is that not the case? Is there a manual "sync" trigger that you need to call in order for the 2-way sync to pickup after an offline session? 

Many Thanks, 

Joshua

**Comment by joshuapinter** [comment]
After some further testing, it does seem to eventually complete the sync. But it can take a while and there's very little feedback for the user. 

I'll update my questions to these: 

1. Is there a manual sync method that can be called or is handled completely automatically? 

2. Are there updates or events that we can subscribe to when the synching is happening, e.g. to update the user?

3. When I turn Airplane mode on, my `realm.syncSession.state` continues to show 'active'. Does this ever change and is there a way to automatically update the UI with the actual current connection status? 

Many Thanks!

Joshua

**Comment by joshuapinter** [comment]
For reference, it takes about 30 seconds for a (small) sync to occur after coming back online from Airplane mode.

**Comment by austinzheng** [comment]
Hi Joshua,

Thanks for getting in touch with us. Right now, the synchronization network code doesn't take into account network reachability; it just retries network requests that fail in certain network-related ways while applying an increasing backoff delay between tries. This accords with your experience: the backoff maximum is 60 seconds, so 30 seconds to begin syncing again sounds right.

If you are running Realm JS on an Apple platform, we have a [change pending](https://github.com/realm/realm-object-store/pull/289) that will add support for network reachability. With this change, the sync subsystem should be able to detect when a network becomes reachable and immediately re-establish the connection. I'll work to get it included in a coming release. If you are running it on a different platform, I'll discuss with our binding engineers what they need to do to include reachability functionality.

We also have a backlog item to expose network status information to app developers. The ticket to track that is in a private repo, but I'll make a corresponding ticket in this repository.

I hope that answers your question, and thanks for using Realm!

**Comment by joshuapinter** [comment]
Thanks very much for the comprehensive reply, @austinzheng. I'm glad I'm not doing something wrong and these are known limitations. And I'm glad you guys are working on solving them. 

You've made a hell of a platform and these additions will tighten up the user experience so that it can be used in production.

I'm just beta testing the sync on iOS and MacOS so this should be fine until you get these updates in the next release.

Keen to follow the development updates.

Thanks again.

**Comment by jpsim** [comment]
Will close this since we're already tracking making these improvements, they're already under review, and from what I can tell we've sufficiently answered the questions you've asked here so far.

Please keep an eye on https://github.com/realm/realm-object-store/pull/289 to stay tuned!
