### ISSUE TITLE
Duplicate zip entry error on building project with realm-android-library-object-server

### ISSUE THREAD

**Issue by shogogan** [realm/realm-mobile-platform#134]
So, i'm trying to use the Realm Mobile Platform for a test application using clean architecture, looked on the demo to see which dependencies where used, and it didn't use anything new.

But, when i tried to make an SyncUser Object, i've got this error: "Cannot resolve symbol 'SyncUser'"

Looking a bit further on the internet i found this dependency: io.realm:realm-android-library-object-server:2.3.1
as i tried to compile, everything worked perfectly, except when i tried to build, it is where this error came out, and i am trying to find any solution for this.

> Warning:Exception while processing task java.io.IOException: Can't write [/home/victor.heck/SSD/CVS1/Android/TestProject/trunk/app/build/intermediates/transforms/proguard/debug/jars/3/1f/main.jar] (Can't read [/home/victor.heck/SSD/CVS1/Android/TestProject/trunk/app/build/intermediates/exploded-aar/io.realm/realm-android-library-object-server/2.3.1/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:io/realm/AndroidNotifier.class]))

Using Realm-Android 2.3.1 and Realm-Object-Server 1.0.3

Build.gradle (project)
```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.0'
        classpath 'io.realm:realm-gradle-plugin:2.3.1'
    }
}
```

Build.gradle (app module)
```
// Nothing important
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:25.1.1'
    compile 'com.caverock:androidsvg:1.2.1'

    compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.google.firebase:firebase-auth:10.0.1'
    compile 'com.google.firebase:firebase-config:10.0.1'
    compile 'com.google.firebase:firebase-storage:10.0.1'
    compile 'com.google.android.gms:play-services-auth:10.0.1'
    compile 'com.google.android.gms:play-services-maps:10.0.1'
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.google.android.gms:play-services-places:10.0.1'

    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.1.6'

    compile('com.google.api-client:google-api-client-android:1.22.0') {
        exclude group: 'com.google.android.google-play-services'
        exclude module: 'httpclient' //by artifact name
        exclude group: 'org.apache.httpcomponents' //by group
        exclude group: 'org.apache.httpcomponents', module: 'httpclient' //by both name and group
        exclude group: 'xpp3'
    }
    compile('com.google.api-client:google-api-client-xml:1.22.0') {
        exclude group: 'com.google.android.google-play-services'
        exclude module: 'httpclient' //by artifact name
        exclude group: 'org.apache.httpcomponents' //by group
        exclude group: 'org.apache.httpcomponents', module: 'httpclient' //by both name and group
        exclude group: 'xpp3'
    }

    compile 'com.google.maps.android:android-maps-utils:0.4'

    compile 'com.facebook.android:facebook-android-sdk:4.18.0'
    compile project(':data')
    compile project(':domain')
    compile project(path: ':smcore')
}
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.getkeepsafe.dexcount'
```

Build.gradle(data module)
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'io.realm:realm-android-library-object-server:2.3.1'
    compile 'com.android.support:appcompat-v7:25.1.0'
    testCompile 'junit:junit:4.12'
    compile project(path: ':domain')
}
```

**Comment by beeender** [comment]
You need below in your app's `build.gradle`:
```
realm {
  syncEnabled = true;
}
```
https://realm.io/docs/java/latest/#enabling-realm-mobile-platform

**Comment by shogogan** [comment]
wow, didn't notice these lines, thank you.

i thought that it would be on the Realm Mobile Platform section, instead of the Realm Mobile database section, sorry.

Well, it's working now, thanks

**Comment by shogogan** [comment]
So, i've got it working, except, not working as i wanted. 
I'm wanting to use it as a primary server, various users, access and interact betwee them.
But all the examples use the "~" in the url to indicate that it is THAT user's realm, so only that user can access.
I've tried to make one without it, got to create only using a admin user, and it came as a Read-Only, and not working properly the same way.

thinking like a chat: one user can comunicate with other users, access other users profiles, search for users, etc.

So i'm asking. it can be used as a primary server? or i should use it as a interactor between the web server and the application?

**Comment by cmelchior** [comment]
What exactly do you mean by using it as a primary server? It is possible for users to share Realms with other users by granting them permissions to do so: https://realm.io/docs/java/latest/#access-control

Depending on how you split your data, you can also create a shared static user that is embedded in your app that has access to all common metadata like user search etc.

Would that would in your case?

**Comment by shogogan** [comment]
Well, got to work with single realm, but not as a user realm: "realm://<serverip>:8090/app"
But i was thinking if it was meant to run this way, as there will be no user realm, only this static realm.

**Comment by cmelchior** [comment]
Hi @shogogan 
Sorry for the late response. You shouldn't need to define a global Realm for this to work. Can you try to describe what steps you took that didn't succeed?

**Comment by shogogan** [comment]
No problem,
Checked on the oher threads that somewhat went close to what i'm trying to do, and verified that it realm wouldn't be the best case for the main aplication, yet it would be great for some parts of it.
The intention is just like a social network, with any user searching any user, checking it's profile and things alike.
It would be necessary a shared realm for this, but while i was trying to use a global realm, the fact that realm doesn't have a verification checking if it's synced or something alike, made me drop the use for the main application, yet i pretend to use it for the chat of the application, or something like this.

**Comment by bmunkholm** [comment]
@shogogan We will very soon add API for sync progress information - the functionality is already available in our other SDKs, see e.g. here how it works for Swift: https://realm.io/docs/swift/latest/#progress-notifications
