### ISSUE TITLE
Shared Realm for all registered Users

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#135]
There could be data needed for an App which are the same for every user but which also can change. An example for that could be tax rates which are changing every year. As a good developer you dont want to hardcode these values. You want a central position for these data to be stored and changed and published to all clients. So I thought about creating a `Realm` which is accessible for ALL registered Users (read only) and only the Administrator should be able to write data.

Is it possible to create such a Realm which is readable for every registered User (automatically), which is also synchronyzing like a usual synced realm does and which is only writable for administrators?

**Comment by Montrazul** [comment]
There are some related tickets [here issue #52](https://github.com/realm/realm-mobile-platform/issues/52) and [here issue #42](https://github.com/realm/realm-mobile-platform/issues/42) but I could not find anything about how to implement it. Either im blind or it isnt mentioned in the realm documentation.

**Comment by Montrazul** [comment]
And also interesting would be how you can decide which realm objects should get synced with which realm.

For example you have the following objects which are all inheriting from realms `object`:

- ObjectA
- ObjectB
- ObjectC

If you open up your synced realm like the following:

```
SyncUser.logIn(with: credentials, server: server) { user, error in
    DispatchQueue.main.async {
                  
        if let user = user {
			self.setDefaultRealmConfiguration(user: user);
                    
        } else if let error = error {
        }
    }
}

private func setDefaultRealmConfiguration(user: SyncUser) {
    let configuration = Realm.Configuration(
        syncConfiguration: SyncConfiguration(user: user, realmURL: HelperRealm.getRealmURL()),
        schemaVersion: 1);
        
    Realm.Configuration.defaultConfiguration = configuration;
}
```

`ObjectA`, `ObjectB` and `ObjectC` are getting synchronized automatically. I have no option to exclude an object to get not synchronized with a given realm. For Example `ObjectC` could contain shared data which should only get synced with another realm so that the user realm should only sync `ObjectA` and `ObjectB` and the shared realm should only sync `ObjectC`.

**Comment by blablablario** [comment]
Hey Montrazul...

I think you can simply add a permission change to the Realm. 

`public PermissionChange(String realmUrl,
                        String userId,
                        Boolean mayRead,
                        Boolean mayWrite,
                        Boolean mayManage)
Construct a Permission Change Object.
Parameters:
realmUrl - Realm to change permissions for. Use * to change the permissions of all Realms.
userId - User or users to effect. Use * to change the permissions for all users.
mayRead - Define read access. true or false to request this new value. null to keep current value.
mayWrite - Define write access. true or false to request this new value. null to keep current value.
mayManage - Define manage access. true or false to request this new value. null to keep current value.`

If u use `*` as a `userId` it should grant acces to all users. Keep in mind that only the one who created the Realm can make a permission change.

**Comment by gritzko** [comment]
@Montrazul did that work for you?

**Comment by AshaChaparala** [comment]
![screenhot](https://user-images.githubusercontent.com/29660477/27580433-33f1e27a-5b48-11e7-9e7e-029c4f348289.png)
Which method i need to use to send token to other user?
Did  i need to use Firebase or i can share through realm only?

**Comment by bmunkholm** [comment]
@AshaChaparala This is unrelated to the current issue. Please use StackOverflow for usage related questions. Thanks.

@Montrazul Closing this due to no response. I assume you have gotten over this a long time ago :-)

**Comment by nishanthvasu** [comment]
HI bmunkholm ,

Is there any example code available for "Realtime Collaboration, Now For Every Mobile Developer" in github ?

Thanks,

**Comment by bmunkholm** [comment]
@nishanthvasu It's best to create new issues, instead of adding to others that are closed. But to answer quickly on this, please checkout https://github.com/realm-demos.
