### ISSUE TITLE
Unable to connect to ROS after upgrading to 1.1.0-257 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-mobile-platform#137]
I have just upgraded ROS (Ubuntu 16.04) using the exact commands here.
(https://realm.io/docs/realm-object-server/#upgrading)

After restarting I attempted to reach the dashboard in my browser.  I get "Safari can not connect...".

I have tried the IP address and the URL.  I have tried :80, :9080. :27080.  Always "can not connect".

When I try CURL - I get the message "connection refused".

I am able to SSH to the server.

I have restarted the server.  I have re-run the upgrade commands.  

When I run

`systemctl status realm-object-server`
```
● realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; vendor preset: enable
   Active: inactive (dead) since Fri 2017-02-24 22:17:22 UTC; 9min ago
  Process: 11527 ExecStart=/usr/bin/realm-object-server -c /etc/realm/configuration.yml (code=kill
 Main PID: 11527 (code=killed, signal=TERM)

```
Any advice appreciated.  

Realm Object Server Version: 1.1.0-257
Flavor: Developer
Server OS & Version: Ubuntu 16.04
Client OS & Version: iOS 2.4.3

**Comment by ianbradbury-bizzibody** [comment]
I tried un-installing and re-installing.

Uninstall
`sudo apt-get remove realm-object-server-developer`

Install
`sudo apt-get install realm-object-server-developer`

Start
`sudo systemctl start realm-object-server`

Now when I check the status I get...
```
systemctl status realm-object-server
● realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; ven
   Active: active (running) since Fri 2017-02-24 23:16:59 UTC; 1s ago
 Main PID: 14008 (realm-object-se)
    Tasks: 6
   Memory: 74.1M
      CPU: 1.279s
   CGroup: /system.slice/realm-object-server.service
           └─14008 /usr/bin/nodejs /usr/bin/realm-object-server -c /
```

Unfortunately the result is no different.  I am unable to browse or connect to the dashboard.  Or connect using the Realm Browser.

One thing I did notice.  If I try `node -v`, the server reports `The program 'node' is currently not installed. You can install it by typing: sudo apt install nodejs-legacy`

**Comment by ianpward** [comment]
hi @ianbradbury-bizzibody can you attach the realm-object-server.log output and also the `journalctl -xe | grep realm` output?

**Comment by ianbradbury-bizzibody** [comment]
Attached.

[journalctl -xe | grep realm.txt](https://github.com/realm/realm-mobile-platform/files/800974/journalctl.-xe.grep.realm.txt)

**Comment by teotwaki** [comment]
@ianbradbury-bizzibody It doesn't look like we're able to reproduce this. Could you tell us what version you upgraded from, and whether other changes have been made to the system?

Thanks.

**Comment by ianbradbury-bizzibody** [comment]
Definitely no other changes had been made to the system.  I am the only Admin so I can be sure of that.  ROS was at version 1.0.2.

Fortunately I had taken a snap shot of the server just a few days prior - so I have managed to recover the serve.  Of course I will need to upgrade at some point.  I'll definitely take another snapshot immediately prior to that event.

I guess to close this and I'll either ask to reopen or start a new issue when I do the upgrade.

**Comment by teotwaki** [comment]
@ianbradbury-bizzibody Any chance you would be willing to setup a clone, and let us attempt the upgrade so that we can see what is going on, first hand? We've done this a few times, using a shared SSH session so that you can see what we do, and then we can collect all the data we need.

**Comment by ianbradbury-bizzibody** [comment]
Sure.  I don't see why not.  

Could you private message me to organise a time and the logistics.  There is no sensitive data on the server as I'm "in development" so i'll be happy for you to do at a time that suits you.

Of course if it upgrades without issue I shall be jumping off the nearest cliff in shame  ;)

**Comment by teotwaki** [comment]
Emailed you last week, but didn't get a response.

**Comment by ianbradbury-bizzibody** [comment]
I've mailed directly.

**Comment by DanielAsher** [comment]
This just happened to me this morning (precisely the same behaviour). I upgraded from 1.0.0 and received:
```
sudo service realm-object-server status
● realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Wed 2017-03-15 08:00:13 UTC; 7min ago
  Process: 17442 ExecStart=/usr/bin/realm-object-server -c /etc/realm/configuration.yml (code=exited, status=99)
 Main PID: 17442 (code=exited, status=99)

Mar 15 08:00:13 ip-172-31-34-215 systemd[1]: realm-object-server.service: Main process exited, code=exited, status=99/n/a
Mar 15 08:00:13 ip-172-31-34-215 systemd[1]: realm-object-server.service: Unit entered failed state.
Mar 15 08:00:13 ip-172-31-34-215 systemd[1]: realm-object-server.service: Failed with result 'exit-code'.
Mar 15 08:00:13 ip-172-31-34-215 systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Mar 15 08:00:13 ip-172-31-34-215 systemd[1]: Stopped Realm Object Server.
Mar 15 08:00:13 ip-172-31-34-215 systemd[1]: realm-object-server.service: Start request repeated too quickly.
Mar 15 08:00:13 ip-172-31-34-215 systemd[1]: Failed to start Realm Object Server.
```
and
```
node -v
The program 'node' is currently not installed. You can install it by typing:
sudo apt install nodejs-legacy
```

**Comment by radu-tutueanu** [comment]
@ianbradbury-bizzibody was kind enough to setup a clone for us and even though the crash did not reproduce, we did find our issue with an inconsistent state that we are working on fixing.

@DanielAsher, if you do not have any confidential data on the server, would you be willing to setup access to the server and  email us the credentials to help@realm.io so that we can confirm that you are experiencing the same issue?

**Comment by radu-tutueanu** [comment]
Closing the issue due to inactivity. Please feel free to reopen if still experiencing issues.
