### ISSUE TITLE
Invalid credentials. Password too long?

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#140]
I tested to register a user with the following credentials:

```
username: tester@testing42.de
password: 24779C1D963A8729710E3549459F761D85D090F9361330F75CC3F20E425D51CEE0D52E9F3FC0D753864566AB1E5ADEA0F2E2D786892D6E09BCA16623DF8AF6E0
```
And the answer from the Server is:

`Registration failed realm: Error Domain=io.realm.sync Code=611 "The provided credentials are invalid or a user with these credentials already exists." UserInfo={statusCode=400, NSLocalizedDescription=The provided credentials are invalid or a user with these credentials already exists.}`

The user is not existing. So something else must be the problem. Is the provided password too big?

**Comment by istx25** [comment]
Hi @Montrazul. Considering you closed the issue, I'll assume that you resolved the issue. If you need help with anything else, just let us know! :)
