### ISSUE TITLE
An error occured while setting up your account

### ISSUE THREAD

**Issue by HebeTienCoder** [realm/realm-mobile-platform#144]
At the first time I register an account successfully.
then I unselect the admin arrow.
then I was kick-logouted.
and I cannot login again.
And when I use another email to register.
it give the error tip "An error occured while setting up your account".

**Comment by teotwaki** [comment]
Hi @HebeTienCoder,

We should probably prevent users from removing admin rights from themselves unless there's another admin user configured. I'll throw that in our feature-request pot.

This being said, I was able to create another admin user using another email address, and log-in subsequently:

![2017-03-01-114518_1161x120_scrot](https://cloud.githubusercontent.com/assets/1420434/23456657/9fba622e-fe74-11e6-8cc7-1e65e9c6680d.png)

**Comment by teotwaki** [comment]
I'm going to close this due to inactivity.
