### ISSUE TITLE
SQL Injection possible in Realm?

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#145]
Is SQL Injection possible in Realm?

Even if Realm does not use SQL the SQL Injection could be possible so im asking if there is a prevention for it or if it is just not simple. Would be great if you could explain how it is possible or it is not possibl.e

**Comment by teotwaki** [comment]
Hi @Montrazul,

This is not an RMP bug report or feature request, so I'm going to close it.

I'll ask others to weigh in.

**Comment by Montrazul** [comment]
Or just put it into your documentation? Documentation is everything!

**Comment by cmelchior** [comment]
Hi @Montrazul 

SQL Injection is only possible if you use placeholders in queries that can be replaced by user input, and you have a query language that allows you to execute multiple commands in one go.

```
// Example
SELECT * FROM Users WHERE UserId = ${id}

// User enters  "105; DROP TABLE Users;"
SELECT * FROM Users WHERE UserId = 105; DROP TABLE Users;
```

The query languages in both Java and .NET uses typed API's, which inherently prevents you from chaining commands.

```
// Java
String id = getId();
realm.where(Person.class).equalTo("id", id).findAll();
```

Cocoa and Javascript actually uses a String-based query language, but neither of these allows you execute multiple commands at once.

```
// Objective-C
let predicate = NSPredicate(format: "id = %@", getId())
tanDogs = realm.objects(Person.self).filter(predicate)
```

So the answer is "No, SQL injection is not possible with Realm"
