### ISSUE TITLE
Download Sync not triggering

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#147]
In my current app I always need a User Object. Without that User Object nothing would work. So if there is no User Object in the Realm, I create one:

```
func getCurrentUser() -> USER {
    if (self.user == nil) {
        let email = SecureManager.getSharedInstance().getLogged()!;

        self.user = self.realm.object(ofType: USER.self, forPrimaryKey: email);

        if (self.user == nil) {
            self.user = USER();
            self.user.email = email;

            try! self.realm.write {
                self.realm.add(self.user!);
            }
        }
    }

    return self.user;
}
```

So now after I successfully logged in I navigate to a "Sync View" where I do a progress syncing:

```
let session = user.session(for: HelperRealm.getRealmURL())!;

self.progressNotification = session.addProgressNotification(for: .download, mode: forCurrentlyOutstandingWork) { progress in
    DispatchQueue.main.async {
        if (!progress.fractionTransferred.isNaN) {
            self.progressBar.setProgress(Float(progress.fractionTransferred), animated: true);
            self.progressLabel.text = "\(Int((progress.fractionTransferred * 100))) %";
        }

        if (progress.isTransferComplete) {
            print("login progress complete");

            self.goToNextView();
        }
    }
}
```

The Problem here is: If the User already exists on the server side and the user just reinstalled the App or installed it on a new device he will never ever get his data because a user with the same primary key already exists on the client side. Realm seems not to be able to know that the data from the server is older and that it actually is the correct data which is needed.

I already tried to not use primary keys at all and use:

`self.user = self.realm.objects(USER.self).filter("email = '\(email)'").first;`

for the lookup but there is another problem. If I simply trigger the realm sync with the code posted above nothing ever would happen. There would be no data synced at all EVEN if the user already exists on the realm mobile platform. I always have to access a user object to trigger the sync. For that I have to create a default user object and that leads to duplicate users after the syncing is finished.

So how am I supposed to get the already existing user data from the server side realm mobile platform WITHOUT having to create a default user first? It is like the sync is just not triggering when I do it like posted above.

**Comment by simonask** [comment]
Thank you for your report. :-)

> Realm seems not to be able to know that the data from the server is older and that it actually is the correct data which is needed.

Realm Mobile Platform synchronizes field updates with a "last write wins" policy, so if the data on the device is indeed newer than what's on the server, it will "win". The exception to this rule is default values, which are always overwritten by explicit updates of property values.

Can you elaborate on how you set the data on the user object for the newly created user? Perhaps it is possible to use default values in the data model to ensure that the data coming from the server wins out. :-)

>  There would be no data synced at all EVEN if the user already exists on the realm mobile platform.

Outside of loss of connectivity, this should never happen, but I can tell you what I expect to be happening in the case without primary keys: You end up with two copies of the user in the database, and the one you created locally seems to never receive any data because the other object got it. Can you verify that this is what's happening using the Browser? If it isn't, it could indicate some other problem that we need to track down. :-)

Thanks!

**Comment by Montrazul** [comment]
The problem is indeed which I was pointing out in my opening post, that the progress notification token is never getting anything to download from the server. Lets go through the following scenario. Imagine you already have an existing user with data on the realm mobile platform. Now you got a new device with a fresh installation. You login into the app with the existing login data and now go to a view where you want to download already existing data:

```
import Foundation
import UIKit
import RealmSwift

class SyncViewController: UIViewController {
    @IBOutlet weak var progressLabel: UILabel!;
    @IBOutlet weak var progressBar: UIProgressView!;
	
    var notificationTokenProgress: NotificationToken!;
    var user: SyncUser!;
    
    static func storyboardInstance() -> SyncViewController? {
        let storyboard = UIStoryboard(name: String(describing: NSStringFromClass(SyncViewController.classForCoder()).components(separatedBy: ".").last!), bundle: nil);
        
        return storyboard.instantiateInitialViewController() as? SyncViewController;
    }
    
    override func viewDidLoad() {
        super.viewDidLoad();
        
        self.addNotificationBlock();
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        self.removeNotificationBlock();
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    func addNotificationBlock() {
        let email = SecureManager.getSharedInstance().getLogged();
        
        if (self.user != nil) {
            let session = self.user.session(for: HelperRealm.getRealmURL())!;
            
            logger.info("start notification for: \(email)");
            
            self.notificationTokenProgress = session.addProgressNotification(for: .download, mode: .forCurrentlyOutstandingWork) { progress in
                DispatchQueue.main.async {
                    logger.debug("sync progress");
                    logger.debug("fraction transferred \(progress.fractionTransferred)");
                    logger.debug("transferrable bytes \(progress.transferrableBytes)");
                    logger.debug("transferred bytes \(progress.transferredBytes)");
                    
                    if (!progress.fractionTransferred.isNaN) {
                        self.progressBar.setProgress(Float(progress.fractionTransferred), animated: true);
                        self.progressLabel.text = "\(Int((progress.fractionTransferred * 100))) %";
                    }
                    
                    if (progress.isTransferComplete) {
                        if (self.user != nil) {
                            logger.debug("login progress completed: \(self.user.identity!)");
                        
                            self.user = nil;
                        
                            self.goToNextView();
                        }
                    }
                }
            }
        }
    }
    
    func removeNotificationBlock() {
        self.notificationTokenProgress?.stop();
    }
    
    func goToNextView() {
        if let vc = NextView.storyboardInstance() {
            present(vc, animated: true, completion: nil);
        }
    }
}
```

So, remember, you already got an existing user with some data on the realm mobile platform. However, with the code posted above the output will be:

```
2017-03-13 12:31:59.846 [Info] [main] [SyncViewController.swift:90] addNotificationBlock() > start notification for: Optional("my.email@email.com")
2017-03-13 12:32:00.607 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:32:00.607 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 1.0
2017-03-13 12:32:00.607 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 0
2017-03-13 12:32:00.607 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 0
```

As you can see there are 0 transferred bytes and also 0 transferrable bytes. Now do a small change to your code (just for testing purposes):

```
import Foundation
import UIKit
import RealmSwift

class SyncViewController: UIViewController {
    @IBOutlet weak var progressLabel: UILabel!;
    @IBOutlet weak var progressBar: UIProgressView!;

    var notificationToken: NotificationToken!;
    var notificationTokenProgress: NotificationToken!;
    var user: SyncUser!;
    
    static func storyboardInstance() -> SyncViewController? {
        let storyboard = UIStoryboard(name: String(describing: NSStringFromClass(SyncViewController.classForCoder()).components(separatedBy: ".").last!), bundle: nil);
        
        return storyboard.instantiateInitialViewController() as? SyncViewController;
    }
    
    override func viewDidLoad() {
        super.viewDidLoad();
        
        self.triggerRealm();
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        self.removeNotificationBlock();
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    func triggerRealm() {
        logger.debug("trigger realm");
        
        self.notificationToken = REALM_Manager.getSharedInstance().getRealm().addNotificationBlock({ _ in
            self.addNotificationBlock();
        });
    }
    
    func addNotificationBlock() {
        let email = SecureManager.getSharedInstance().getLogged();
        
        if (self.user != nil) {
            let session = self.user.session(for: HelperRealm.getRealmURL())!;
            
            logger.info("start notification for: \(email)");
            
            self.notificationTokenProgress = session.addProgressNotification(for: .download, mode: .forCurrentlyOutstandingWork) { progress in
                DispatchQueue.main.async {
                    logger.debug("sync progress");
                    logger.debug("fraction transferred \(progress.fractionTransferred)");
                    logger.debug("transferrable bytes \(progress.transferrableBytes)");
                    logger.debug("transferred bytes \(progress.transferredBytes)");
                    
                    if (!progress.fractionTransferred.isNaN) {
                        self.progressBar.setProgress(Float(progress.fractionTransferred), animated: true);
                        self.progressLabel.text = "\(Int((progress.fractionTransferred * 100))) %";
                    }
                    
                    if (progress.isTransferComplete) {
                        if (self.user != nil) {
                            logger.debug("login progress completed: \(self.user.identity!)");
                        
                            self.user = nil;
                        
                            self.goToNextView();
                        }
                    }
                }
            }
        }
    }
    
    func removeNotificationBlock() {
        self.notificationToken?.stop();
        self.notificationTokenProgress?.stop();
    }
    
    func goToNextView() {
        if let vc = NextView.storyboardInstance() {
            present(vc, animated: true, completion: nil);
        }
    }
}
```

As you can see I added another notification token. This time directly on the realm, not on the session. If there is an incoming notification for that token the progress notification token is created. and this time the output is the following:

```
2017-03-13 12:31:59.846 [Info] [main] [SyncViewController.swift:90] addNotificationBlock() > start notification for: Optional("my.email@email.com")
2017-03-13 12:31:59.847 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:31:59.847 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 0.324374067905728
2017-03-13 12:31:59.847 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 3136083
2017-03-13 12:31:59.847 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 1017264
2017-03-13 12:32:00.403 [Info] [main] [SyncViewController.swift:90] addNotificationBlock() > start notification for: Optional("my.email@email.com")
2017-03-13 12:32:00.403 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:32:00.403 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 0.959876061953717
2017-03-13 12:32:00.403 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 3136083
2017-03-13 12:32:00.403 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 3010251
2017-03-13 12:32:00.404 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:32:00.404 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 0.959876061953717
2017-03-13 12:32:00.404 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 3136083
2017-03-13 12:32:00.404 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 3010251
2017-03-13 12:32:00.493 [Info] [main] [SyncViewController.swift:90] addNotificationBlock() > start notification for: Optional("my.email@email.com")
2017-03-13 12:32:00.494 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:32:00.494 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 0.982095180516587
2017-03-13 12:32:00.494 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 3136083
2017-03-13 12:32:00.494 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 3079932
2017-03-13 12:32:00.495 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:32:00.495 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 0.982095180516587
2017-03-13 12:32:00.495 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 3136083
2017-03-13 12:32:00.495 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 3079932
2017-03-13 12:32:00.496 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:32:00.496 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 0.982095180516587
2017-03-13 12:32:00.496 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 3136083
2017-03-13 12:32:00.496 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 3079932
2017-03-13 12:32:00.557 [Info] [main] [SyncViewController.swift:90] addNotificationBlock() > start notification for: Optional("my.email@email.com")
2017-03-13 12:32:00.558 [Debug] [main] [SyncViewController.swift:94] addNotificationBlock() > sync progress
2017-03-13 12:32:00.558 [Debug] [main] [SyncViewController.swift:95] addNotificationBlock() > fraction transferred 1.0
2017-03-13 12:32:00.558 [Debug] [main] [SyncViewController.swift:96] addNotificationBlock() > transferrable bytes 3136083
2017-03-13 12:32:00.558 [Debug] [main] [SyncViewController.swift:97] addNotificationBlock() > transferred bytes 3136083
2017-03-13 12:32:00.559 [Debug] [main] [SyncViewController.swift:106] addNotificationBlock() > login progress completed: 23d8d78b95258cf6d8212d4543a39424
```

So, that means that indeed the progress notification token is never getting any changes from the server side when you use it as we are supposed to use it.
The code here works if you already have an existing user and you login for the first time. Unfortunately it does ofcourse not work if you already logged in before or if it is a new user since you then will never get the notification to trigger the progress notification token.

So thats the core of the problem. The realm simply isnt downloading using the progress notification.

**Comment by simonask** [comment]
> But they are only duplicate on the realm mobile platform not on the local client.

How do you confirm this? Did you use the Browser to inspect the Realm file from the local client?

> BTW: I tried to use default values with the primary key approach. The default values are also overriding the already existing data.

This should never happen, unless the existing data is also default values. Can you share your schema and object creation routine? 

Thanks! :)

**Comment by simonask** [comment]
Just to explain what I'm trying to get at: I'm wondering if it is a problem with data synchronization or with update notifications. Those are two different subsystems, so it would be very helpful to try and narrow down where the problem lies. :)

**Comment by Montrazul** [comment]
I have server logoutput when there was no synchronization possible. The Scenario was the following:

1. Start App
2. Register
3. Login
4. Create some data
5. Delete App
6. Reinstall App
7. Login with Account created in step 2.

The Result was, that there was no syncing happening at all. The Logoutput for the sync request after step 7. is the following:

> sync-server: Connection[60]: Session[1]: Received: IDENT(server_file_ident=8429275042727112626, client_file_ident=11, client_file_ident_secret=2838689450431583288, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)

I dont know if this is correct but there is written that:

- scan_server_version=0
- scan_client_version=0
- last_server_version=0
- latest_server_session_ident=0

And always when the syncing isnt possible I also cant login as admin into realm object browser. This is very strange! After I try it a couple of times i can login into realm object browser again and after it the sync also is working again.

To your questions:

> How do you confirm this? Did you use the Browser to inspect the Realm file from the local client?

I use realm object browser to inspect realm mobile platform and I use logoutputs in my app to inspect the local client. Locally I never have duplicates. But on the serverside I have. 

> This should never happen, unless the existing data is also default values. Can you share your schema and object creation routine?

Ofcourse I can. I tried two different Approaches. Both leaded to the same result. First:

```
import Foundation
import ObjectMapper
import Realm
import RealmSwift

class USER : Object, Mappable {
    dynamic var firstname: String!;
    dynamic var lastname: String!;
    dynamic var dateOfBirth: NSDate!;
    let gender = RealmOptional<Int>();
    dynamic var email: String!;
    dynamic var phone: String!;
    dynamic var mobile: String!;
    dynamic var fax: String!;
    dynamic var address: ADDRESS!;
    
    required init() {
        super.init();

        self.firstname = "";
        self.lastname = "";
        self.dateOfBirth = nil;
        self.gender.value = -1;
        self.email = "";
        self.phone = "";
        self.mobile = "";
        self.fax = "";
        self.address = ADDRESS();
    }
    
    required init?(map: Map) {
        super.init(map: map);
    }
    
    required init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init(realm: realm, schema: schema);
    }
    
    required init(value: Any, schema: RLMSchema) {
        super.init(value: value, schema: schema);
    }
    
    func mapping(map: Map) {
        self.firstname <- map["firstname"];
        self.lastname <- map["lastname"];
        self.dateOfBirth <- (map["dateOfBirth"], TransformOf<NSDate, NSNumber>(fromJSON: { $0 == nil ? nil : NSDate(timeIntervalSince1970: Double(($0?.int64Value)! / 1000)) }, toJSON: { $0.map { NSNumber(value: Int64($0.timeIntervalSince1970 * 1000)) } }));
        self.gender.value <- map["gender"];
        self.email <- map["email"];
        self.phone <- map["phone"];
        self.mobile <- map["mobile"];
        self.fax <- map["fax"];
        self.address <- map["address"];
    }
}
```

Second:

```
import Foundation
import ObjectMapper
import Realm
import RealmSwift

class USER : Object, Mappable {
    dynamic var firstname: String! = "";
    dynamic var lastname: String! = "";
    dynamic var dateOfBirth: NSDate! = nil;
    let gender = RealmOptional<Int>(-1);
    dynamic var email: String! = "";
    dynamic var phone: String! = "";
    dynamic var mobile: String! = "";
    dynamic var fax: String! = "";
    dynamic var address: ADDRESS! = ADDRESS();
    
    required init() {
        super.init();
    }
    
    required init?(map: Map) {
        super.init(map: map);
    }
    
    required init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init(realm: realm, schema: schema);
    }
    
    required init(value: Any, schema: RLMSchema) {
        super.init(value: value, schema: schema);
    }
    
    func mapping(map: Map) {
        self.firstname <- map["firstname"];
        self.lastname <- map["lastname"];
        self.dateOfBirth <- (map["dateOfBirth"], TransformOf<NSDate, NSNumber>(fromJSON: { $0 == nil ? nil : NSDate(timeIntervalSince1970: Double(($0?.int64Value)! / 1000)) }, toJSON: { $0.map { NSNumber(value: Int64($0.timeIntervalSince1970 * 1000)) } }));
        self.gender.value <- map["gender"];
        self.email <- map["email"];
        self.phone <- map["phone"];
        self.mobile <- map["mobile"];
        self.fax <- map["fax"];
        self.address <- map["address"];
    }
}

```

This is how I create my objects:

```
func getCurrentUser() -> USER {
    if (self.user == nil) {
        logger.debug("current user is nil");
            
        let email = SecureManager.getSharedInstance().getLogged()!;
    
        try! REALM_Manager.getSharedInstance().getRealm().write {
            logger.debug("open realm write transaction");
            
            self.user = REALM_Manager.getSharedInstance().getRealm().objects(USER.self).filter("email = '\(email)'").first;

            if (self.user == nil) {
                logger.debug("user is not existing in realm: \(email)");
                        
                self.user = USER();
                self.user?.email = email;
                     
                logger.info("add new user to realm: \(email)");
                        
                REALM_Manager.getSharedInstance().getRealm().add(self.user!);
            }
        }
    }
        
    return self.user!;
}
```

As you can see I am not anymore using the primary key approach since deleting duplicates for is much better than letting realm handle the merging with "newest wins". To delete duplicates I use the following:

```
func deleteUserssDuplicate() {
    logger.debug("delete users duplicate");
        
    let users = REALM_Manager.getSharedInstance().getRealm().objects(USER.self);
    let usersEmails = NSCountedSet(array: users.map { $0.email });
        
    guard usersEmails.count > 1 else {
        logger.debug("there are no user duplicates to delete");
            
        return;
    }
        
    for email in usersEmails where usersEmails.count(for: email) > 1 {
        logger.debug("duplicate: \(email)");
            
        let email = email as! String;
        let indexesToRemove = users.enumerated().flatMap { index, element in
            return element.email == email ? index : nil;
        }
            
        for index in indexesToRemove {
            let user = users[index];
                
            logger.debug("duplicate deletion for: \(user.email)");
                
            for customer in user.customers {
                self.removeCustomer(user, customer);
                    
                VKB_CUSTOMER_Manager.getSharedInstance().removeCustomer(customer);
            }
                
            try! REALM_Manager.getSharedInstance().getRealm().write {
                REALM_Manager.getSharedInstance().getRealm().delete(user.address);
                REALM_Manager.getSharedInstance().getRealm().delete(user);
            }
        }
    }
}
```

This function is currently always returning after the check, if there are duplicates:

> there are no user duplicates to delete

And I have no idea why. It behaves like there is always a completely new local realm file. but on the server side I can see all those duplicates using the realm object browser. So the current state is now:

Always when I login into my app after app restart or app reinstallation the login works perfectly but there is always a new user object created and uploaded to the realm mobile platform. Older user objects are never existing locally and there is never a sync triggered. Only sometimes when im lucky I will get the originally created user object from the realm mobile platform after restarting or reinstalling.

For code completion I'll also post how I login into realm:

```
func loginRealm(json: String, email: String, password: String) {
    let userIS = USER_IS(JSONString: json);
    let credentials = SyncCredentials.usernamePassword(username: (userIS?.realmMail)!, password: (userIS?.realmPassword)!, register: false);
    let server = URL(string: HelperUrls.URL_SERVER)!;
        
    SyncUser.logIn(with: credentials, server: server) { user, error in
        DispatchQueue.main.async {
            if let user = user {
                logger.verbose("Login success: \(user.identity!)");
                    
                SecureManager.getSharedInstance().login(email: email);
                    
                self.setDefaultRealmConfiguration(user: user);
                    
                if (SecureManager.getSharedInstance().hasData(email: email)) {
                    SecureManager.getSharedInstance().setIdentity(email: email, identity: user.identity!);
                    SecureManager.getSharedInstance().setPassword(email: email, password: password);
                } else {
                    SecureManager.getSharedInstance().setData(email: email, user: SecureUser(identity: user.identity!, password: password));
                }

                REALM_Manager.getSharedInstance().getRealm().refresh();
				
				self.openSyncViewController();
            } else if let error = error {
                logger.debug("Login failed: \(error)");
                    
                self.alert(message: "Login failed.");
            }
        }
    }
}

private func setDefaultRealmConfiguration(user: SyncUser) {
    let configuration = Realm.Configuration(
        syncConfiguration: SyncConfiguration(user: user, realmURL: HelperRealm.getRealmURL()),
        schemaVersion: 3);
        
    Realm.Configuration.defaultConfiguration = configuration;
}

class HelperRealm {
    static func getRealmURL() -> URL {
        let server = HelperUrls.URL_REALM;
        let version = 1;
        
        return URL(string: "\(server)/\(version)")!;
    }
}
```

**Comment by simonask** [comment]
Thank you, that's very helpful. :-)

Can you try to reproduce this with debug logging enabled in the server?

**Comment by Montrazul** [comment]
I did that but the logoutput now is really huge. Do you need the full output?

**Comment by simonask** [comment]
Alright, it seems there are two issues here:

For the default values overwriting "real" data, the solution is to initialize the User object with `initWithValues:` passing an empty dictionary. The reason is that at present, we have no way to distinguish between default values set by the Swift runtime and values that you explicitly set on the object when we first persist the object in the Realm database. This is an unfortunate shortcoming that we need to document. For now, you should be able to work around it like that.

Note that manually deleting duplicates is quite brittle, as two devices may end up disagreeing about which object to delete, resulting in both objects ending up deleted. :-)

For the other issue, it is expected that `scan_server_version` (and other fields) are zero on a fresh install of the app, but it certainly is not expected that a restart is required for synchronization to commence. It would be extremely helpful if you are able to get a debug log in this situation. Are you setting any permissions for users on the server?

**Comment by Montrazul** [comment]
> Note that manually deleting duplicates is quite brittle, as two devices may end up disagreeing about which object to delete, resulting in both objects ending up deleted. :-)

But the example `RealmTasks` provided exactly that way of deleting duplicates since in that example project you (as realm developer team) faced the same problem with duplicate tasklists.

> Are you setting any permissions for users on the server?

No. Im not setting any permissions.

For the debug logs: Im leaving an eye on it. But for some reasons at the moment all sync processes are working as they should.

**Comment by simonask** [comment]
> But the example RealmTasks provided exactly that way of deleting duplicates since in that example project you (as realm developer team) faced the same problem with duplicate tasklists.

Yes. That doesn't change the fact that it is brittle. The `RealmTasks` example app was developed at a time when we had not yet implemented proper support for synchronizing primary keys, and we would rather not change the schema right now. It may happen in the future, though. It isn't a problem when all devices are online, but for a production app it should definitely be avoided.

> For the debug logs: Im leaving an eye on it. But for some reasons at the moment all sync processes are working as they should.

Glad to hear it! :-)

**Comment by Montrazul** [comment]
Hi. You mentioned that the default value solution is to use `initWithValues`. Can you post an example or an API reference? I cant find the `initWithValues` method. And also do I still have to use the standard `init()` method or not`?

**Comment by simonask** [comment]
Ah sorry, I was using the Objective-C name. In Swift, it's just `init(value:)`. Here is the API documentation for the method: https://realm.io/docs/swift/2.4.4/api/Classes/Object.html#/s:FC10RealmSwift6ObjectcFT5valueP__S0_

You do not have to call `init()` separately when you have called `init(value:)`. :-)

**Comment by Montrazul** [comment]
So you mean to change to the following:

```
import Foundation
import ObjectMapper
import Realm
import RealmSwift

class USER : Object, Mappable {
    dynamic var firstname: String! = "";
    dynamic var lastname: String! = "";
    dynamic var dateOfBirth: NSDate! = nil;
    let gender = RealmOptional<Int>(-1);
    dynamic var email: String! = "";
    dynamic var phone: String! = "";
    dynamic var mobile: String! = "";
    dynamic var fax: String! = "";
    dynamic var address: ADDRESS! = ADDRESS();
    
    required init() {
        super.init();
    }
    
    required init?(map: Map) {
        super.init(map: map);
    }
    
    required init(realm: RLMRealm, schema: RLMObjectSchema) {
        super.init(realm: realm, schema: schema);
    }
    
    required init(value: Any, schema: RLMSchema) {
        super.init(value: value, schema: schema);
    }

    override class func parimaryKey() -> String? {
        return "email";
    }
    
    func mapping(map: Map) {
        self.firstname <- map["firstname"];
        self.lastname <- map["lastname"];
        self.dateOfBirth <- (map["dateOfBirth"], TransformOf<NSDate, NSNumber>(fromJSON: { $0 == nil ? nil : NSDate(timeIntervalSince1970: Double(($0?.int64Value)! / 1000)) }, toJSON: { $0.map { NSNumber(value: Int64($0.timeIntervalSince1970 * 1000)) } }));
        self.gender.value <- map["gender"];
        self.email <- map["email"];
        self.phone <- map["phone"];
        self.mobile <- map["mobile"];
        self.fax <- map["fax"];
        self.address <- map["address"];
    }
}
```

and:

```
func getCurrentUser() -> USER {
    if (self.user == nil) {
        let email = SecureManager.getSharedInstance().getLogged()!;

        self.user = self.realm.object(ofType: USER.self, forPrimaryKey: email);

        if (self.user == nil) {
            self.user = USER(value: []); // value with empty dictionary
            self.user.email = email;

            try! self.realm.write {
                self.realm.add(self.user!);
            }
        }
    }

    return self.user;
}
```

**Comment by simonask** [comment]
Yes, except that the empty dictionary in Swift is written as `[:]`, and that you have misspelled your `primaryKey()` method as `parimaryKey()`. :-)

**Comment by Montrazul** [comment]
Ok I just wanted to be sure to use the correct init method. Because it isnt working:

> Incorrect argument label in call (have 'value:', expected 'map:')

**Comment by simonask** [comment]
Yes, your code is overriding single-argument `init` as `init(map:)`. There shouldn't be any reason to override `init` at all in this case.

**Comment by Montrazul** [comment]
But it is required. My `USER` is inherting from `Object` and from `Mappable` (JSON convertion) and all those init methods are required. Ill just use the map init to call the `init(value:)` then.

**Comment by Montrazul** [comment]
Oh... but even if I kick out the `Mappable` it still isnt possible to use `USER(value: [:])`:

> Cannot invoke initializer of type 'USER' with an argument list of type '(value: [AnyHashable : Any])'

**Comment by stel** [comment]
@Montrazul I would suggest you to use [`StaticMappable`](https://github.com/Hearst-DD/ObjectMapper#staticmappable-protocol) protocol instead. You can even implement it in a class extension and there is no need to override all the initializers. 

So it could look like this:

```Swift
import Foundation
import ObjectMapper
import Realm

class USER: Object {

    // All your properties here

}

extension USER: StaticMappable {

    static func objectForMapping(map: Map) -> BaseMappable? {
        return User()
    }

    func mapping(map: Map) {
        // Your mapping here
    }

}
```

**Comment by Montrazul** [comment]
For testing purposes I now did the following:

import Foundation
import Realm
import RealmSwift

```
class USER : Object {
    dynamic var firstname: String! = "";
    dynamic var lastname: String! = "";
    dynamic var dateOfBirth: NSDate! = nil;
    let gender = RealmOptional<Int>(-1);
    dynamic var email: String! = "";
    dynamic var phone: String! = "";
    dynamic var mobile: String! = "";
    dynamic var fax: String! = "";
    dynamic var address: ADDRESS! = ADDRESS();
}
```

and the following object creation method:

```
func getCurrentUser() -> USER {
    if (self.user == nil) {
        let email = SecureManager.getSharedInstance().getLogged()!;

        self.user = self.realm.object(ofType: USER.self, forPrimaryKey: email);

        if (self.user == nil) {
            self.user = USER(value: [:]); // value with empty dictionary
            self.user.email = email;

            try! self.realm.write {
                self.realm.add(self.user!);
            }
        }
    }

    return self.user;
}
```

But now im again at the point where all my old values are getting overwritten. What I did:

1. I registered a new User to realm
2. I logged into my app and created some data to override the default user data
3. I deleted the App from my device
4. I reinstalled the App
5. I logged into my app

The positive thing is: I have no duplicate users which i have to delete. The negative thing is:

All my values again got overwritten with default values. So when my `USER` object before the reinstallation had:

```
firstname: "Bob"
lastname: "Smith"
dateOfBirth: nil
gender: 1
email: "bobsEmail@Smith.de"
phone: ""
mobile: ""
fax: ""
address: ADDRESS()
```

He after reinstallation of the app again has:

```
firstname: ""
lastname: ""
dateOfBirth: nil
gender: -1
email: "bobsEmail@Smith.de"
phone: ""
mobile: ""
fax: ""
address: ADDRESS()
```

So when the merging happens the default values are overriding the old values.

**Comment by Montrazul** [comment]
Just noticed there is a new realm database version (2.4.4). The problem is fixed. The progress now is fireing correctly. Even the first initial download is working! great!

**Comment by simonask** [comment]
@Montrazul Sounds great! Glad to hear your problems have been fixed. Thanks cooperating with us to resolve this. :-)
