### ISSUE TITLE
How can I contribute to the Realm Object Server codebase?

### ISSUE THREAD

**Issue by neokree** [realm/realm-mobile-platform#148]
Hi to all the Realm team.
I have searched for the realm object server sources because I want to contribute to the project. 
However I cannot find any github repo for that. 
It is closed source at this time or I'm missing something? 

Thank you for your time

**Comment by bmunkholm** [comment]
Hi @neokree :-)
What's up?

**Comment by neokree** [comment]
Sorry I typed cmd + enter for mistake when I was writing the issue, I have edited it.

**Comment by bmunkholm** [comment]
@neokree Awesome of you to want to contribute - we appreciate that!
Unfortunately it is closed source at the moment and the foreseeable future. Only the core database is open sourced for now. But perhaps it's the specific sync parts you are interested in? Let me know in which way you want to help the project. There could be other ways to help advance the development. It could be in testing and replicating issues for instance - if not core or SDK work.

**Comment by neokree** [comment]
Yes I'm interested in the permission and "partial sync" feature from [#22](https://github.com/realm/realm-mobile-platform/issues/22). 
Because Realm Object Server could be perfect for my project use case, but without these two features I cannot use it without have a serious security and big data syncing problems (for instance, use a global realm sync between all users). I'm sure that you have a lot work to do, so implement these features by myself was the fastest way I thought. 
Anyway I will continue to stay updated with your releases. 
Thank you for your support!

**Comment by omidraha** [comment]
Hi,
Is there any source code for syncing process section, or technical post about how syncing  is done?
Currently i use realm on the client side,
But, for some reason i can't use object server on the server side, 
So i want to implement simple small application for sync data between client and server on the server side. (and also one background task on the client side)
Actually i just want to know what is standard algorithm on this section: 
How server can track/keep difference/detect new and dirty records (also some new records generate on the server side for user) for each of multiple devices of one user from the client side on the server?
Thanks.
