### ISSUE TITLE
SyncPermissionOffer does not generate a token after resetting Realm Object Server

### ISSUE THREAD

**Issue by Taco55** [realm/realm-mobile-platform#156]
A problem occurs with generating a token using `SyncPermissionOffer` after resetting the MacOS Realm Object Server.

When a fresh install of the Realm Object Server is used, a token is successfully generated after a `SyncPermissionOffer` is added to the user's management Realm. However, after resetting ROS, no tokens are generated anymore. More specifically, after adding a `addNotificationBlock` to a SyncPermissionOffer collection, only an `.initial` change is observed while an `.update` (with an expected token) does not occur.
The only way to avoid this problem seems to re-install the server every time an empty database is required. Since I prefer to refresh the database several times during development this is not ideal. 

## Steps to Reproduce

1. Setup server (create admin account)
2. Create a user and add a `SyncPermissionOffer` to the user's management Realm
3. Reset ROS
3. Setup server, create user again 
4. This time adding a `SyncPermissionOffer` to the user's management Realm does not result in a generated token

## Code Sample

I created a sample application for another issue with SyncPermissionOffer and Response, which can be found [here](https://github.com/Taco55/RealmPermissionChangeDemo). When this app is started for the first time a token is generated. After resetting ROS and running the app again does not result in generation of a token.

## Version of Realm and Tooling

- Realm Object Server Version: 1.2.1
- Flavor: Developer
- Server OS & Version: MacOS

- Client SDK Version: 2.4.4
- Client OS & Version: MacOs 10.12.3

**Comment by istx25** [comment]
Hi @Taco55. Thanks for providing all of the information that you did. We'll have someone look into this and follow-up soon with more information/if a fix from our side is necessary. Cheers!

**Comment by radu-tutueanu** [comment]
Hello, @Taco55 .
Could you please describe how you reset the ROS?

Thanks!

**Comment by Taco55** [comment]
I encounter this bug when I quit an active ROS instance and use the `reset-server-realms` script. I just tested it also with ROS version 1.3.0, but the problem still exists.

**Comment by radu-tutueanu** [comment]
You are right, we do have a bug in the reset script.
Until a release with the fix is out, you can use the reset script in the archive attached. You will have to replace yours in the realm-object-server folder.

Please let me know if that solves your issue.

[reset-server-realms.command.zip](https://github.com/realm/realm-mobile-platform/files/878530/reset-server-realms.command.zip)

**Comment by Taco55** [comment]
Yes, this fixes the issue. Thanks for providing!
