### ISSUE TITLE
NodeJS version

### ISSUE THREAD

**Issue by gemiren** [realm/realm-mobile-platform#168]
The ROS 1.4.1 changelog has this change "Use node 6.10.1 when running ROS". However, the document on the website still says "Currently, the Realm Object Server requires NodeJS 4.x and only version 4.x to be installed on Linux". So which version of NodeJS should we use for ROS 1.4.1?  Thanks.

**Comment by radu-tutueanu** [comment]
Hello, @gemiren ! Thank you for logging this.  You are right, the docs need to be updated.

Right now the ROS comes with it's own bundled node - so there is no restriction on the system NodeJS version.

**Comment by radu-tutueanu** [comment]
Updated the docs. Thanks!
