### ISSUE TITLE
RealmBrowser: Should allow user realm access after a admin token login

### ISSUE THREAD

**Issue by bmsantos** [realm/realm-mobile-platform#169]
## Goals

```gherkin
Feature: Access realm object from Realm Browser
  Scenario: Should allow admin user access to a realm previously accessed within an auth token login
    Given a realm
    And a ObjectServer auth token
    And a auth token login to the realm has occurred
    When the admin user logins to the realm
    Then the realm objects will be displayed
```

## Expected Results

As an admin user, I always want to be able to browse the realm objects after a username/password login.

## Actual Results

Realm Browser crashes and fails to display realm objects if that realm has previously been accessed through an auth token login

## Steps to Reproduce

1. Login using user admin account and verify access to realm
1. Logout and login again this time using the auth token and verify access to same realm
1. Logout and login again using admin account and user will no longer be able to access a realm that was accessed using the auth token

## Code Sample

N/A

## Version of Realm and Tooling

- Realm Mobile Platform Professional 1.3.0-1
- Server OS & Version: OSX 10.12.4
- Client SDK Version: Realm Browser 2.1.7 (91)
- Client OS & Version: OSX 10.12.4

**Comment by stel** [comment]
Thanks for reporting this issue @bmsantos! I was able to reproduce it, to me it seems like it's related to https://github.com/realm/realm-browser-osx/issues/297. Will try to investigate and fix it.

**Comment by stel** [comment]
I believe this issue has been fixed in https://github.com/realm/realm-browser-osx/pull/317.
