### ISSUE TITLE
Change password API at /auth/password endpoint?

### ISSUE THREAD

**Issue by RiverbayChris** [realm/realm-mobile-platform#173]
## Goals

Change User Password

## Expected Results

According to 1.4.1 release notes, there's this: 

Adds change password API at /auth/password endpoint.

## Actual Results

I can't find this endpoint, or a reference to it anywhere.  How do you use this?

## Steps to Reproduce

Read release notes.  Look for new api.  🤷🏻‍♂️

## Code Sample

N/A

## Version of Realm and Tooling

- Realm Object Server Version: 1.4.1
- Flavor: Developer

## Logs

N/A

**Comment by istx25** [comment]
Hi @RiverbayChris. Wanted to let you know that we've received your issue and that someone will review and follow-up with an answer soon. Thanks!

**Comment by teotwaki** [comment]
Hi @RiverbayChris,

This API is internal to ROS, and is targetted to be used by the clients (bindings) to provide client-side password change. I don't believe any of the bindings have shipped support for this new API, though.
