### ISSUE TITLE
setupRealm()  connect to server once 

### ISSUE THREAD

**Issue by RawanA** [realm/realm-mobile-platform#181]
I'm using this code in my project 

```
var realm : Realm!

func setupRealm() {
    let username = "myUsername"
    let password = "myPassword"

    SyncUser.logIn(with: .usernamePassword(username: username, password: password, register: false), server: URL(string: "http://myIP:9080/")!) { user, error in
        
    guard let user = user else {

    fatalError(String(describing: error))
    }

    DispatchQueue.main.async {
  
    // Open Realm
    let configuration = Realm.Configuration(
    syncConfiguration: SyncConfiguration(user: user, realmURL: URL(string: "realm://myIP:9080/fe533bbd57b525833ed3618a28abb009")!)
    )
   
    self.realm = try! Realm(configuration: configuration)

    }
        }
    }
```

is there any way to write this function only once, and make it return realm value so it could be used in other classes later ? 

thank you in advanced 

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by stel** [comment]
If I got your questions correctly, you can just return newly created realm from `setupRealm()` function instead defining it globally. Please keep in mind that `SyncUser.logIn()` is an asynchronous function and it means that you should probably return a realm instance in some completion block.

```swift
func setupRealm(completion: (realm: Realm?, error: Error?) -> Void) {
    let username = "myUsername"
    let password = "myPassword"

    SyncUser.logIn(with: .usernamePassword(username: username, password: password, register: false), server: URL(string: "http://myIP:9080/")!) { user, error in 
        guard let user = user else {
            completion(nil, error)
            return
        }

        DispatchQueue.main.async {
            // Open Realm
            let configuration = Realm.Configuration(syncConfiguration: SyncConfiguration(user: user, realmURL: URL(string: "realm://myIP:9080/fe533bbd57b525833ed3618a28abb009")!))
            completion(try? Realm(configuration: configuration), nil)
        }
    }
}
```

Also note that you can use `SyncUser.current` to retrieve the last user who logged in and whose credentials have not expired. Learn more in docs at https://realm.io/docs/swift/latest/#working-with-users.

**Comment by RawanA** [comment]
@stel thank you for your help 
it works ^_^
