### ISSUE TITLE
iOS Tutorial - ToDoList App Bugs

### ISSUE THREAD

**Issue by ronhippler** [realm/realm-mobile-platform#182]
- TaskList is never used
- no items are visible without an existing list on server (no TaskList is added to server)

**Comment by radu-tutueanu** [comment]
Thanks, @ronhippler . I have opened 2 issues in our RealmTasks repo : https://github.com/realm-demos/realm-tasks/issues/413 https://github.com/realm-demos/realm-tasks/issues/414

**Comment by jpsim** [comment]
These problems shouldn't occur if the tutorial is followed step by step.
