### ISSUE TITLE
Realm: How to get the properties of a realted object inside a custom Row componant when using Realm ListView

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-mobile-platform#186]
I posted this question to [StackOverflow](http://stackoverflow.com/questions/44013746/realm-how-to-get-the-properties-of-a-realted-object-inside-a-custom-row-compona), but the Realm tag does not appear to have a lot of answers on questions. 

I have two Realm schemas defined. A student can have a list of parents.

```
const StudentSchema = {
      name: "Student",
      primaryKey: "id",
      properties: {
        id: "string", // primary key
        bb_first_name: "string",
        bb_last_name: "string",
        bb_current_grade: "string",
        bb_class_of: "string",
        DirectoryentryDisplay: "string",
        parents: {type: 'list', objectType: 'Parent'},
      }
    };

    const ParentsSchema = {
      name: "Parent",
      primaryKey: "id",
      properties: {
        id: "string", // primary key
        bb_first_name: "string",
        bb_last_name: "string",
        student_id: "string",
      }
    };
```

Inside of a custom componant for a Realm ListView row I am passing a Realm ListView DataSource which is a result set of a students, they end up in the row as a props:

```
<Text style={styles.text}>
            {`${this.props.bb_first_name} ${this.props.bb_last_name}`}
            {this.props.parents}
          </Text>
```

I am able to access properites of the student such as this.props.bb_first_name with no problems. However, I have tried everythig I can think of to access the parent data such as:

`{this.props.parents[0].bb_first_name} `

and it always comes back as undefined. However, this.props.parents.length returns a number and this.props.parents logs as "Object". So I know I have data in there. In fact when I create the Realm I check to make sure students have parent data:

```
this.realm.write(() => {
      //for (let i = 0; i < data.length - 1; ++i) {
      for (let i = 0; i < data.length; ++i) {
        let parents = this.realm.objects("Parent").filtered('student_id = "' + data[i].kp_ID + '"');
        this.realm.create(
          "Student",
          {
            id: data[i].kp_ID,
            bb_first_name: data[i].bb_first_name,
            bb_last_name: data[i].bb_last_name,
            bb_current_grade: data[i].bb_current_grade,
            bb_class_of: data[i].bb_class_of,
            DirectoryentryDisplay: data[i].DirectoryentryDisplay,
            parents: parents
          },
          true
        );
      }
    });
    let parents = this.realm.objects("Student")[0].parents
    console.log(parents[0].bb_first_name);
```

The final console.log does in fact print a prent's first name.

I am really stuck on this and I am unable to proceed with my app until I can access related record data in my components. Any help is greatly appreciated.

**Comment by blagoev** [comment]
Maybe you should try to see what object is this.props.parents and dump all its members. Also you can try using slice method if it is available to convert it to Javascript array like : this.props.parents.slice()

**Comment by agersoncgps** [comment]
Its a Realm JS Proxy object. I was able to convert it to an array:

let parents = Array.from(this.props.parents);
let parentOne = parents[0]
let parentOneFirstName = parentOne.bb_first_name

parentOneFirstName is a RealmObject. I get the error Cannot read property 'bb_first_name' of undefined but when I inspect parentOne it has a bb_first_name property.

**Comment by blagoev** [comment]
We will need to take a closer look into that. Could you share your project or a sample one if not possible that reproduces this, so we can debug it.

**Comment by agersoncgps** [comment]
I bleive I figured it out. Thank you for looking into it. The List was looping over the data source wich was missing one "parent" and produced the error. Thanks for your help.

**Comment by blagoev** [comment]
glad its working. closing it
