### ISSUE TITLE
Can not start ROS

### ISSUE THREAD

**Issue by gemiren** [realm/realm-mobile-platform#188]
## Goals
Run ROS.

## Expected Results
Run ROS.

## Actual Results
ROS fails to start.

## Steps to Reproduce

This is a fresh install of RPM 1.5.0 in a new Droplet. ROS can run using the command `service realm-object-server start` with all default configuration. However, if I change the root_path in the configuration.yml it fails to run.

Here are the steps to reproduce.
1. Change root_path in /etc/realm/configuration.yml and save. The root_path used is shown below.
```
storage:
  ## The directory in which the realm server will store all its data files.
  ## This configuration option is MANDATORY.
  root_path: /mnt/data/realm/object-server
```

2. Run the command `service realm-object-server start`. 

The ROS fails to run with error:
```
realm-object-server[22254]: Error: EACCES: permission denied, access '/mnt/data/realm/object-server'
realm-object-server[22254]:     at Error (native)
realm-object-server[22254]:     at Object.fs.accessSync (fs.js:249:11)
realm-object-server[22254]:     at validateFileAccessPermissions (/usr/lib/nodejs/realm-object-server/.build/src/node/configuration.js:322:6)
realm-object-server[22254]:     at validateConfig (/usr/lib/nodejs/realm-object-server/.build/src/node/configuration.js:341:3)
realm-object-server[22254]:     at Object.loadConfig (/usr/lib/nodejs/realm-object-server/.build/src/node/configuration.js:374:3)
realm-object-server[22254]:     at loadConfigurationFromArguments (/usr/lib/nodejs/realm-object-server/.build/src/node/cli-interface.js:17:24)
realm-object-server[22254]:     at Object.handleCLIArguments (/usr/lib/nodejs/realm-object-server/.build/src/node/cli-interface.js:106:16)
realm-object-server[22254]:     at Object.<anonymous> (/usr/lib/nodejs/realm-object-server/.build/src/node/bootstrap.js:29:25)
realm-object-server[22254]:     at Module._compile (module.js:570:32)
realm-object-server[22254]:     at Object.Module._extensions..js (module.js:579:10)
systemd[1]: realm-object-server.service: Main process exited, code=exited, status=99/n/a
systemd[1]: realm-object-server.service: Unit entered failed state.
systemd[1]: realm-object-server.service: Failed with result 'exit-code'.
systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
```

The server is installed and started as root account. So it has the permission to read/write the root path.

What's interesting is that if I run with this command `realm-object-server --configuration /etc/realm/configuration.yml`, ROS can run but `service realm-object-server status` doesn't report the ROS status.

## Version of Realm and Tooling

- Realm Object Server Version: 1.5.0
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? Ubuntu 16.04
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by radu-tutueanu** [comment]
Hello, @gemiren !

The ROS service is run by the `realm` user - if you change the root_path the user has to be able to access it.
In your case, you can do that by running `sudo chown -R realm:realm /mnt/data/realm/object-server`

When you start the binary from the commad line `realm-object-server --configuration /etc/realm/configuration.yml`, it can run because you start it with the current user, which probably has access to the path. However, it is not started as a service and `service realm-object-server status` won't pick it up.

Let me know if that solves it for you!

**Comment by gemiren** [comment]
Works great after change the owner of the directory. Maybe you can add that to the document https://realm.io/docs/realm-object-server/#configuring-the-server so others can find the information easily. Thanks!

**Comment by radu-tutueanu** [comment]
Will do that, thank you!
