### ISSUE TITLE
Notification for new beta releases

### ISSUE THREAD

**Issue by DiogoAndre** [realm/realm-mobile-platform#19]
Hi!  Is there a way to get notified when new beta releases are out? I just saw that 2.1 was out and I'm still running 1.0 😢 

Maybe a symbolical release tag on this repository?

Thanks!!

**Comment by teotwaki** [comment]
Hi,

That's actually a pretty great idea. We initially thought of sending an email to everyone who had registered, though I fear that might be slightly spammy.

I'll see with the team if we can set something like that up (the tag)

**Comment by DiogoAndre** [comment]
Guess this can be closed now that new releases are being notified as release tags on this repo. Thanks!
