### ISSUE TITLE
How to disable ROS setup

### ISSUE THREAD

**Issue by gemiren** [realm/realm-mobile-platform#191]
## Goals

Disable the accessing to ROS setup by visiting the IP http://OBJECT_SERVER_IP:9080/#!/setup or at least it should require admin permissions.

## Expected Results
After the initial setup, following accessing to http://OBJECT_SERVER_IP:9080/#!/setup is either disabled or requires admin permission.

## Actual Results

Anyone can open a web browser and go to http://OBJECT_SERVER_IP:9080/#!/setup to set up a new admin account.

## Version of Realm and Tooling

- Realm Object Server Version: 1.5.0
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6) Ubuntu 16.04
- Client SDK Version: ?
- Client OS & Version: ?

**Comment by mrackwitz** [comment]
What you describe appears to be an error. I can confirm that it was possible to get to see the form for setting up the initial user by visiting the link as you describe, but it should never have been possible to actually create an admin account that way. That being said we released version 1.7.0 today which addresses the former issue as well.
