### ISSUE TITLE
Disable Cert Validation for SyncUser.logIn()

### ISSUE THREAD

**Issue by RiverbayChris** [realm/realm-mobile-platform#192]
## Goals

For local Mac dev and testing reasons, disable certificate validation for self-signed certs for the call to SyncUser.login()

## Expected Results

Bypass of cert validation for the login call against an https URL.

## Actual Results

"Login failed with error: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “127.0.0.1” which could put your confidential information at risk."

At one point, it looks like there was a bypass using SyncManager, but it has been deprecated.  Setting it doesn't do anything for the login.

Dashboard works fine if you accept the user warning, as expected.

## Steps to Reproduce

Create a self-signed cert (openssl or whatever).  

## Code Sample

N/A

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [X] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? macOS version
- Client SDK Version: ? 2.7
- Client OS & Version: ? Mac

**Comment by austinzheng** [comment]
Thanks for getting in touch with us. We have a new `enableSSLValidation` property on the `RLMSyncConfiguration` type that defaults to true, but can be set to false if you want. Can you try that and see if that helps?

**Comment by RiverbayChris** [comment]
I was under the assumption that this new property was for the realm’s config, but I’m referring to the step before opening the realm file (the call to SyncUser.login).  There is no property that I see that would control SSL at that step.  I want to refer to the server with https:// for the authentication, but I want to use self-signed certs when testing locally on my laptop.  This is mostly due to Apple’s TLS requirement.  I do not want to mark my ROS server as exempt in the info.plist, because then I need to change it before I build and push to App Store… which I will always forget.

**Comment by austinzheng** [comment]
We don't have an option to bypass certificate validation at the HTTP level (e.g. when connecting to the authentication server), but will consider adding it to our feature backlog.
