### ISSUE TITLE
Unable to VIEW dashboard output

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [realm/realm-mobile-platform#198]
Ubuntu 16.04
ROS v1.7.1 / Developer

Viewing the Dashboard results in a blank screen.  The Dashboard displays the text "Loading" for approximately 2 seconds.  Then central area, where I would expect to see the dashboard, is blank.

I can view the list of Realms, Users, Functions, Log.  But not the Dashboard. 

I notice that the following entries are logged.  (However these are logged for pretty much any activity in the whole dashboard)
```
i 2017-05-25T07:01:31.127Z client: Connection[8]: Connection closed due to error
e 2017-05-25T07:01:31.127Z client: Connection[8]: SSL handshake failed: certificate verify failed
```

I have start/stopped the service.  I have rebooted the server.  I have increased the RAM to 2gb.  There is plenty of available disk.

If I attempt to view a Realm in the Dashboard (by navigating to a realm and then clicking it's link) the screen shows "Loading" for approx 10 seconds before a "Timeout" message is displayed.  Reading the documentation I think this is because the ROS is not running on MacOS - it's not 100% clear.  But mention this just in case.

Any ideas?

**Comment by stel** [comment]
Thanks for reporting this @ianbradbury-bizzibody! Please try to update ROS to 1.7.2, we've fixed some related issues there.

Do you use SSL? Please try to disable it and/or make sure that you have valid certificates on your server.

**Comment by ianbradbury-bizzibody** [comment]
I have upgraded the ROS server - it now shows 1.7.5.

Unfortunately there is no real change.  When I select the Dashboard tab the screen displays `Loading...` for a second or two then nothing.  The same is true when I select/click on a Realm file in the Realms tab.

I notice that now I'm seeing the following errors over and over in the Log tab.

```
e 2017-06-02T04:01:24.854Z
statsd: events.js:160 throw er; // Unhandled 'error' event ^ Error: listen EADDRINUSE :::8126 at Object.exports._errnoException (util.js:1018:11) at exports._exceptionWithHostPort (util.js:1041:20) at Server._listen2 (net.js:1262:14) at listen (net.js:1298:10) at Server.listen (net.js:1394:5) at Object.exports.start (/usr/lib/nodejs/realm-object-server-developer/node_modules/statsd/lib/mgmt_server.js:21:10) at runServer (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/statsd/statsd-process.js:309:17) at Object.<anonymous> (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/statsd/statsd-process.js:500:1) at Module._compile (module.js:570:32) at loader (/usr/lib/nodejs/realm-object-server-developer/node_modules/babel-register/lib/node.js:144:5)

w 2017-06-02T04:01:23.173Z
StatsD server broke down. Attempting a restart.
```

**Comment by ianbradbury-bizzibody** [comment]
Update : Figured out the log messages.  They're being created by the DataDog agent.  So I've removed DataDog from the server to double check this was not impacting ROS.

Guess what.  Now that I've removed the DataDog..... I can see the dashboard charts!

The issue attempting to "view" the contents of a Realm in the Dashboard - "Loading..." followed by "Request Timed Out".

**Comment by stel** [comment]
@ianbradbury-bizzibody have you tried to disable SSL?

**Comment by Redth** [comment]
Same issue here.  Disabling SSL does seem to work, but that's not a realistic option.

My cert is generated via letsencrypt.

**Comment by bigfish24** [comment]
Just a small update, we have an internal fix for this waiting for review, so hopefully we can get it out soon. Sorry for the delay!

**Comment by stel** [comment]
I believe this issue has been fixed in one of the latest versions so I'm closing this issue for now. Feel free to reopen it if it still doesn't work for you.
