### ISSUE TITLE
HTTP: Failed to switch protocols (response status 400)

### ISSUE THREAD

**Issue by Redth** [realm/realm-mobile-platform#204]
## Goals

Xamarin.iOS client should connect (it used to, and in some cases for some accounts still does).

## Expected Results

Normal connection and sync to the ROS

## Actual Results

```
Connection[1]: Session[1]: Starting session for '/Users/redth/Library/Developer/CoreSimulator/Devices/GUID-HERE/data/Containers/Data/Application/ANOTHER_GUID/Documents/realm-object-server/GUID_USER_ID/realm%3A%2F%2Fmyservername.com%3A9080%2F%7E%2Fdefault'
Connection[1]: Resolving 'myservername.com:9080'
Connection[1]: Connecting to endpoint 'xx.yy.zz.11:9080' (1/1)
Connection[1]: Connected to endpoint 'xx.yy.zz.11:9080' (from '192.168.2.166:61896')
ERROR: Connection[1]: HTTP: Failed to switch protocols (response status = 400)
Connection[1]: Connection closed due to error
```

## Steps to Reproduce

Not sure why it's happening to only some users at this point.

## Version of Realm and Tooling

- Realm Object Server Version: 1.7.2
- Flavor:
  - [X] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: Ubuntu
- Client SDK Version: 1.4.0 (Xamarin)
- Client OS & Version: iOS (10.3)

## Logs

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>

w 2017-05-29T14:15:51.020Z
[proxy] internal error. Code undefined, status: undefined, message: TypeError: Cannot read property 'id' of null at ProxyService.getOrAssignNodeForFile (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/proxy.js:140:94) at ProxyService.webSocketUpgradeHandler (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/proxy.js:121:26) at ProxyService.safeUpgrade (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/proxy.js:78:12) at emitThree (events.js:116:13) at Server.emit (events.js:194:7) at onParserExecuteCommon (_http_server.js:411:14) at HTTPParser.onParserExecute (_http_server.js:379:5)

d 2017-05-29T14:15:51.017Z
proxy attempting to upgrade client ::ffff:206.47.179.118:61896 => headers: {"connection":"Upgrade","host":"poolmathappsync1.eastus.cloudapp.azure.com","sec-websocket-key":"SOME-VALUE","sec-websocket-protocol":"io.realm.protocol","sec-websocket-version":"13","upgrade":"websocket","x-realm-access-token":"TOKEN-STUFF-HERE==","x-realm-path":"/REALM_ID/default","x-realm-protocol-version":"17"}.}
  </code>
</details>

**Comment by bigfish24** [comment]
Can you describe your server setup? Are you using a proxy in front like NGINX?

**Comment by Redth** [comment]
Just the http proxy that ros sets up by default.

**Comment by Redth** [comment]
It seems like switching my config to use https on the client avoids the issue. I do have appropriate exceptions in my info.plist file specified but I wonder if somehow the TLS requirements in iOS are still interfering. It's just very odd that it only seems to happen in some cases.

**Comment by bigfish24** [comment]
@Redth "switching my config to use https" doesn't make sense to me. What exactly did you do? Did you setup ROS to use TLS?

**Comment by Redth** [comment]
Yes I've since enabled the https proxy (after creating a cert/private key) and now am connecting to 9443 instead of 9080 as previously.

**Comment by morten-krogh** [comment]
@Redth 
Do you think that the iOS TLS requirements explain what you see, or is there another issue?
I can look into your log files if you are interested.

**Comment by bigfish24** [comment]
This does sound like it is related to [App Transport Security](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33).

**Comment by Redth** [comment]
I can't seem to repro it after enabling TLS on the server, so I guess it's related to that.  It might make sense for the client to throw a better error in this case though.
