### ISSUE TITLE
Realm Browser: Auth works with u/p but not admin token

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-mobile-platform#206]
With Realm Browser 2.1.8 / Object Server 1.7.2 I am able to log into my server with the admin username / password. However, when I try to use the admin token I get:

![screenshot 2017-05-29 16 22 34](https://cloud.githubusercontent.com/assets/336441/26561317/520a86a0-448b-11e7-8d3b-f0693c5b945f.png)

**Comment by bigfish24** [comment]
Sorry about this! Are you using the `Connect to Object Server` command or directly opening a sync URL?

**Comment by agersoncgps** [comment]
I am choosing " Connect to Object Server"

**Comment by stel** [comment]
@agersoncgps could you attach the server logs as well? Thanks!

**Comment by agersoncgps** [comment]
[Terminal Saved Output.txt](https://github.com/realm/realm-mobile-platform/files/1043237/Terminal.Saved.Output.txt)

**Comment by stel** [comment]
According to the server logs a token you've provided is incorrect:
```
2017-06-01T00:09:01.750Z - error: sync-server: Sync Connection[9]: Session[1]: Signature does not match user token (signed_user_token='...mYN8FieolsAx4lGZqiN/rAS2N+Uw==').
2017-06-01T00:09:01.750Z - error: sync-server: Sync Connection[9]: Session[1]: Bad authentication (message_type='bind', signed_user_token='...mYN8FieolsAx4lGZqiN/rAS2N+Uw==').
```

Please make sure you entered the token correctly and without leading/trailing spaces.

**Comment by agersoncgps** [comment]
At the risk of opening up the security of my localhost test sever I lay my security bare here for all to see ;-)

![screenshot 2017-06-01 18 13 37](https://cloud.githubusercontent.com/assets/336441/26703137/2c7e354a-46f6-11e7-8367-035970ec53ef.png)

**Comment by stel** [comment]
@agersoncgps sorry for delay with this but honestly to me it's not clear what's going on there because everything seems fine :) Could you please try to update ROS to the latest version?

**Comment by bmunkholm** [comment]
@agersoncgps Do you still see this problem?

**Comment by bmunkholm** [comment]
Closing due to lacking response. Please reopen in case new information becomes available.
