### ISSUE TITLE
Realm data doesnt match between Object Server web gui and Mac Realm Browser

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-mobile-platform#207]
With Realm Browser 2.1.8 / Object Server 1.7.2

Realm browser shows, correctly, that all four of my tables are populated. The web gui does not show the same data. (Yes, I refreshed.)

![screenshot 2017-05-29 17 21 49](https://cloud.githubusercontent.com/assets/336441/26562370/c6dae8fa-4493-11e7-8750-9756c1801e34.png)

**Comment by agersoncgps** [comment]
I also noticed that my admin user's isAdmin value is false:
![screenshot 2017-05-29 20 51 04](https://cloud.githubusercontent.com/assets/336441/26564577/ab7cfd38-44b0-11e7-8f4e-f8a30bfc5b3f.png)

**Comment by bigfish24** [comment]
Sorry about this, does the web browser show any data for any Realm?

**Comment by agersoncgps** [comment]
Yes, it shows data for the permissions realms and in my screenshot you can see that some of the tables in my realm show data in the web display and some do not. While all tables in the app show data.

**Comment by stel** [comment]
We had an issue displaying `null` values that has already been fixed. It will be release in next version.

@agersoncgps could you share some logs from browser's console output?

**Comment by agersoncgps** [comment]
Of course. Is there any particular actions you want me to perform when capturing the logs? 

Should I open another issue about the isAdmin value?

**Comment by agersoncgps** [comment]
It did not output much. 

![screenshot 2017-05-31 20 15 40](https://cloud.githubusercontent.com/assets/336441/26659337/f82b51d2-463d-11e7-83ca-b9ffe0b394bc.png)

**Comment by stel** [comment]
Hm, interesting, there are no any errors in the browser. Could you also check server's logs?

**Comment by agersoncgps** [comment]
I dont see any generated by my clicking on the different tables in the web. I do see a lot of entries for this:

```
2017-06-03T03:06:46.646Z - error: client: Connection[4]: Failed to connect to endpoint ':::9080': Connection refused
2017-06-03T03:06:46.646Z - error: client: Connection[4]: Failed to connect to ':::9080': All endpoints failed
```

**Comment by stel** [comment]
@agersoncgps we've released an updated version recently, could you please update ROS and let us know if that issue is fixed? Thanks

**Comment by agersoncgps** [comment]
Updating to version 1.7.4 appears to have fixed the issue. Thanks.
