### ISSUE TITLE
What is the standard latency per bite in realm object server?

### ISSUE THREAD

**Issue by anujjpandey11** [realm/realm-mobile-platform#209]
Please update an standard latency chart of realm object server syncing on different network connection.

**Comment by kvap** [comment]
@anujjpandey11 can you provide more details on that kind of charts or link to some examples?

**Comment by anujjpandey11** [comment]
@kvap & @simonask 
I need an overview of average latency of sync:
Just assume that I commited an object with byte array and total data size is 10Kb then how long(average time) it will take to reach on ROS and how long to sync on other sync user.

what will be the average latency of 1Kb data sync. on wifi or on 3G/4G connection.

I need to do continuous syncing and I need to put sync interval greater then latency

**Comment by nirinchev** [comment]
Realm uses sockets to communicate with the server, so the latency depends entirely on the network conditions and proximity of the client to the server. There's nothing particular about Realm that would reduce or increase the latency. While Realm does add some information (and thus overhead) to the message, it is unlikely to noticeably affect the time it takes the information to reach the server. 

It wouldn't make sense for us to try to come up with an average latency, as using a 3g network in Copenhagen to talk to a server in Berlin would yield much different results compared to using a 3g network in Munich. Your best bet would be to ping your server from different networks that you expect your customers to use and use that as a reference point. 

I'm not sure what you mean by "do continuous syncing" and "put sync interval", can you elaborate on that bit.

**Comment by anujjpandey11** [comment]
Thanks @nirinchev

**Comment by simonask** [comment]
@anujjpandey11 As @nirinchev said, the observed latency will most probably be dominated by network latency. The only "added" latency by Realm Mobile Platform is the time required to resolve data conflicts, so in special situations you can see a higher latency if two clients are writing to the same Realms simultaneously. What this higher latency is depends entirely on the usage pattern. We encourage that you benchmark and measure yourself for your particular use case. :-)

**Comment by anujjpandey11** [comment]
Thanks guys...
