### ISSUE TITLE
Offline Access using Sync from JS SDK

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-mobile-platform#210]
This code is working to push and pull data from my realm. However, I want to test how it will behave in an offline sitaution so I turned off my Realm Server and get "TypeError: Network request failed" which I understand and "undefined" for this.realm. I would have expected this.realm to gracefully fail to the local copy. Why does it return undefined?

```
Realm.Sync.User.login(
      "http://localhost:9080",
      "me@domain.org",
      "password$",
      (error, adminUser) => {
        console.log(error);
        if (!error) {
          console.log(adminUser);
          this.realm = new Realm({
            sync: {
              user: adminUser,
              url: "realm://localhost:9080/master-cgps-realm-3"
            },
            schema: [
              StudentSchema,
              ParentPhonesSchema,
              ParentsSchema,
              ParentAdressSchema
            ]
          });
```

**Comment by mrackwitz** [comment]
You have run across something that we are still working on. Once you have a Realm and an established connection, going offline works just fine. But initially, you do need the network. Obviously this is something that we are fixing, stay tuned. This is something that interferes quite significantly with the whole sign-in/sign-up process, so it needs to be thought out.

This was also already brought up as #14 here and over in the JS SDK repo as https://github.com/realm/realm-js/issues/857.

You'll find there some code samples how you can work around such scenarios. When trying to work around this yourself, keep in mind that you can't just use a non-synced Realm and open it with a sync configuration later. We use different history types, optimized for each use case. So if you would want to use a local database and can't rely on initial online access, you would need to migrate the data yourself from a local offline Realm to the local synced copy.

**Comment by agersoncgps** [comment]
@mrackwitz Could you just clarify something in your statement: "Once you have a Realm and an established connection, going offline works just fine. But initially, you do need the network." Do you mean:

1. The very first time the user launches the app a network connection is required, but after that it creates a local copy and if they launch it a week later with no network it will use its local copy and work fine

or

2. Every time they launch the app they need a network connection to initially load the realm, and then if they loose network later on in the same session the data persists locally and is usable

?

**Comment by mrackwitz** [comment]
I mean 1. Once the user is signed up, the authentication info will be automatically stored locally in a metadata realm, so that it will be available on subsequent app launches.
