### ISSUE TITLE
ROS 1.7.4 dashbord error

### ISSUE THREAD

**Issue by dina304** [realm/realm-mobile-platform#213]
## Goals

we are trying to use dashbord-> realms
see what inside the DB

## Expected Results

when click on the database link 

## Actual Results

nothing happens 
- if its my custom DB - it show empty screen
- if its some realM DB like permissions - it show : loading screen 

## Version of Realm and Tooling

- Realm Object Server Version: 1.7.4-5
- Flavor:
  - [ ] Developer
  - [X] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

i checked the logs and no error there
i payed attention that the links navigate to no where 

thanks
Dina

**Comment by bmunkholm** [comment]
@dina304 Did you perhaps upgrade from an earlier version? Or is this from a fresh install?
Did you try to "refresh" the browser window?
Could you give us instructions as to how this can be reproduced?

**Comment by stel** [comment]
Also that would be very helpful if you share log messages from the server and from the web-browser console.

**Comment by stel** [comment]
I believe this issue has been addressed in one of the latest updates, so I'm closing it for now. @dina304 please feel free to reopen it or create a new one if you're still getting this behaviour.
