### ISSUE TITLE
AsynOpen() fails on next login after logout

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-mobile-platform#214]
## Goals

Log back in after user logout while using AsyncOpen()
## Expected Results

should have been able to log in/out without issue
## Actual Results
RealmSwift reports the following error:

> Error Domain=io.realm.sync Code=4 "Cannot asynchronously open synced Realm, because the associated session previously experienced a fatal error" UserInfo={NSLocalizedDescription=Cannot asynchronously open synced Realm, because the associated session previously experienced a fatal error}

See error above

## Steps to Reproduce
1. Log in to a synced realm using AsyncOpen to ensure the realm is full downloaded 
2. log out
3. try to log back in as _another user_
4. error will occur as part of return from AsyncOpen call 

## Code Sample

 https://github.com/realm/AsyncOpen-Error-Tester

## Version of Realm and Tooling
This seems to be a regression somewhere -- this did not occur priory's to release 1.7.2.

- Realm Object Server Version: ? 1.7.2 -> 1.7.5 (RMP PE)
- Flavor:
  - [ ] Developer
  - [x ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6),  macOS 
- Client SDK Version: ? 2.7.0 -> 2.8.0
- Client OS & Version: ? macOS 10.12.5

## Logs

Fails  silently - no relevant log entries produced either on client or server.

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by gritzko** [comment]
The error message comes from `Realm/RLMRealm.mm` in the Cocoa binding.
@dhmspector are you sure it should be filed in realm-sync?

**Comment by nirinchev** [comment]
Perhaps @austinzheng can shed more light. In any case, posting the relevant code would help us pinpoint the culprit.

**Comment by dhmspector** [comment]
Figured it out:

It happens when you _switch users_ after a logout.  For example in teamwork  Ian is logged in, then logs out and then immediately logs back in - no problem.

If we log out and then try to log back on the same device with my account (which of course would sync the same realms... but as ME) I get the error.

**Comment by dhmspector** [comment]
Here's the test app that will demo the issue:  https://github.com/realm/AsyncOpen-Error-Tester

**Comment by dhmspector** [comment]
@austinzheng New news -- this is a deeper issue that it appears:

Once you log in to an an using AsyncOpen, any subsequent uses of the AsyncOpen call -- to open other Realms for example -- will fail silently.

**Comment by dhmspector** [comment]
@austinzheng  Another data point - a customer reported to @ianpward  that if you are an _admin_ user AsyncOpen seems to work -- which we can verify from TeamWork - we seem to be able to open multiple Realms with AsyncOpen from TeamWork admin-user  accounts.

**Comment by austinzheng** [comment]
Can you give me access to the demo app repo please? Also, are you opening global Realms, or Realms with `~`s in them? I believe that the intended behavior is that global Realms cannot be created by non-admin users using `asyncOpen()` if they don't already exist, or opened by non-admin users if they do.

**Comment by dhmspector** [comment]
https://github.com/realm/AsyncOpen-Error-Tester 

 this will show the re-open, logout then from another user problem... I haven't yet (since we just figured out the other failure mode this morning) written code to show what happened if you log in and then try to use AsyncOpen from non-admin users. In teamwork's case the other Realms are already in existence, and there RW permission is set so the non admin users DO have access to them..

**Comment by austinzheng** [comment]
Hmm...I still get a 404 when I click on the link.

**Comment by dhmspector** [comment]
sorry.. for some reason GH didn't apply any access permissions for realm folks.. fixed

**Comment by dhmspector** [comment]
resolved  Part 1 - multiple login/logout/login issue was result of a poorly defined static constant in TeamWork which was setting up (but not resetting) Syncuser.current across logouts.

 Part 2: failure to AsyncOpen() of global Realms by non-admin users is still an issue - moved to https://github.com/realm/realm-object-server/issues/1216
