### ISSUE TITLE
Unknown provider returned from registerWithProvider

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-mobile-platform#215]
I am trying to create a custom auth provider called "cgpsauth" and I am getting "Unknown provider" when I call:
```
  var ru = Realm.Sync.User.registerWithProvider(
        "http://localhost:9080",
        "cgpsauth",
        accessToken,
        (error, user) => {...
```

Here is my provider which I know is being loaded because if I make a syntax error in this file I get an error when I launch the ROS:

```
module.exports = function(deps) {
  return class CgpsAuthProvider extends deps.BaseAuthProvider {
    
    static get name() {
      return 'custom/cgpsauth';
    }

    constructor(name, options, requestPromise) {
      super(name, options, requestPromise);
    }

    verifyIdentifier(req) {
      const token = req.body.data;
      return 30;
    }
  }
};
```

configuration.yml

```
  providers:
     custom/cgpsauth:
      implementation: cgpsauth.js
```

**Comment by mrackwitz** [comment]
You have to prefix the provider name when authenticating from the client SDK with `custom/`.

**Comment by agersoncgps** [comment]
Thanks! I should have tried that. (I thought I did.) However, I think the docs make it a little confusing. In  [docs for Access Control ](https://realm.io/docs/realm-object-server/#access-contro) you give the example:

```
static get name() {
      return 'custom/fooauth';
    }
```

But then in the [example for Custom Auth ](https://realm.io/docs/javascript/latest/#sync) you just use "fooauth".

```
const user = Realm.Sync.User.registerWithProvider(
  'http://my.realm-auth-server.com:9080',
  'fooauth',
  accessToken,
  (error, user) => { /* ... */ }
);
```

I would think it should be:

const user = Realm.Sync.User.registerWithProvider(
  'http://my.realm-auth-server.com:9080',
  'custom/fooauth',
  accessToken,
  (error, user) => { /* ... */ }
);

**Comment by bigfish24** [comment]
I filed an issue to update the code sample, sorry about that!

**Comment by agersoncgps** [comment]
Sorry to open this back up again. I am sure I am doing something wrong, but I have tried everything I can think of.

I got custom auth working on 1.7.4 on my local Mac. I then set up a 1.7.5 server on Ubuntu. I copied my config values over to the default configuration.yml and it is now saying "Unknown provider!" again. If I point my client code to the local Mac server it works, but when I point it to the Linux server it fails. 

So I know its something with the configuration.yml or something else on the server, but as far as I can tell I used the identical values. The only difference is I put the custom auth provider js file (cgpsauth.js) in "/usr/local/lib/realm/auth/providers" - which I had to create. I have tried opening up permissions on this path to 777 and I even tried putting the custom provider js in /home/ubuntu and /tmp and specifying those paths as my providers_include_path. I don’t see anything in the logs that might indicate at what point its failing, but I appear unable to get ROS to notice any custom auth file at any path I specify for providers_include_path. If I make a syntax error in the custom auth file and restart the service it does not complain or crash, which is did on my Mac when I had a syntax error. 

![screenshot 2017-06-11 20 34 45](https://user-images.githubusercontent.com/336441/27015796-7fdf3ed6-4ee5-11e7-855c-885bb93be55a.png)

**Comment by mrackwitz** [comment]
If a provider is configured, an implementation is required. If no implementation would be found, the server would log an error and fail to start.

That given, could it be the case that your configuration changes are not picked up by the server?

**Comment by ianpward** [comment]
@agersoncgps I would also suggest making sure that all npm packages for your custom auth code are installed locally on your server. What happens if you run the script manually? 

`node cgpsauth.js`

**Comment by agersoncgps** [comment]
@mrackwitz I thought that could be the case as well, but I have made several other changes to the configuration that have all applied. I changed the logging level to 'debug', enabled the https proxy, installed the cirtificates and keys. When I run it in debug mode it also shows all these values loaded in:

`2017-06-12T23:03:04.929Z - debug: Realm Object Server starting with configuration: {"file":{"path":"/etc/realm/configuration.yml"},"development":false,"storage":{"root_path":"/var/lib/realm/object-server","internal_data":{"root_path":"/var/lib/realm/object-server/internal_data","stats_path":"/var/lib/realm/object-server/internal_data/stats.realm","auth_path":"/var/lib/realm/object-server/internal_data/auth.realm","analytics_path":"/var/lib/realm/object-server/internal_data/analytics.realm","permission_path":"/var/lib/realm/object-server/internal_data/permission"},"user_data":{"root_path":"/var/lib/realm/object-server/user_data"}},"network":{"http":{"listen_address":"127.0.0.1","listen_port":27080}},"sync":{"servers":[{"id":"0","address":"0.0.0.0","port":27800}],"base_url":"realm://127.0.0.1:9080"},"auth":{"ttls":{"refresh_token":315360000,"access_token":600},"sync_hosts":["127.0.0.1:9080","localhost:9080","::1:9443","localhost:9443"],"providers":{"realm":{},"password":{}},"public_key_path":"/etc/realm/keys/public_key.pem","private_key_path":"/etc/realm/keys/private_key.pem","providers_include_path":"/usr/local/lib/realm/auth/providers","database_sync_uri":"realm://127.0.0.1:9080/__admin"},"proxy":{"http":{"enable":true,"listen_address":"127.0.0.1","listen_port":9080},"https":{"enable":true,"listen_address":"::","listen_port":9443,"certificate_path":"/etc/realm/keys/https-proxy.crt","private_key_path":"/etc/realm/keys/https-proxy.key"}},"logging":{"level":"debug","path":"/var/log/realm-object-server.log"},"enterprise":{"skip_setup":false},"sync_hosts":{"ttls":null,"providers_include_path":"/usr/local/lib/realm/auth/providers","providers":{"custom/cgpsauth":{"implementation":"cgpsauth.js"}}},"performance":null,"backup":{"enable":true,"network":null,"logging":{"path":"/var/log/realm-object-server-backup-server.log"}}}`

PS: Anything in here I should change for security now that I have posted in publially?

**Comment by agersoncgps** [comment]
@ianpward At this time I dont have any custom npm packages. I hacked it to just return a static id for testing purposes:
```

module.exports = function(deps) {
  return class CgpsAuthProvider extends deps.BaseAsssuthProvider {
    
    static get name() {
      return 'custom/cgpsauth';
    }

    constructor(name, options, requestPromise) {
      super(name, options, requestPromise);
    }

    verifyIdentifier(req) {
      const token = req.body.data;

      var promise = new Promise(function(resolve, reject) {
        // do a thing, possibly async, then…

        if (true) {
          resolve("30");
        }
        else {
          reject(Error("It broke"));
        }
      });
      return promise;
    }
  }
};

```

When I run it manually it just returns:

```
ubuntu@ip-172-31-37-66:/usr/local/lib/realm/auth/providers$ node cgpsauth.js
ubuntu@ip-172-31-37-66:/usr/local/lib/realm/auth/providers$ 
```

**Comment by mrackwitz** [comment]
Thanks for posting the logs from startup. I was so free and extracted the minified JSON configuration from the log message and pasted it in a beautified serialization. That showed that the configuration keys for the custom authentication provider sit under the key `sync_hosts` instead of `auth.providers` where it would be expected.

```js
    …
    "auth": {
        "providers": { // that's where the configuration would be expected
            "realm": {},
            "password": {}
        },
        …
    },
    "sync_hosts": {
        …
        // but it sits here
        "providers_include_path": "/usr/local/lib/realm/auth/providers",
        "providers": {
            "custom/cgpsauth": {
                "implementation": "cgpsauth.js"
            }
        }
    },
```

Could you verify that you configure this in the right place in your `configuration.yml`? Unknown keys in the configuration aren't rejected so far, so when they are misplaced, it would just slip through.

Re your P.S: No worries, you did not disclose any sensitive information here. :wink:

**Comment by agersoncgps** [comment]
Amazing! Thank you! The problem was a single tab missing before "sync_hosts". 

"sync_hosts" was on an equal level to "auth", as opposed to a child of it where it belonged.
