### ISSUE TITLE
An error occured when try to write to realm object server  

### ISSUE THREAD

**Issue by marcuswu0814** [realm/realm-mobile-platform#216]
## Goals

I follow the [tutorial](https://realm.io/docs/tutorials/realmtasks/#import-realm-swift-and-create-models) and try to build a todo list app with swift project, 

## Expected Results

I think I can see the task on tableView after I added one.

## Actual Results

But I got the error:

~~~
2017-06-07 17:13:56.465437+0800 RealmToDo[8294:13899640] [Common] _BSMachError: port 150f; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND"
2017-06-07 17:13:56.465741+0800 RealmToDo[8294:13899640] [Common] _BSMachError: port 150f; (os/kern) invalid name (0xf) "Unable to deallocate send right"
~~~

and didn't got correct result and show on screen.

I think is client problem cause this issue, is any config missing?

## Version of Realm and Tooling

- Realm Object Server Version: **1.7.5**
- Flavor: **Developer**
- Server OS & Version: **Ubuntu 16.04.2 LTS**
- Client SDK Version: **Realm-Swift 2.8**
- Client OS & Version: **iOS 10**

**Comment by gritzko** [comment]
Looks similar to this: https://stackoverflow.com/questions/39676762/error-bsmacherror-port-1607-os-kern-invalid-capability-0x14-unable-to-i

**Comment by gritzko** [comment]
It looks like a generic iOS 10 issue. Closing.

**Comment by marcuswu0814** [comment]
I think this is my break point cause this problem. After I removed it, the error disappear.

But, why I can't insert the data to my realm object server?

**Comment by marcuswu0814** [comment]
I think I found the mistake, I didn't have any record in TaskList table.

Result from: https://stackoverflow.com/questions/41846405/trying-to-use-realm-object-server-tutorial

Sorry for making this trouble.
