### ISSUE TITLE
macOS bundle still on 1.7.4

### ISSUE THREAD

**Issue by RiverbayChris** [realm/realm-mobile-platform#217]
I've seen numerous references to 1.7.5 available, but the macOS download still points to 1.7.4.  I've tried to change the path, but it seems the zip doesn't exist yet.

**Comment by nnrealm** [comment]
Do you mean the bundle here?

https://realm.io/docs/get-started/installation/mac/

That's 1.7.5 as of today.

**Comment by RiverbayChris** [comment]
Yeah it has since been updated.  Thanks!
