### ISSUE TITLE
ROS: Loss of access to a database

### ISSUE THREAD

**Issue by YaTree** [realm/realm-mobile-platform#218]
## Goals

Create a database on ROS

## Expected Results

Database was created and we always can access to it

## Actual Results

Database contains 20k objects. And it was created successfully;
Then we was able to access to the database via any client: realm-browser/android-app.
But then we lost access to the database: it does not open from realm-browser.
Then I removed the db (First from web-ui, then from /var/lib/realm/*, restarted ROS), and I created new one with same name. - at the end of creating I recieved error 208. Results - no access.
Then I created new database with another name (all schemas, data - the same) -   I got access to new db.

The database has read-write access, created by admin user.
AndroidApp opens realm with same credentials(via Sync User). It does not modify the database, only read.

## Steps to Reproduce

I dont know reasons why we lost access to first databasae.

## Version of Realm and Tooling

- Realm Object Server Version: last one
- Version of realm for creating db - trial professional.

## Logs
Here is log of failed request to database vie realm-browser:

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
  
Logs from /var/log/realm-object-server:
2017-06-08T10:46:31.666Z - info: sync-server: HTTP Connection[35]: Connection from 127.0.0.1:32794
2017-06-08T10:46:31.666Z - info: sync-server: HTTP Connection[35]: Received: Sync HTTP request(protocol_version=17)
2017-06-08T10:46:31.733Z - info: sync-server: Sync Connection[35]: Session[1]: Session initiated (session_ident=1).
2017-06-08T10:46:31.733Z - info: sync-server: Sync Connection[35]: Session[1]: Received: BIND(server_path=/c982099ae2f950bd5a437a497c1ca561/products/42, signed_user_token='...Bw4zzrcamxL09WhkrgfPTxSNbaeQ==', need_file_ident_pair=0)
2017-06-08T10:46:31.835Z - info: sync-server: Sync Connection[35]: Session[1]: Received: IDENT(server_file_ident=1, client_file_ident=2, client_file_ident_secret=8004746042331843040, scan_server_version=0, scan_client_version=0, latest_server_version=0, latest_server_session_ident=0)
2017-06-08T10:46:36.600Z - info: sync-server: Sync Connection[35]: Session[1]: Session terminated (session_ident=1).
2017-06-08T10:46:36.600Z - info: sync-server: Sync Connection[35]: Connection closed by client: End of input
  </code>
</details>

<details>
  <summary>Logs from eth0:</summary>
  <code>
  
079.180.093.001.49366-010.000.000.160.09080: GET /realm-object-server HTTP/1.1
Connection: Upgrade
Host: 
Sec-WebSocket-Key: Ucw6dxB9Tf0ldhgxEckX3Q==
Sec-WebSocket-Protocol: io.realm.protocol
Sec-WebSocket-Version: 13
Upgrade: websocket
X-Realm-Access-Token: ewoJImlkZW50aXR5IjogIl9fYXV0aCIsCgkiYWNjZXNzIjogWyJ1cGxvYWQiLCAiZG93bmxvYWQiLCAibWFuYWdlIl0KfQo=:slufw5f4bnhXs6EiaZVifVD+SY/mZYxbN5nVgN5YRqKiM3M4kd2n2S2MovrtGmk0VL8yulxoa5PHbdoeXoe2Fmm7yy0qHKWxNbw7DawvNIBAbXxXVmbs+3l/B+lYapOaLeX+8wI9RYc6X8DVbwhL/FqyHt4TLgefmIIgxsA4cvSxpg59so9cnEuiboka3kaxdFD9MOQzu2/gZ3uwHv6tfnFVlagNF+NhYoZjt6+VuctGMj17pzRItu5oXEUIcvOL92ct6VnWRNsDr/xLumHaH8jaj+6yhrX8xVG3dkMuvL9JTNBec5IKo9UINuBw4zzrcamxL09WhkrgfPTxSNbaeQ==
X-Realm-Path: /c982099ae2f950bd5a437a497c1ca561/products/42
X-Realm-Protocol-Version: 17

010.000.000.160.09080-079.180.093.001.49322: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49324: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49323: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49329: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49332: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49334: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49326: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49333: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49330: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49328: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49331: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49359: gdownload 1 3192 0 3192 2422022400218884869 0 152033 0 44 0
3192 0 76848221452 3 20 = ===
010.000.000.160.09080-079.180.093.001.49366: HTTP/1.1 101 Switching Protocols
connection: Upgrade
sec-websocket-accept: YQDgeulxVOvGhXMoa8Pv8oB9t2E=
sec-websocket-protocol: io.realm.protocol
upgrade: websocket
  </code>
</details>

**Comment by gritzko** [comment]
208 is OK. It says your client replica is a replica of a different realm. Which is exactly the case.

Regarding the original database, maybe you mistyped the password?

**Comment by YaTree** [comment]
The password is hardcoded in scripts and in realm-browser it saved.
So I not think that problem in the password.

**Comment by gritzko** [comment]
Did your script get any error?

**Comment by YaTree** [comment]
No, nothing strage.

**Comment by ianpward** [comment]
@YaTree this is working as expected because the client is ahead of the history of the server so a 208 is served. With the other mobile bindings you can programmatically handle the client reset, like this: https://realm.io/docs/swift/latest/#client-reset

This has not landed in JS yet - to resolve this wipe the realm folder on the client

**Comment by YaTree** [comment]
Ok. Thx.
