### ISSUE TITLE
isAdmin returns false when user is admin

### ISSUE THREAD

**Issue by agersoncgps** [realm/realm-mobile-platform#220]
After logging a user in I am printing out the user object and it shows isAdmin = false when the user is in fact an admin. 

![ab7cfd38-44b0-11e7-8f4e-f8a30bfc5b3f](https://user-images.githubusercontent.com/336441/26995964-b4b8349a-4d3d-11e7-9ded-afa4591524a7.png)

**Comment by bigfish24** [comment]
Assuming you mean the browser is just displaying it incorrectly, right?

**Comment by agersoncgps** [comment]
The browser is displaying it just fine. The user is an admin. The user object returned from the login when displayed in the console.log() contains an incorrect value.

**Comment by kristiandupont** [comment]
I've created an issue for this in the JS repo: realm/realm-js/issues/1063

**Comment by kspangsege** [comment]
Thanks. Closing this one then.
