### ISSUE TITLE
Swift: group Realm database with date in tableview section

### ISSUE THREAD

**Issue by o1xhack** [realm/realm-mobile-platform#222]
## Goals

In Swift, when I using tableview, I want to group my data with date and show them in section.

For example I have:
20/5/2017 12:25 100ml
20/5/2017 14:40 200ml
21/5/2017 8:30   500ml
21/5/2017 18:30 100ml
NSDate()             Int

## Expected Results

So it groups with date:

20/5/2017  //section title
12:25  100ml  // cell in this section
14:40  200ml

21/5/2017 // section title
8:30  500ml
18:30  100ml

So I need to find a way to separate NSDate() into date and time and compare them. But I cannot find any way in Realm that can fetch certain data in a group.

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [ ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? (e.g. CentOS 6)
- Client SDK Version: ?
- Client OS & Version: ?

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    Paste output here
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    Paste output here
  </code>
</details>

**Comment by bmunkholm** [comment]
Hi @o1xhack - This is related to the Cocoa SDK and more about usage rather than bugs. As stated in the readme and the issue template, we ask to use github for bugs or feature requests and StackOverflow for usage related questions. This sounds like a great question for StackOverflow.
Thanks!
