### ISSUE TITLE
Sharing Realm Between Users using PermissionOffer 

### ISSUE THREAD

**Issue by AshaChaparala** [realm/realm-mobile-platform#224]
Hi ,I am trying to implement Realm in my Android app.
I was stuck in Sharing Realm Between Users.
1.Send the token to another user via any method.[ which method i need to use to send token to other user ?]
2.I have User Details Model-if i want this to share User Details data to all users 
Did i need to use PermissionOffer and PermissionOfferResponse classes to share or any other way ?

**Comment by bmunkholm** [comment]
@AshaChaparala : As stated in the issue template, please post usage related questions to StackOverflow - we respond to those there. Thanks!
