### ISSUE TITLE
the onsuccess is fire even when my task is not done.

### ISSUE THREAD

**Issue by yamamz** [realm/realm-mobile-platform#23]
```java
public void onItemLongClick(View view, final int position) {


              realm.executeTransactionAsync(new Realm.Transaction() {
                  @Override
                  public void execute(Realm bgRealm) {
                      final RealmResults<Device> deviceQuery=bgRealm.where(Device.class).findAllSorted("ipAddress", Sort.ASCENDING);

                      deviceQuery.deleteFromRealm(position);
                  }
              }, new Realm.Transaction.OnSuccess(){
                  @Override
                  public void onSuccess () {

                      adapter.notifyItemRemoved(position);
                      Toast.makeText(MainActivity.this,"successfully deleted",Toast.LENGTH_LONG).show();
                  }

              });

          }
      }));
```

**Comment by yamamz** [comment]
the deleted items is database is not the same in UI because the onSuccess fire even if the transaction is not completed yet

**Comment by sorenvind** [comment]
Hi @yamamz!

Do you see this problem only when running with Realm Object Server, or does it also happen with just the Realm Mobile Database?

**Comment by yamamz** [comment]
hi @sorenvind 
it happens on realm local database...   what is the solution of this... thanks

**Comment by zaki50** [comment]
@yamamz Why do you think `onSuccess` was fired before the transaction was completed?
Are you still seeing the deleted object in the `onSuccess` method?

**Comment by zaki50** [comment]
One more question.
Are you using `RealmRecyclerViewAdapter`?

**Comment by zaki50** [comment]
@yamamz I think this issue is not related to RMP.
Could you move this issue to https://github.com/realm/realm-java/issues ?

**Comment by yamamz** [comment]
@zaki50 yes i,m see i am seeing the deleted object in in onsuccess but when i loaded all the data the deleted item is minus one to the original position  because the on success was executed and the ui position is change already..

**Comment by zaki50** [comment]
moved to realm/realm-java#3663
