### ISSUE TITLE
Dashboard: Realm name/path/owner display bug

### ISSUE THREAD

**Issue by RiverbayChris** [realm/realm-mobile-platform#232]
## Goals

Organize realms into subfolders at both the global level as well as within users ~/ folder.

## Expected Results

Viewing such realms in the dashboard should work, with realm names reflecting correct path.

## Actual Results

When a realm that is two folders deep within a user's folder is viewed in the dashboard, the page is blank.  The realm exists as I can read/write to it fine in code.  Also, if you try this same behavior at the root, the page is not blank, but instead shows the Realm name and path as "/~/realmName", even though it is in a subfolder.

Also related, when an admin creates a realm in another user's folder (so admin is the owner), the dashboard shows the Owner as that user, instead of the admin.  This may be the case between users too, I just only checked with admin so far.

## Steps to Reproduce

Open a realm with a subfolder path (like ~/someSubfolder/theRealm).

## Version of Realm and Tooling

- Realm Object Server Version: ?
- Flavor:
  - [X ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? MacOS
- Client SDK Version: ?  2.8.3 with ROS 1.8.1
- Client OS & Version: ?

## Logs

**Comment by kraenhansen** [comment]
Thanks for the issue!
I believe we are tracking this issue as https://github.com/realm/realm-object-server/issues/1280 internally and as stability and the browser is a priority at the moment I believe we'll have a fix for it very soon.

**Comment by kraenhansen** [comment]
@RiverbayChris: Just wanted to update you on the progress on this one, we have a fix ready which is waiting for another PR to be merged. Until then I wanted to let you know if you're on a Mac you can use the Mac Browser to browse the realms in ROS until the fix is released. Thanks again for reporting the issue.

**Comment by kraenhansen** [comment]
@RiverbayChris: Wanted to let you know that a fix for this has now merged and will be released when the next version of Realm Object Server comes out.

Please re-open if you experience this issue again with the next version of ROS and thanks again for reporting this!
