### ISSUE TITLE
View sync'd realm data in the web browser

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-mobile-platform#234]
## Goals

Browse realms.

## Expected Results

Insights.

## Actual Results

<img width="1203" alt="ros v1 8 1-chronic-loading 2017-07-10 at 15 42 07" src="https://user-images.githubusercontent.com/7915553/28023776-c12b13da-6586-11e7-981d-ea9ae07c086c.png">

## Steps to Reproduce

http://52.210.33.82/realms/bookstore-01

## Code Sample

http://52.210.33.82/realms/bookstore-01

## Version of Realm and Tooling

- Realm Object Server Version: v1.8.1
- Flavor:
  - [ x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ubuntu
- Client SDK Version: github "realm/realm-cocoa" "v2.8.3"
- Client OS & Version: Sierra 10.12.4 (16E195)

## Logs
<img width="838" alt="realm-failure-log" src="https://user-images.githubusercontent.com/7915553/28023994-68673944-6587-11e7-97c4-00ae8acfdfdb.png">
<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    ...
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    ...
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
    ...
  </code>
</details>

**Comment by stel** [comment]
Thanks for reporting this, @DanielAsher! Could you please provide some info like server logs and logs from the browser's console, thanks!

**Comment by bmunkholm** [comment]
@DanielAsher Are you still experiencing this issue? Can you provide the requested info and login info to your server?

**Comment by DanielAsher** [comment]
Hi Brian,
sorry not to follow this up. I am still experiencing this issue, though it
seems not to affect a couple of my colleagues. I assume that my browser
configuration could be influencing this (perhaps ad blockers?) as I
experience it on both Chrome and Safari. I've not had time to dig in as we
require an ability to edit our data (so a bespoke mechanism has been more
important to us)
Thanks,
Daniel

**Comment by bmunkholm** [comment]
@DanielAsher Please try out the new Realm Studio: https://realm.io/docs/realm-object-server/latest/#realm-studio-1 and let us know if you still experience issues.
