### ISSUE TITLE
IllegalArgumentException: Unknown error code: 112

### ISSUE THREAD

**Issue by anujjpandey11** [realm/realm-mobile-platform#235]
Sync was working fine for initial stage after some time application stopped syncing data and I'm getting
IllegalArgumentException: Unknown error code: 112 repeatedly, there is no definition for this bug, please clarify the case.

**Comment by bmunkholm** [comment]
This is being dealt with by email. Closing here for now.

**Comment by anujjpandey11** [comment]
@bmunkholm I didn't got the answer what is this error code 112 and why it is coming?

**Comment by bmunkholm** [comment]
@anujjpandey11 Please use the issue template with details about which SDK, version, and sample code for getting this error. Otherwise it's very hard to help you when your context is not clear. In case this is an error that originates in an SDK, please file the issue in the relevant repo. The READM.md in this repo contains links.
Thanks!

**Comment by anujjpandey11** [comment]
@bmunkholm If sdk is returning error code 112 it simply means there will be some definition for this error code, I'm not able to figure out why there is a need of sample code or use case if there is an error code. error code comes in predefined use case usually.

**Comment by bmunkholm** [comment]
@anujjpandey11 It's really hard when you are not even telling me which SDK and version you are using :-) And not knowing which function you are calling and getting the error message from doesn't make it easier. If you want help, then please enable us to help you.

**Comment by anujjpandey11** [comment]
Sdk version is 3.5.0

**Comment by bmunkholm** [comment]
Please do give all the information you can. IllegalArgumentException obviously is a response to an illegal argument. It helps tremendously to know exactly which function that gave you this exception and which parameters you passed. Providing us as much info as possible is the only way for us to be able to help you.

**Comment by anujjpandey11** [comment]
I was committing data to ROS with an alarming interval of 5 second after a period of time I found syncing is stop with bad change set exception and application is close, now whenever I restart my application I got this exception repeatedly. 

I written all the local logs to a file and I found nothing wrong with my data.

This is where I'm getting this issue 

```

    public Realm getSyncRealm() throws RealmAuthException {
        if (mRealmPrivate != null)
            return mRealmPrivate;
        Realm.init(this);
        SyncUser user = SyncUser.currentUser();
        if (user != null && user.isValid()) {
            String url = getURI(user, REMOTE_PRIVATE_DIRECTORY);
            mPrivateConfig = new SyncConfiguration
                    .Builder(user, url)
                    .directory(Methods.getSyncDirectory())
                    .modules(new PrivateSyncModule())
                    .name(REMOTE_PRIVATE_DIRECTORY + ".realm")
                    .schemaVersion(BuildConfig.REALM_VERSION)
                    .build();
            mRealmPrivate = Realm.getInstance(mPrivateConfig);
        }
        return mRealmPrivate;
    }

    /**
     * @param dirName Dedicated Directory name
     * @return Uniform resource path
     */
    private String getURI(String dirName) {
        return REALM_PARENT_DIRECTORY + "~" + "/" + Methods.getTempUniqueId() + "/" + dirName;
    }

```

and unfortunately the exception is redirecting me here


   ```
 public static ErrorCode fromInt(int errorCode) {
        ErrorCode[] errorCodes = values();
        for (int i = 0; i < errorCodes.length; i++) {
            ErrorCode error = errorCodes[i];
            if (error.intValue() == errorCode) {
                return error;
            }
        }
        throw new IllegalArgumentException("Unknown error code: " + errorCode);
    }
```

io.realm.ErrorCode line number 183

This is all I can say about this apart from this if I can have any clue on it I don't think that I need to raise a bug.

**Comment by bmunkholm** [comment]
Ok. Showing the call stack when you get the exception could have been useful. I'm still not sure exactly where the exception is thrown from? But it's now at least clear that we are talking about a sync error-code, and that 112 means "Bad changeset".
This means that we are receiving a change from the server that doesn't match our expectations somehow. That's very likely due to a mismatch in schema's/datamodels between the server and the client. So if you have changed the schema in a way that's not just additive, then you won't be able to sync the data, and you have to wipe the data on the client.

**Comment by anujjpandey11** [comment]
Actually on realtime sycing application got crashed with Bad change set and next time while I'm opening it show me this... is there some other way I can check which of my data is not proper.

**Comment by anujjpandey11** [comment]
@bmunkholm  here are the complete logs why I'm getting bad change set 

**Device Logs**

> > D/REALM_SYNC: Using already open Realm file: /storage/sdcard0/KentTracker/Sync/031a4d341c1f20f57767d7b3386010fe/031a4d341c1f20f57767d7b3386010fe/2056696625/private.realm
> D/REALM_SYNC: Connection[1]: Session[2]: Sending: UPLOAD(**client_version=1771**, **server_version=1593**, changeset_size=203843, timestamp=80999100127)
> 
> D/REALM_SYNC: message_type = error
> 
> I/REALM_SYNC: Connection[1]: Received: ERROR(error_code=212, message_size=22, try_again=0, session_ident=2)
> 
> I/REALM_SYNC: Connection[1]: Connection closed due to error reported by server: Bad changeset (UPLOAD) (212)
> D/REALM_SYNC: Connection[1]: Reconnecting in 17025 milliseconds

 

> **Server Logs**
> info: sync: HTTP Connection[55244]: Connection from 127.0.0.1:49588
> 
> info: sync: HTTP Connection[55244]: Received: Sync HTTP request(protocol_version=18)
> 
> info: sync: Sync Connection[55244]: Session[2]: Session initiated (session_ident=2).
> 
> info: sync: Sync Connection[55244]: Session[2]: Received: BIND(server_path=/031a4d341c1f20f57767d7b3386010fe/2056696625/private, signed_user_token='...zOZwJKVo/jQkx74jPMcOAaT0fRlA==', need_file_ident_pair=0)
> info: sync: Sync Connection[55244]: Session[2]: Received: IDENT(server_file_ident=1, client_file_ident=2, client_file_ident_secret=7052751188005760600, scan_server_version=1800, scan_client_version=1763, latest_server_version=1800, latest_server_session_ident=5953965513565227173)
> detail: sync: Sync Connection[55244]: Session[2]: Sending: DOWNLOAD(**scan_server_version=1800**, **scan_client_version=1763**, latest_server_version=1800, latest_server_session_ident=5953965513565227173, **latest_client_version=1763**, number of changesets=0, downloadable_bytes=15074)
> detail: sync: Sync Connection[55244]: Session[2]: Received: UPLOAD(**client_version=1769**, **server_version=1592**, changeset_size=160512, timestamp=80999067486)
> error: sync: Sync Connection[55244]: Session[2]: **Bad changeset received: Bad transaction log (message_type='upload')**
> 
> info: sync: Sync Connection[55244]: Session[2]: Session terminated (session_ident=2).
> 
> info: sync: Sync Connection[55244]: Sending: ERROR(error_code=212, message_size=22, try_again=0, session_ident=2)
> 
> info: sync: Sync Connection[55244]: Connection closed by client: End of input
> 
> 

It's happening while device is trying to upload the the data to the ROS, however if we make any change from server it will easily reflect to the client as shown in below logs:

> I/REALM_SYNC: Opening Realm file: /storage/sdcard0/KentTracker/Sync/031a4d341c1f20f57767d7b3386010fe/031a4d341c1f20f57767d7b3386010fe/2056696625/private.realm
> 
> D/REALM_SYNC: Connection[1]: WebSocket::Websocket()
> 
> D/REALM_SYNC: Connection[1]: Reconnecting in 0 milliseconds
> 
> I/REALM_SYNC: Connection[1]: Session[2]: Starting session for '/storage/sdcard0/KentTracker/Sync/031a4d341c1f20f57767d7b3386010fe/031a4d341c1f20f57767d7b3386010fe/2056696625/private.realm'
> 
> D/REALM_SYNC: Connection[1]: Session[2]: last_version_available  = 2053
> 
> D/REALM_SYNC: Connection[1]: Session[2]: progress_server_version = 1801
> 
> D/REALM_SYNC: Connection[1]: Session[2]: progress_client_version = 1763
> 
> D/REALM_SYNC: Using already open Realm file: /storage/sdcard0/KentTracker/Sync/031a4d341c1f20f57767d7b3386010fe/031a4d341c1f20f57767d7b3386010fe/2056696625/private.realm
> 
> D/REALM_SYNC: Connection[1]: Session[2]: Progress handler called, downloaded = 15087, downloadable = 15087, uploaded = 52902327, uploadable = 87819849, progress version = 0, snapshot version = 2053
> 

Other Details:
**private.realm** file size on device: **160 Mb**
**private.realm** file size on server: **104 Mb**

=============>
**Android Version: 3.5.0
Server Version: 1.8.2**


Use case to derive it:
From android device start pushing
Large data like byte array at a time interval of 5 second and starting committing it stop internet connection for some time so that the uploading and uploaded difference reach to large in size. 
start connection again in the mean time delete the files from server also using some other client.

Multiple operation to the same path in a frequent way will cause this easily.

> Please let me know what should I do if I'm facing this issue, so that my application feature does not interrupt with this bad change set.

**Comment by anujjpandey11** [comment]
Team any update..!

**Comment by bigfish24** [comment]
@anujjpandey11 have you made changes to your schema? Can you provide the client side code?

**Comment by anujjpandey11** [comment]
No there is no changes in schema.

**Comment by anujjpandey11** [comment]
Thanks for adding error code in update it will help alot

**Comment by sshakilms** [comment]
getting same error : its  happening on only ReamList<String> 

Schema 
```
    private RealmList<String> specialization;
    private String speciality;
    private RealmList<String> links;
  
```

```
@RealmModule(classes={
        SpecialistEntity.class,
        SpecialtyEntity.class})
public class LoopHealthSchema {
}
```


```
 if (realmSyncConfig == null) {
                    realmSyncConfig = user.createConfiguration(RealmServerConfig.REALM_Common_URL+"realm-admin/loopHealthUser")
                            .schemaVersion(1)
                            .modules(new LoopHealthSchema())
                            .errorHandler((session, error) -> {
                                error.printStackTrace();
                                Timber.e("User error:%s", error.getErrorCode());
                                //EventBus.getDefault().post(new RealmRefreshModel(ChatServer.Realm_Reset_Sync,true,error));
                                //myCustomObject.onObjectError("Realm Error Found");
                            })
                            .build();
                }
                //set Default Instance
                realmConfiguration = realmSyncConfig;
```

SDK - 5.9.0

**Comment by ianpward** [comment]
pretty clear error here -

```
E/REALM_SYNC: Connection[8]: Session[8]: Failed to transform received changeset: Schema mismatch: Property 'specialization' in class 'SpecialistEntity' is nullable on one side and not on the other.
```

you need to fix your schema and get it to match

**Comment by sshakilms** [comment]
private RealmList<String> specialization;   //in java
on Server ther is "String?[]"

this code working till yesterday from today it stop, i just want to know why this happend now ,
and how i can achieve this "String?[]" in Java
