### ISSUE TITLE
ROS Documentation Update: iCloud Auth Setup

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-mobile-platform#238]
If you browse to this page in your documentation: https://realm.io/docs/realm-object-server/#icloud (**Realm Object Server** -> **Access Control** -> **iCloud**)

...the screenshot is out of date. Apple redesign their CloudKit dashboard. 🙂

Thanks!

**Comment by bmunkholm** [comment]
Thanks for that @clifonlabrum!
