### ISSUE TITLE
Need Help, ROS can not start, how to fix it?

### ISSUE THREAD

**Issue by wtlucky** [realm/realm-mobile-platform#241]
## Goals

A running server stopped, I want to start it.

## Expected Results

The dead server started.

## Actual Results

The server can't be started, and after `systemctl status realm-object-server.service`, I got some error log. 

## Version of Realm and Tooling

- Realm Object Server Version:  1.7.2 (not exactly, I have forgot it and can't check it out)
- Flavor:
  - [ ] Developer
- Server OS & Version: Ubuntu 16.04 x64

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
    ● realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: core-dump) since Mon 2017-07-24 04:45:05 UTC; 24min ago
  Process: 2531 ExecStart=/usr/bin/realm-object-server -c /etc/realm/configuration.yml (code=dumped, signal=ABRT)
 Main PID: 2531 (code=dumped, signal=ABRT)

Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:45:05 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Start request repeated too quickly.
Jul 24 04:45:05 shadowsocks systemd[1]: Failed to start Realm Object Server.
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
    -- Logs begin at Mon 2017-07-24 04:38:03 UTC, end at Mon 2017-07-24 05:14:21 UTC. --
Jul 24 04:38:04 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:38:06 shadowsocks realm-object-server[1018]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:38:06 shadowsocks realm-object-server[1018]:   what():  write(): failed: No space left on device
Jul 24 04:38:06 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:38:06 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:38:06 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:38:07 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:38:07 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:38:07 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:38:07 shadowsocks realm-object-server[1168]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:38:07 shadowsocks realm-object-server[1168]:   what():  write(): failed: No space left on device
Jul 24 04:38:08 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:38:08 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:38:08 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:38:08 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:38:08 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:38:08 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:38:08 shadowsocks realm-object-server[1204]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:38:08 shadowsocks realm-object-server[1204]:   what():  write(): failed: No space left on device
Jul 24 04:38:09 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:38:09 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:38:09 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:38:09 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:38:09 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:38:09 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:38:10 shadowsocks realm-object-server[1215]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:38:10 shadowsocks realm-object-server[1215]:   what():  write(): failed: No space left on device
Jul 24 04:38:10 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:38:10 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:38:10 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:38:10 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:38:10 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:38:10 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:38:11 shadowsocks realm-object-server[1246]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:38:11 shadowsocks realm-object-server[1246]:   what():  write(): failed: No space left on device
Jul 24 04:38:11 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:38:11 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:38:11 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:38:11 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:38:11 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:38:11 shadowsocks systemd[1]: realm-object-server.service: Start request repeated too quickly.
Jul 24 04:38:11 shadowsocks systemd[1]: Failed to start Realm Object Server.
Jul 24 04:43:34 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:43:34 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:43:35 shadowsocks realm-object-server[2241]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:43:35 shadowsocks realm-object-server[2241]:   what():  write(): failed: No space left on device
Jul 24 04:43:35 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:43:35 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:43:35 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:43:35 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:43:35 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:43:35 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:43:36 shadowsocks realm-object-server[2252]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:43:36 shadowsocks realm-object-server[2252]:   what():  write(): failed: No space left on device
Jul 24 04:43:36 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:43:36 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:43:36 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:43:36 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:43:36 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:43:36 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:43:37 shadowsocks realm-object-server[2263]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:43:37 shadowsocks realm-object-server[2263]:   what():  write(): failed: No space left on device
Jul 24 04:43:37 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:43:37 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:43:37 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:43:37 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:43:37 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:43:37 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:43:38 shadowsocks realm-object-server[2274]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:43:38 shadowsocks realm-object-server[2274]:   what():  write(): failed: No space left on device
Jul 24 04:43:38 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:43:38 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:43:38 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:43:38 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:43:38 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:43:38 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:43:39 shadowsocks realm-object-server[2285]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:43:39 shadowsocks realm-object-server[2285]:   what():  write(): failed: No space left on device
Jul 24 04:43:39 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:43:39 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:43:39 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:43:39 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:43:39 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:43:39 shadowsocks systemd[1]: realm-object-server.service: Start request repeated too quickly.
Jul 24 04:43:39 shadowsocks systemd[1]: Failed to start Realm Object Server.
Jul 24 04:45:00 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:45:01 shadowsocks realm-object-server[2472]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:45:01 shadowsocks realm-object-server[2472]:   what():  write(): failed: No space left on device
Jul 24 04:45:01 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:45:01 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:45:01 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:45:01 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:45:01 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:45:01 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:45:02 shadowsocks realm-object-server[2488]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:45:02 shadowsocks realm-object-server[2488]:   what():  write(): failed: No space left on device
Jul 24 04:45:02 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:45:02 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:45:02 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:45:02 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:45:02 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:45:02 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:45:03 shadowsocks realm-object-server[2499]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:45:03 shadowsocks realm-object-server[2499]:   what():  write(): failed: No space left on device
Jul 24 04:45:03 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:45:03 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:45:03 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:45:03 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:45:03 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:45:03 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:45:04 shadowsocks realm-object-server[2515]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:45:04 shadowsocks realm-object-server[2515]:   what():  write(): failed: No space left on device
Jul 24 04:45:04 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:45:04 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:45:04 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:45:04 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:45:04 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:45:04 shadowsocks systemd[1]: Started Realm Object Server.
Jul 24 04:45:05 shadowsocks realm-object-server[2531]: terminate called after throwing an instance of 'std::runtime_error'
Jul 24 04:45:05 shadowsocks realm-object-server[2531]:   what():  write(): failed: No space left on device
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Main process exited, code=dumped, status=6/ABRT
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Unit entered failed state.
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Failed with result 'core-dump'.
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Service hold-off time over, scheduling restart.
Jul 24 04:45:05 shadowsocks systemd[1]: Stopped Realm Object Server.
Jul 24 04:45:05 shadowsocks systemd[1]: realm-object-server.service: Start request repeated too quickly.
Jul 24 04:45:05 shadowsocks systemd[1]: Failed to start Realm Object Server.
  </code>
</details>

**Comment by bigfish24** [comment]
The logs say there is not enough space on your server, can you increase the available disk space?

**Comment by wtlucky** [comment]
@bigfish24 Thanks. I checked the server space, you were right.  But I found one of my user_data `/var/lib/realm/object-server/0/user_data/6df9d5df359fa3aa941e29a9c4b04f23` uses 99% of my disk, how can I make it smaller, If I can't increase my server disk space?

**Comment by wtlucky** [comment]
I have deleted the realm file and recreate it.
