### ISSUE TITLE
using RealmList<?> gives Error:Execution failed for task ':app:compileDebugJavaWithJavac'. > java.lang.NullPointerException error

### ISSUE THREAD

**Issue by aalap03** [realm/realm-mobile-platform#242]
I have a realm object class which I update with json response. This is how it looks like I have replies field where I get string responses and what I care about is just their length. So I have stored it this way as list and then use size of it to display in textview. But as I added this code it started giving me the error mentioned in title. I search everywhere and did all the remedies like deleting gradle, updating realm, using multidex etc. nothing worked, then when I comment these lines it worked, then I uncommented these lines to make sure and error appeared again, then commented and error gone. What is the issue related to ? 

    public class MyRealmObject extends RealmObject {
    @PrimaryKey
    String _id;

    //RealmList<?> replies;

    //    public RealmList<?> getReplies() {
    //        return replies;
    //    }
    //
    //    public void setReplies(RealmList<?> replies) {
    //        this.replies = replies;
    //    }

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }
    }

**Comment by zaki50** [comment]
You can't use wildcard(`?`) in model class since Realm's annotation processor need to know which class is the thrget of the list in order to buiold schema from class definition.

We should print error message ibstead of NPE.
