### ISSUE TITLE
Realm Function - “We ran into an issue trying to start User Search” 

### ISSUE THREAD

**Issue by michael-mckenna** [realm/realm-mobile-platform#243]
## Goals

Get a working Realm Function

## Expected Results

To successfully run the function

## Actual Results

After hitting the green Run button for my realm function, in the top right there is a red error message with the shield icon on the left of the message pop up saying “We ran into an issue trying to start User Search”.

## Steps to Reproduce

 A little over a week ago I was working on building a realm function for searching users and it was working well. I was constantly making incremental changes, stopping, saving, and restarting it. Then all of the sudden it just stopped working. Also, at this time, the Logs tab stopped working as well and nothing has been showing there since then.

## Code Sample

https://gist.github.com/michael-mckenna/60825702faf8b3f70b1652a94978ecfe

## Version of Realm and Tooling

- Realm Object Server Version: 1.8.1
- Flavor:
  - [ ] Developer
  - [x ] Professional
  - [ ] Enterprise
- Server OS & Version: CentOS 6

## Logs
As mentioned above, there's absolutely nothing showing up in the Logs anymore. Perhaps items are still being logged but just not showing in the logs tabbed? If so please let me know how to retrieve them.

**Comment by michael-mckenna** [comment]
I fixed this after upgrading to ROS 1.8.2. It happened one more time but was fixed after restarting server. Definitely some sort of bug going on.

**Comment by alebsack** [comment]
Hi @michael-mckenna,

We've released 1.8.3 last week.  In includes some usability and error reporting improvements over both 1.8.2 and 1.8.1.  I've tried your code with this release and was unable to reproduce your issue.

If you try again with 1.8.3, could you please monitor the server log file and send any relevant information to us?
