### ISSUE TITLE
Option to not use memory mapped DB

### ISSUE THREAD

**Issue by Maxxan** [realm/realm-mobile-platform#247]
## Goals

I've got a lot of data due to many users, like 1 TB of data. I would like to use ROS as a syncing backend. It's personal data for each user, for syncing between their devices if they login using tha same account.

## Expected Results
 
No need of 1TB of RAM or swap file, but a lot less memory needed, like 2GB and look up the data when syncing, more like MongoDB or any other NoSQL DB.

I don't need the speed when syncing, I need to handle larger ammount of data due to many users (with 1-2MB data per user), since it's used for syncing between their own devices, like their phone and tablet, not for any real time co-op. Just to have the same data on both devices.

**Comment by simonask** [comment]
Hi @Maxxan!

2GB RAM is a very small amount for a production server handling 1TB databases, even with a relatively light workload. Depending on your usage pattern and number of active users on your system, you might run into serious performance issues long before memory mapping becomes a problem.

That said, Realm Object Server only keeps a limited amount of Realm files concurrently open at any time (depending on the file descriptor limit on your system), so many small Realms of 1-2MB should not be a problem. If you do see an issue with this usage pattern, please do not hesitate to open a bug report. :-)

For reference, there are no current plans to support non-memory-mapped access to Realm files.
