### ISSUE TITLE
ROS2 is crashing intermittently

### ISSUE THREAD

**Issue by misterlib** [realm/realm-mobile-platform#248]
[var-log-realm-object-server-output.txt](https://github.com/realm/realm-mobile-platform/files/1211600/var-log-realm-object-server-output.txt)

## Goals

Just run the server like normal and have it not crash.

## Expected Results

The server runs without crashing.

## Actual Results

Since upgrading to ROS2, every few hours it seems to crash. It just is suddenly unreachable.  When going to the terminal and checking the status, it may say something like it has been active for 1min42sec.

Here is a screenshot of the logs on the server:

https://www.dropbox.com/s/i6g3fozgvx0x1jo/Screenshot%202017-08-09%2006.18.15.png?dl=0

We have encrypted it with the steps from the Realm blog post on using Let's Encrypt.  So we are using 9443, but all these errors are 9080.

## Steps to Reproduce

Just use normally and it will crash.

## Version of Realm and Tooling

- Realm Object Server Version: 2.0.0-rc2
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? CentOS 7 Latest 64 bit (4.9.36-x86_64-linode85)
- Client SDK Version: React Native Realm 0.1.2

## Logs

<details>
  <summary>systemctl status realm-object-server.service</summary>
  <code>
● realm-object-server.service - Realm Object Server
   Loaded: loaded (/etc/systemd/system/realm-object-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-08-09 13:01:34 UTC; 32min ago
 Main PID: 32652 (realm-object-se)
   CGroup: /system.slice/realm-object-server.service
           ├─32652 /usr/lib/realm-object-server-developer/node/bin/node /usr/bin/realm-object-server -c /etc/realm/configuration.yml
           ├─32667 statsd {"flushInterval":10000,"flush":true}
           └─32675 /usr/lib/realm-object-server-developer/node/bin/node /usr/lib/node_modules/realm-object-server-developer/node_modules/realm-functions/lib/wrapp...

Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=9/KILL
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 13:01:35 li1171-59.members.linode.com realm-object-server[32652]: read configuration from /etc/realm/configuration.yml.
  </code>
</details>

<details>
  <summary>sudo journalctl -u realm-object-server.service</summary>
  <code>
-- Logs begin at Tue 2017-08-08 02:22:54 UTC, end at Wed 2017-08-09 13:34:08 UTC. --
Aug 08 02:36:06 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 08 02:36:06 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 08 02:36:07 li1171-59.members.linode.com realm-object-server[4889]: read configuration from /etc/realm/configuration.yml.
Aug 08 03:25:54 li1171-59.members.linode.com systemd[1]: Stopping Realm Object Server...
Aug 08 03:25:54 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 08 03:25:54 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 08 03:25:55 li1171-59.members.linode.com realm-object-server[5777]: read configuration from /etc/realm/configuration.yml.
Aug 08 20:48:32 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=6/ABRT
Aug 08 20:48:32 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 08 20:48:32 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 08 20:48:33 li1171-59.members.linode.com systemd[1]: realm-object-server.service holdoff time over, scheduling restart.
Aug 08 20:48:33 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 08 20:48:33 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 08 20:48:34 li1171-59.members.linode.com realm-object-server[29000]: read configuration from /etc/realm/configuration.yml.
Aug 08 23:23:58 li1171-59.members.linode.com systemd[1]: Stopping Realm Object Server...
Aug 08 23:25:28 li1171-59.members.linode.com systemd[1]: realm-object-server.service stop-sigterm timed out. Killing.
Aug 08 23:25:28 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=9/KILL
Aug 08 23:25:28 li1171-59.members.linode.com systemd[1]: Stopped Realm Object Server.
Aug 08 23:25:28 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 08 23:25:28 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 08 23:25:30 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 08 23:25:30 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 08 23:25:32 li1171-59.members.linode.com realm-object-server[29653]: read configuration from /etc/realm/configuration.yml.
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: Error: not opened
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at WebSocket.send (/usr/lib/node_modules/realm-object-server-developer/node_modules/express-
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at Array.load (/usr/lib/node_modules/realm-object-server-developer/node_modules/realm-browse
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at RealmURLPresenter.resetRealm (/usr/lib/node_modules/realm-object-server-developer/node_mo
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at /usr/lib/node_modules/realm-object-server-developer/node_modules/realm-browser/dist/backe
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at Timeout.setTimeout (/usr/lib/node_modules/realm-object-server-developer/node_modules/real
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at ontimeout (timers.js:386:14)
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at tryOnTimeout (timers.js:250:5)
Aug 09 03:19:25 li1171-59.members.linode.com realm-object-server[29653]: at Timer.listOnTimeout (timers.js:214:5)
Aug 09 03:19:25 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=exited, status=99/n/a
Aug 09 03:19:25 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 03:19:25 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 03:19:25 li1171-59.members.linode.com systemd[1]: realm-object-server.service holdoff time over, scheduling restart.
Aug 09 03:19:25 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 03:19:25 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 03:19:26 li1171-59.members.linode.com realm-object-server[29917]: read configuration from /etc/realm/configuration.yml.
Aug 09 04:33:22 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=9/KILL
Aug 09 04:33:22 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 04:33:22 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 04:33:23 li1171-59.members.linode.com systemd[1]: realm-object-server.service holdoff time over, scheduling restart.
Aug 09 04:33:23 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 04:33:23 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 04:33:24 li1171-59.members.linode.com realm-object-server[30187]: read configuration from /etc/realm/configuration.yml.
Aug 09 04:35:31 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=6/ABRT
Aug 09 04:35:31 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 04:35:31 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 04:35:31 li1171-59.members.linode.com systemd[1]: realm-object-server.service holdoff time over, scheduling restart.
Aug 09 04:35:31 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 04:35:31 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 04:35:33 li1171-59.members.linode.com realm-object-server[30226]: read configuration from /etc/realm/configuration.yml.
Aug 09 04:39:24 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=6/ABRT
Aug 09 04:39:24 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 04:39:24 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 04:39:25 li1171-59.members.linode.com systemd[1]: realm-object-server.service holdoff time over, scheduling restart.
Aug 09 04:39:25 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 04:39:25 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 04:39:26 li1171-59.members.linode.com realm-object-server[30262]: read configuration from /etc/realm/configuration.yml.
Aug 09 04:44:30 li1171-59.members.linode.com systemd[1]: Stopping Realm Object Server...
Aug 09 04:46:00 li1171-59.members.linode.com systemd[1]: realm-object-server.service stop-sigterm timed out. Killing.
Aug 09 04:46:00 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=9/KILL
Aug 09 04:46:00 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 04:46:00 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 04:46:00 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 04:46:00 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 04:46:01 li1171-59.members.linode.com realm-object-server[30336]: read configuration from /etc/realm/configuration.yml.
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: Error: not opened
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at WebSocket.send (/usr/lib/node_modules/realm-object-server-developer/node_modules/express-
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at Array.load (/usr/lib/node_modules/realm-object-server-developer/node_modules/realm-browse
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at RealmURLPresenter.resetRealm (/usr/lib/node_modules/realm-object-server-developer/node_mo
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at /usr/lib/node_modules/realm-object-server-developer/node_modules/realm-browser/dist/backe
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at Timeout.setTimeout (/usr/lib/node_modules/realm-object-server-developer/node_modules/real
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at ontimeout (timers.js:386:14)
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at tryOnTimeout (timers.js:250:5)
Aug 09 12:31:21 li1171-59.members.linode.com realm-object-server[30336]: at Timer.listOnTimeout (timers.js:214:5)
Aug 09 12:31:21 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=exited, status=99/n/a
Aug 09 12:31:21 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 12:31:21 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 12:31:21 li1171-59.members.linode.com systemd[1]: realm-object-server.service holdoff time over, scheduling restart.
Aug 09 12:31:21 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 12:31:21 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 12:31:22 li1171-59.members.linode.com realm-object-server[32467]: read configuration from /etc/realm/configuration.yml.
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: Error: not opened
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at WebSocket.send (/usr/lib/node_modules/realm-object-server-developer/node_modules/express-
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at Array.load (/usr/lib/node_modules/realm-object-server-developer/node_modules/realm-browse
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at RealmURLPresenter.resetRealm (/usr/lib/node_modules/realm-object-server-developer/node_mo
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at /usr/lib/node_modules/realm-object-server-developer/node_modules/realm-browser/dist/backe
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at Timeout.setTimeout (/usr/lib/node_modules/realm-object-server-developer/node_modules/real
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at ontimeout (timers.js:386:14)
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at tryOnTimeout (timers.js:250:5)
Aug 09 12:57:51 li1171-59.members.linode.com realm-object-server[32467]: at Timer.listOnTimeout (timers.js:214:5)
Aug 09 12:57:51 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=exited, status=99/n/a
Aug 09 12:57:51 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 12:57:51 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 12:57:52 li1171-59.members.linode.com systemd[1]: realm-object-server.service holdoff time over, scheduling restart.
Aug 09 12:57:52 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 12:57:52 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 12:57:53 li1171-59.members.linode.com realm-object-server[32596]: read configuration from /etc/realm/configuration.yml.
Aug 09 13:00:04 li1171-59.members.linode.com systemd[1]: Stopping Realm Object Server...
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: realm-object-server.service stop-sigterm timed out. Killing.
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: realm-object-server.service: main process exited, code=killed, status=9/KILL
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: Unit realm-object-server.service entered failed state.
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: realm-object-server.service failed.
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: Started Realm Object Server.
Aug 09 13:01:34 li1171-59.members.linode.com systemd[1]: Starting Realm Object Server...
Aug 09 13:01:35 li1171-59.members.linode.com realm-object-server[32652]: read configuration from /etc/realm/configuration.yml.
  </code>
</details>

<details>
  <summary>cat /var/log/realm-object-server.log</summary>
  <code>
attaching file, too long

  </code>
</details>

**Comment by morten-krogh** [comment]
@misterlib 
Can I ask you to turn on debug level logging and show us those log files?

**Comment by misterlib** [comment]
Yes, for sure. Sorry, I'm a non-technical founder that is trying to limp through this. Can you tell me how to do that?

**Comment by morten-krogh** [comment]
In the configuration file
/etc/realm/configuration.yml
you replace 
## level: 'info'
with 
level: 'debug'

So remove the ## and write debug.

Then you stop the server and start it again.

**Comment by misterlib** [comment]
ok, I did that. Just to clarify, are you asking me to run and upload the log from `cat /var/log/realm-object-server.log` with debug on?

**Comment by morten-krogh** [comment]
Yes, exactly. Run for some time and then upload it.

**Comment by misterlib** [comment]
Ok.  It just recently crashed, so I ran the log again and attached it.
[var-log-realm-object-server-output-with-debug-on.txt](https://github.com/realm/realm-mobile-platform/files/1212166/var-log-realm-object-server-output-with-debug-on.txt)

**Comment by morten-krogh** [comment]
Thanks.
Can you run

journalctl -u realm-object-server.service --no-pager > some-file

and upload some-file?

**Comment by misterlib** [comment]
It wouldn't upload as some-file, so I had to add a .txt.  But here it is: 

[some-file.txt](https://github.com/realm/realm-mobile-platform/files/1212863/some-file.txt)

**Comment by morten-krogh** [comment]
Thanks. 

Yes, some-file was just any file name.

**Comment by morten-krogh** [comment]
@misterlib 
I have found the reason behind the crashes I see in your files.

One issue has already been solved and will be released soon.
The other issue is on the road map to be solved.

You can actually continue running your current system as is. 
The server restarts itself and no data is lost.

**Comment by misterlib** [comment]
Thanks Morten.

The issue actually may be worse though (or perhaps this is a separate issue).

Last night, it did the same thing where it restarted and it is unreachable for a period of time, but it didn't come back online.  When I run `sudo systemctl status realm-object-server`, it says it is loaded and active (for just a few minutes when it has reset). But trying to access it from the browser, from the Realm Browser, in app connections, all of them are unable to connect. Nothing has changed from previous to this happening and now it is just gone. This was last night and to help get it going, I stopped and started it, I rebooted the actual linode it is running on and started it again. I disabled the firewall just in case (which makes no sense because it was working and nothing on the firewall had changed at all), but that obviously didn't do anything. I switched the logging back from `debug` to `info` because you had me change that, so I thought that putting it back and restarting the server might help it be accessible, but it did not.  Everything I have tried is fruitless.  As of right now, I SSH into the server and run the status and it says it has been active for 7 hours. I am still unable to access it in any way.

I have no idea what to do. Development has been begrudgingly extended to help account for this shift to 2.0 and as of now, it is halted right at the time we should be wrapping everything up.

So here is my response to your last message:

When you say that the other issue has already been solve and will be released soon, what does that mean? We are building a time based app that centers around the start of school in the US. (that is today for some school districts and continues to increase every single day) If soon means weeks, I am going to go into full panic mode.

When you say that the other issue is on the road map to be solved, it sounds like code for: this won't be solved in the foreseeable future, so this issue will persist and the server will continue to be unreachable intermittently throughout the day as well as the possibility of what is currently happening where it is completely unreachable and even restarting it won't help for what could be even a few more months. (Please assure me that this either is or is not what you are saying.)

I have more to say, but I'll just DM it to you because it is more personal than about this issue.
