### ISSUE TITLE
Realm Browser doesn't connect to Azure 

### ISSUE THREAD

**Issue by ajonno** [realm/realm-mobile-platform#249]
## Goals

Test Realm on Azure

## Expected Results

Be able to login and use the Realm Browser app on Mac

## Actual Results

Failed

## Steps to Reproduce

MacBook Pro (Retina, 15-inch, Late 2013)
Mac OS Sierra
10.12.5
Chrome - Version 60.0.3112.90 (Official Build) (64-bit)

## Code Sample
Didn't make it that far

## Version of Realm and Tooling

- Realm Object Server Version:  Whatever version of ROS you currently make available on Azure
- Flavor:
  - [X ] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: ? using the default setup for Realm on Azure. Just using defaults.
- Client SDK Version: ?
- Client OS & Version: ?

Screenshots attached
![image](https://user-images.githubusercontent.com/3005269/29203447-361bc590-7eb4-11e7-9ef8-3d4f1a0be10c.png)
![image](https://user-images.githubusercontent.com/3005269/29203453-3ca60f9c-7eb4-11e7-9189-e35824a6736c.png)

**Comment by stel** [comment]
What version of Realm Browser do you use? Please make sure you use the latest one (2.1.12).

**Comment by ajonno** [comment]
confirmed im using 2.1.12

same error. happy to provide you IP address / login details via email if you want to try

**Comment by bigfish24** [comment]
@ajonno is this still a problem? Note I updated the Azure image to 1.8.3 last week.

**Comment by ajonno** [comment]
Thanks Adam. I ran an instance on Digital Ocean after I couldn’t get this working on Azure. If you think this has been resolved via 1.8.3 on Azure feel free to close the ticket.

Cheers
Angus
