### ISSUE TITLE
ONLINE-first 

### ISSUE THREAD

**Issue by adamsmaka** [realm/realm-mobile-platform#253]
I know that Realm is proud of offline-first database access, but sometimes I have to check if something is in Server database. When I drop filter query on the first launch of the app, before Realm gets sync it returns empty results. How to force the query to access only data on a server or not at all?

If it helps, my case is that I want to check in common realm if a username is available. I want to provide a unique username for each user.

**Comment by nirinchev** [comment]
Depending on your app's logic, you could asynchronously open the Realm which will download all data from the server before invoking its callback. Which SDK are you using on the client?

**Comment by adamsmaka** [comment]
Hmm that's interesting. I'm using Swift.

**Comment by nirinchev** [comment]
In that case you could use [`Realm.asyncOpen`](https://realm.io/docs/swift/latest/#asynchronously-opening-realms) to open and download the latest state of the Realm. If you have the Realm already opened and want to make sure there are no outstanding changes from the server, you could call [`session.addProgressNotification(for .download, mode .forCurrentlyOutstandingWork`](https://realm.io/docs/swift/latest/#progress-notifications) to ensure your local Realm is up to date.

**Comment by adamsmaka** [comment]
thank you! it works! sorry for newbie question. we can close it.

**Comment by nirinchev** [comment]
No worries, glad to be of help!
