### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by tpedersen123** [realm/realm-mobile-platform#26]
Are there any plans to support Realm Mobile Platform in React Native (RN)?

I'm aware that we can use the mobile platform using native modules in RN, but would like to know whether Realms has plans to implement RN support.

**Comment by alazier** [comment]
This is currently in the works. Should have more news in the coming days/weeks.

**Comment by netspencer** [comment]
@alazier any updates on the timeline?

**Comment by alazier** [comment]
We have things working for iOS but still have issues with chrome debugging support and android. We don't yet have a definitive timeline.

**Comment by marstall** [comment]
starting a new react-native project and would love to base it on realm mobile - what's the best way to get notified when this is released?

**Comment by bmunkholm** [comment]
We will announce that in this issue - so subscribing to this should do it.

**Comment by iZaL** [comment]
like @marstall I too planning to build my next react-native project on realm. when can we expect the feature to be available ?

**Comment by bmunkholm** [comment]
We really try our best to not make specific promises on release dates :-) It limits our ability to be agile :-) That said we are pretty close, so _right now_ I wouldn't be surprised if it's available before end of next month.

**Comment by joshuapinter** [comment]
Would love to have this as well. Is there a branch I can help test for you guys?

I have an existing react native app that is currently only locally stored via Realm and I'm looking to add data back and multiple device synchronizations across multiple platforms, including iOS, Android and MacOS. 

Let me know. 

Thanks.

**Comment by crazydavy** [comment]
Ditto on the testing. I have an app in the store, and the #1 request is syncing between devices.  Would love to get coding.

**Comment by kristiandupont** [comment]
The prerelease is up for anyone who wants to try things out:
https://github.com/realm/realm-js/releases/tag/0.15.5-rmp-beta.1

​You can download the file and install it by simply using "npm install --save path/to/realm-0.15.5-rmp-beta.1.tgz"
​You can then open a synchronized realm with the api described here: https://realm.io/docs/realm-object-server/#user-based -- make sure you download the Realm Object Server to play with (Click "Download developer edition" in the Realm Mobile Platform section of http://realm.io).
​
​Please let me know if you run into issues

**Comment by joshuapinter** [comment]
FYI, you can just add this to your `package.json` file: 

`"realm": "realm/realm-js#0.15.5-rmp-beta.1"`

Then doing a `npm install` will get the beta version.

No need to download it separately.

**Comment by teotwaki** [comment]
This was released.
