### ISSUE TITLE
asyncOpen callback never called when offline 

### ISSUE THREAD

**Issue by ewerx** [realm/realm-mobile-platform#260]
## Goals

App waits for sync realm to be open at app launch before presenting UI by using asyncOpen() and waiting for callback. 

## Expected Results

asyncOpen callback is called every time asyncOpen is called, with either an error or valid realm.

## Actual Results

When there is no network connection (airplane mode) and using a previously-authenticated SyncUser the callback is never triggered.

## Steps to Reproduce

Authenticate a user to connect to the sync realm so that the authenticated user is stored in SyncUser.current. Launch the app with no network connection (airplane mode), setup the Realm configuration using the SyncUser.current user and then call Realm.asyncOpen(callback: {...}) and wait for the callback.

## Code Sample

```swift
if let user = SyncUser.current {
    let config = Realm.Configuration(syncConfiguration: SyncConfiguration(user: user, realmURL: syncRealmURL))
    Realm.asyncOpen(configuration: config) { realm, error in
        print("asyncOpen result: \(error)") // this is never called
}
```

## Version of Realm and Tooling

- Realm Object Server Version: v1.8.3
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: Ubuntu 16.04
- Client SDK Version: v2.10.0
- Client OS & Version: iOS 10.3.3

## Logs

Client outputs this when asyncOpen is called while disconnected:

`error in connection_block_invoke_2: Connection interrupted`

**Comment by ewerx** [comment]
Related? https://github.com/realm/realm-cocoa/issues/5186

**Comment by ewerx** [comment]
I have worked around this issue by adding a timeout so the UI is not blocked waiting for asyncOpen to return. If this is the expected behaviour of asyncOpen this issue can be closed.

**Comment by bmunkholm** [comment]
@bdash Can you comment on this?

**Comment by bdash** [comment]
This is the same issue as realm/realm-cocoa#5186. While it talks about read-only Realms, there's nothing specific to read-only Realms in how `asyncOpen` works. Let's continue to track this via the realm-cocoa issue for now.
