### ISSUE TITLE
Realm Files are Kinda Fat

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-mobile-platform#262]
_ROS 2.0.0b-rc285, Realm 3.0.0-beta-2_

I'm not really sure which Realm repository to use when reporting this, but since I'm heavily reliant on the Realm Object Server, I'll put it here.

I have been migrating from an SQLite solution to Realm over the past year, and one thing has me worried.

I took a user's SQLite database and migrated it into a corresponding Realm (with similar data structure). The **SQLite database is a mere 821KB** and the **Realm file is 469.8MB**.
![realm-vs-sqlite](https://user-images.githubusercontent.com/2513753/29957201-f8bfb204-8ea0-11e7-8a84-1b01de073842.png)

I imagine the Realm file has lots of magic built into it for syncing, but a 500X increase? This makes hosting super expensive. If I have 1000 users with an average Realm size of 500MB, I'd need a 500GB VPS. That would be outrageously expensive for a relatively small number of users.

I sure hope I'm doing something wrong because I don't feel like I'm storing a crazy amount of data. Here's a view of the Realm opened up:
<img width="2178" alt="realm-sample" src="https://user-images.githubusercontent.com/2513753/29957299-95c9535c-8ea1-11e7-8611-45f0a1c762d9.png">

Any ideas?

**Comment by Maxxan** [comment]
The big problem with ROS (at least 1.x, probably 2.x) as I've understood it, is that is saves every single operation since day one (so every insertion, deletion, rearrange, setting value etc). So compared to a "normal" database where the data is replaces with the latest version, Realm online database with just keep growing and growing. Especially realm lists seems to grow quickly.

**Comment by bigfish24** [comment]
The 2.0 version you are using doesn't have log compaction yet. This should be addressed by that in upcoming versions.

**Comment by cliftonlabrum** [comment]
That's good to know. Thanks, @bigfish24. Do you have any examples to set my expectations? Such as... a `100 MB` database before compaction would become about a `X MB` database after, etc.?

**Comment by bigfish24** [comment]
We have been seeing 80% reductions but obviously usage varies since compaction doesn't apply to some operations.

**Comment by cliftonlabrum** [comment]
Okay, great. Thanks.

I'll close this and anticipate compaction in a future version.

**Comment by Maxxan** [comment]
Will the compact functionality be in the release version of ROS 2.0 or in a
later version?

**Comment by bigfish24** [comment]
It will be in 2.0
