### ISSUE TITLE
How to not sync certain objects?

### ISSUE THREAD

**Issue by ekimia** [realm/realm-mobile-platform#263]
Device specific object that should be persisted only in the local realm.

For example, I have an image snapshot of a dashboard. That snapshot is only meant to reflect the current user's last state when viewing a dashboard. Therefore, I don't want other users to see it.

**Comment by Maxxan** [comment]
I think that you will need to use one realm for shared data and one realm for their personal state.

**Comment by ekimia** [comment]
thanks!
