### ISSUE TITLE
Help me with the SetupRealm()

### ISSUE THREAD

**Issue by EmysDanny** [realm/realm-mobile-platform#265]
Hello i have a problem with using a realm. When running the program that i copied from https://realm.io/docs/tutorials/realmtasks/#create-a-new-xcode-project
i can't run it. When i run it, suddenly the func setupRealm()  became error
i don't know what supposed to write in this code about the username and the password
![snip20170908_3](https://user-images.githubusercontent.com/31758739/30199184-c77df01a-949b-11e7-8038-a4c04c13b0bb.png)

so when i run it, the error is = 

![snip20170908_4](https://user-images.githubusercontent.com/31758739/30199207-e02050fe-949b-11e7-815e-2c7f7b8bb59c.png)

**Comment by DavidOliverDoswell** [comment]
Hi, EmysDanny 

Enter the username and password you used when you first downloaded the Realm Object Server (ROS) in the Getting Started section. You should already have the ROS running. The ROS expects the values from your Mac or iOS client to match those server-side. If you've forgotten these values, delete the admin user from the ROS (again, assuming you're logged in) and sign up again as a new user, remember them, and `let username = "ROS username"`, `let password = "ROS password"`
