### ISSUE TITLE
Web interface is caching too aggressively (thinks I'm logged in)

### ISSUE THREAD

**Issue by Dids** [realm/realm-mobile-platform#268]
## Goals

I'm trying to use the web interface to do diagnostics and maintenance every now and again.

## Expected Results

Realm Object Server's web interface should properly show the login screen when I'm not logged in or when my session has expired, ignoring any cached data.

## Actual Results

Realm Object Server's web interface thinks I'm logged in, allowing me to click around, although some elements aren't always loading, while some are.

When I forcefully refresh the page, I get a JSON error saying "permission denied", but again, I'm not redirected to the login page as one would expect.
The only way to login again is to go to the root url, click "Logout" and then I'm shown the login form again.

From what I can tell, the web app is caching too heavily and relying on the cache at all times, which makes me (and probably others) think they're logged in already, even though their session has clearly expired.

## Steps to Reproduce

Login, wait until your session expires (no idea how long this is set to, but waiting for 24 hours seems to do the trick at least), and try opening the web interface again. Whether you open the root url or not doesn't seem to make a difference.

## Version of Realm and Tooling

- Realm Object Server Version: v1.8.3-83
- Flavor:
  - [x] Developer
  - [ ] Professional
  - [ ] Enterprise
- Server OS & Version: Ubuntu 16.04
- Client SDK Version: N/A
- Client OS & Version: macOS Sierra 10.12.6 and Safari 11.0

**Comment by morten-krogh** [comment]
Thanks for reporting the issue.
We will soon release a new, and better, UI for the Realm Object Server.
We will not fix the issue with the current web interface.
I will close this issue since it will (hopefully) be resolved by the new UI.
If the problem still persists, we can open a new issue.
