### ISSUE TITLE
Memory is increase when add multi row to realm

### ISSUE THREAD

**Issue by hoathuongphuoc** [realm/realm-mobile-platform#269]
Hi all, I have 1 issues about add object to realm. So, i have data about 40000 records and i need to add it to realm but i try to use for loop to add it, so memory in app is increase so much. Everybody have another solution can help me. Thanks so much. This my source.

```
func savePlaceInfoList(placeInfoList: [PlaceInfo], productType: Int){
       let mRealm = try! Realm()
        try! mRealm.write {
            for item in placeInfoList{
                item.mProductType = productType
                let placeRealm = PlaceRealm()
                placeRealm.addPlace(placeInfo: item )
                mRealm.add(placeRealm)
            }
        }
    }
```

**Comment by bmunkholm** [comment]
Hi @hoathuongphuoc!
I suggest you make multiple commits (writes) instead of one big of 40000. E.g. make a write for every 500 objects.

**Comment by hoathuongphuoc** [comment]
Thanks bmunkholm.
