### ISSUE TITLE
"Realtime Collaboration, Now For Every Mobile Developer" - Java 

### ISSUE THREAD

**Issue by nishanthvasu** [realm/realm-mobile-platform#271]
@bmunkholm Thanks for the info Dude!! 

As per the answer from you, I cant find any Java or Android Demo's present in this link "**https://github.com/realm-demos**". All Demos are related to swift,objective C only mostly. So i am looking for a demo with **Java or Android** for "**Realtime Collaboration, Now For Every Mobile Developer" .**

Thanks,

**Comment by bmunkholm** [comment]
How about this from the Docs?
https://realm.io/docs/get-started/android-demo-app/
