### ISSUE TITLE
Realm Partial Sync question : are links recursively Eagerly synced to local Realm? 

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-mobile-platform#279]
I'm asking this to answer https://stackoverflow.com/questions/46509810/realm-mobile-platform-architecture-thousands-of-realms-vs-big-realm-files/46836088?noredirect=1#comment80695018_46836088

If you define a relation from one object to another (object / list), then if you subscribe to an object by results of partial sync query, all its linked objects and relations are synchronized down with it, correct?

**Comment by nirinchev** [comment]
Yes, the entire object graph is synchronized eagerly at the moment. With a future release we'll provide API for more fine gained control.

**Comment by Zhuinden** [comment]
Figured that's the only possible way the API could work, thanks :smile:
