### ISSUE TITLE
Module version mismatch. Expected 48, got 46

### ISSUE THREAD

**Issue by ArifADS** [realm/realm-mobile-platform#31]
I get the error Module version mismatch. Expected 48, got 46 when trying to run realm-object-server, I'm on Node.js v6.9.1 and Ubuntu 16.04.1 LTS on AWS

Edit: Showing Complete error log with backtrace
```

/usr/lib/nodejs/realm-object-server/node_modules/realm-sync-server/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/lib/nodejs/realm-object-server/node_modules/realm-sync-server/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/nodejs/realm-object-server/node_modules/realm-sync-server/index.js:34:54)
    at Module._compile (module.js:570:32)

```

**Comment by alebsack** [comment]
Hi @ArifADS,

Thank you for the report.  We've also seen this when the system has another version of Nodejs installed.  Currently, we are only supporting nodejs 4.x, which is a dependency of the packages we distribute.  We have a fix in our latest packages (1.0.0-BETA-2.3, released yesterday), which will forcibly use the proper Nodejs version.  Please try upgrading and let us know if you continue to see this error.

**Comment by ArifADS** [comment]
I'm using that version actually, installed yesterday. I could downgrade the Node version, or want me to test another version?

**Comment by alebsack** [comment]
I guess it depends on how you installed nodejs 6.  If you've overwritten `/usr/bin/nodejs`, then you'll have to reinstall the nodejs package that realm-object-server depends on:

```
apt-get install nodejs=4.2.6~dfsg-1ubuntu4.1
```

We'll create an issue on our end that should help prevent this problem in the next release.

**Comment by teotwaki** [comment]
We have landed a patch for this, it should be available soon (meaning, you shouldn't hit this any more).

Please let us know if you encounter this after the next version is released.
