### ISSUE TITLE
Synchronization over Bluetooth

### ISSUE THREAD

**Issue by virl** [realm/realm-mobile-platform#34]
Greetings!

I'm developing Bluetooth networking library for iOS+Android called [Underdark](http://underdark.io) and would like to integrate it with Realm Mobile platform, so client devices will be able to sync not only with server, but with each other too.

What is the best or easiest way to do that?

**Comment by bmunkholm** [comment]
Hey @virl!
Peer-to-peer sync is a very interesting use case that we would love to support at some point further out. It is also not something you would be able to build yourself on top of what we have at the moment. Sorry to disappoint you here.

**Comment by doovers** [comment]
@bmunkholm Also very interested in the peer to peer use case for offline capabilities. Is there any update on this a year since this question was originally posted?

**Comment by bmunkholm** [comment]
@doovers Unfortunately it's not something we have explored further. We have been way too busy with other priorities. Would love to be able to do it all if we had unlimited resources :-)

**Comment by doovers** [comment]
@bmunkholm Thanks for the update!

**Comment by bmunkholm** [comment]
Your welcome - sorry it wasn't better :-)

**Comment by lucasgerard** [comment]
Hey! Interested in the peer-to-peer sync as well :) does anyone implemented its own approach? Thanks!

**Comment by brendand** [comment]
Any movement on peer-to-peer sync for Realm databases in 2020?

**Comment by bmunkholm** [comment]
I'm sorry, but this is not in our plans atm.

**Comment by ianpward** [comment]
Hey @brendand if you could please make a feature request at https://feedback.mongodb.com/ we will be sure to review it at our quarterly roadmap planning
