### ISSUE TITLE
Non-admin user can read __admin by default

### ISSUE THREAD

**Issue by TotemChris** [realm/realm-mobile-platform#39]
That probably shouldn't be the case.  Anybody that knew 9080 or 9443 was Realm, and had valid creds, could enumerate the ROS pretty easily at that point.

I was able to fix this by manually removing the nil - __admin - mayRead permission.

**Comment by mrackwitz** [comment]
In fact non-admin users are unable to read the admin-Realm by default. But there is a big pitfall: once you access the admin-Realm via a user with administrative privileges (≠ admin token), it will lazily create a `RealmFile` in the admin-Realm, which will default to have read-only default permissions. We'll fix that.

**Comment by TotemChris** [comment]
Ok thanks.  I will use token creds for now to prevent messing up the defaults.

**Comment by mrackwitz** [comment]
This should be solved with the latest release. The admin-Realm is now eagerly tracked by a `RealmFile` in itself.
