### ISSUE TITLE
Syncing data across users

### ISSUE THREAD

**Issue by mikalackis** [realm/realm-mobile-platform#42]
I'm having problems understanding how the sync mechanism is intended to work for different users. I'm confused on how should I create a realm database that would be in sync with two different users. The Realm mobile platform docs says this about the URL:
String serverURL = "realm://my.realm-server.com/~/default";

According to the docs, ~ is optional. If it is present, it will be replaced by users identifier meaning that every user would have its own realm database. When I do this with two different users, the database is not synced (which makes sense) because there are 2 different realms. So my question is, how should I setup my realm so that I have one realm database that is synced between 2 (or more) different users? The only case I managed to make it sync is when I would use one same user on two different devices. 

I also tried constructing a realm url without ~ sign but then I get this:
REALM_JAVA: AuthenticateResponse. Error The path is invalid or current user has no access!

Can someone help me out understanding this please?

**Comment by teotwaki** [comment]
Hi @mikalackis,

This is pretty high on our priority list. We should be able to get you an answer ASAP (probably later this week). We have some stuff cooking for this exact use-case.

**Comment by OMGBrains** [comment]
I've been working on a project that requires a use case very much like this.  I have an app that offers up a good number of available datasets, conditionally synced to a variable number of users.  They are conditionally offered as needed for each user, and it also helps to cut down on the sheer volume of data (~200 unique available datasets, approx. 10MB a piece, typical user may 'subscribe' to 5 or so at a time).  A simple analogy would be sharing eBooks to multiple users, with revisions being pushed from the publisher.  These would be adjacent to a standard bidirectionally synced Realm for everything else.

My current thought is to publish those 200 or so Realms and simply download the files as needed, operating on them as local Realms.  Keeping them all up to date becomes a bit of a challenge though.  This is the model I use today with sqlite, and while it works, Realm would be better :)

If you have some work happening towards conditional access to shared synced Realms, that is quite exciting.  Looking forward to anything that comes available.  Having conditional access to shared Realms opens up a LOT of great options.

**Comment by bmunkholm** [comment]
Handling permissions is now available: https://realm.io/news/realtime-collaboration-now-for-every-mobile-developer/
