### ISSUE TITLE
Migrating from Parse.com

### ISSUE THREAD

**Issue by Den-Ree** [realm/realm-mobile-platform#47]
Hi! I want to migrate on realm DB and platform, but now my app use backend on Parse.com. How can I migrate on realm-server?

**Comment by cliftonlabrum** [comment]
There isn't going to be an automated way to do this. I think you should write some code that does a conversion. Pull all your Parse objects down and save them to Realm objects (one at a time, on a background thread, if available). It should be pretty straight forward.

**Comment by Den-Ree** [comment]
@cliftonlabrum thanks for your answer. So if I have on parse server - registered users and paid content, which I can add from dashboard, I should change my DB on device and create realm users instead of parse users. But, one thing is still not clear, how can I add content on realm server for all users?

**Comment by cliftonlabrum** [comment]
Yes, that's right. You might approach it this way:

1. As users get into the app, use their email to create a Realm username and prompt them to set a new password. You would then create a new user on the Realm Object Server with that info.
2. Migrate the user's data to their personal Realm.
3. Disable their access to the Parse data and use Realm going forward.

As far as shared data, I've read about the ability to share Realms, but I've never tried it. Realm data can only be added via the API. There is no way to add it via the Realm Object Server's web interface.

If you need to be able to view and manage shared data via the web, you might be better off migrating to a self-hosted version of Parse, [or one of its alternatives](https://www.raywenderlich.com/126098/top-5-parse-alternatives).

**Comment by Den-Ree** [comment]
@cliftonlabrum  Thanks for  your help. I understood.
