### ISSUE TITLE
Share sync realms between users

### ISSUE THREAD

**Issue by KieranLaffertySC** [realm/realm-mobile-platform#52]
Hey there,

For some reason using Object Server after authenticating I get a unique db for each individual user.

Example

static NSString * const kDefaultAuthURL = @"http://10.0.1.6:9080/";
static NSString * const kDefaultRealmURL = @"realm://10.0.1.6:9080/default";

After authenticating using 2 different users on http://10.0.1.6:9080/ I open the endpoint using Realm Browser and have 2 databases created:

http://10.0.1.6:9080/b9a277419ccc5f4386e2ea590e63e9a3/default
http://10.0.1.6:9080/a508bdfbd6716c751c3cf1144e1e6c81/default

The hashes in the urls above correspond to the syncUserID's for each user. My expectation was that all users would share a sync realm that could be used to share data between users. Am I missing something?

**Comment by mtrossbach** [comment]
I think this the same question as in (or is related to) #42 - Syncing data across users

**Comment by rishabhparikh** [comment]
I believe the point of the mobile platform as a sync server is to have user data backed up on a server in realtime. This allows users to access the same data consistently across multiple devices, but doesn't mean that users will be able to share the same realm. Not sure if Realm is planning to support this in the future, but ATM I don't think it's possible.

**Comment by KevinVitale** [comment]
I less than a day into Realm (first-time); I'm confused with how Realm is supposed to support "real-time collaboration" if realms are just _per-user_. Maybe I misunderstood what Realm is supposed to be providing — I thought it [was similar to a Firebase-type service](https://www.reddit.com/r/Firebase/comments/55ozf0/realm_mobile_platform_vs_firebase/d8e4lxc/), but with on-premise benefits.

I have the Object Server installed via Docker (Ubuntu 16.04). I'm using RealmSwift 2.1.0.

**Comment by KieranLaffertySC** [comment]
+1 also thought this was a better alternative to firebase

**Comment by bmunkholm** [comment]
You will certainly be able to share Realms between different users shortly
(roughly a week or so)!

**Comment by KevinVitale** [comment]
@bmunkholm: thanks for the quick response! I'm evaluating deps for a new project; if it's going to be a week, I can wait.

 Realm has had my attn for awhile, but the Object Server really has me intrigued. To you & and the rest of the team: keep up the great work.

**Comment by fpatelm** [comment]
Hello,

Is there any news if the feature in which "multiple users have access to the same sync realm object" is available?

**Comment by fpatelm** [comment]
this feature will be available in Developer Edition?

**Comment by bmunkholm** [comment]
Yes it's now available in the Developer Edition: https://realm.io/news/realtime-collaboration-now-for-every-mobile-developer/

**Comment by fpatelm** [comment]
Is there any code example for global realm shared among all users?

**Comment by i-schuetz** [comment]
@fpatelm @bmunkholm 

A bit late - was looking into this too and here are some demos: https://realm.io/docs/demo-apps/

I'm a bit confused about which ones include this feature (by looking at the descriptions), as e.g. RealmTasks is described as collaborative but last time I used this it seemed to only sync for the same user... and e.g. CrowdCircle, which is a team game doesn't have "collaboration" in it. Maybe I'm understanding this word incorrectly. Is this the case, or are these descriptions inaccurate?

**Comment by Jonsapps** [comment]
We've been using shared Realms since we starting using ROS. When you specify the Realm path just use a common name for all clients.

For instance realm://server.com:9080/*/RealmData will connect to a user specific realm (the * is replaced by the users id automatically in ROS)

We use something along the lines of realm://server.com:9080/common/RealmData the * is replaced by the name of the shared Realm.

You can then grant permissions for all users to have read/write access.

**Comment by i-schuetz** [comment]
@Jonsapps thanks for the infos! I had a different use case in mind though - when a user decides to share their database with other specific users (which would have to happen via invitations, I guess).
