### ISSUE TITLE
SyncCredentials(accessToken:identity:) ignoring `identity`?

### ISSUE THREAD

**Issue by KevinVitale** [realm/realm-mobile-platform#54]
Just started kicking the tires on Realm.

After [getting an `accessToken`](https://realm.io/docs/realm-object-server/#the-realm-browser), I saw the `SyncCredentials` API. Being unsure what to put in for `identity`, I started with an empty string and it worked. 

Seemingly I can put whatever value I'd like into `accessToken:identity:` — what's `identity`? and is this expected behavior?

---
```swift
let syncURL = URL(string: "http://localhost:32768")!
let creds = SyncCredentials.accessToken(accessToken, identity: "")
SyncUser.logIn(with: creds, server: syncURL) {
    if let user = $0.0 {
        dump(user)
        dump("Identity: \(user.identity)")
    }
}
```
---
```
- <RLMSyncUser: 0x78630450> #0
  - super: NSObject
- "Identity: Optional(\"\")"
```

**Comment by stel** [comment]
The `identity` is the unique Realm Object Server user ID string identifying the user. Identity is generated by the Object Server when creating a new user, but in case of `accessToken` authentication you need to specify it manually. It can be any string and you can also use it to get a valid sync user from `SyncUser.all` dictionary across application launches.
