### ISSUE TITLE
Xcode Playground support: Keychain returned unexpected status code: -34018

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-mobile-platform#57]
Hi,

thanks for creating such an awesome product!

I've been using Realm a while and have created and managed many of my local realms from within Xcode playgrounds. When using Realm Object Server, however, a call to `SyncUser.all()` results in this error:
`libc++abi.dylib: terminating with uncaught exception of type realm::keychain::KeychainAccessException: Keychain returned unexpected status code: -34018`

Would it be possible to remove the requirement on Keychain access and allow this (wonderful) use case?

regards,

Daniel

**Comment by jpsim** [comment]
It'd be very easy to use our existing `RLMIsInPlayground()` check to disable metadata encryption. Thanks for reporting this!
