### ISSUE TITLE
Unable to use Node.js to connect to Realm Object Server

### ISSUE THREAD

**Issue by mseijas** [realm/realm-mobile-platform#60]
According to the documentation, we can access the Realm Object Server via Node.js through the following way:

```
let admin_user = Realm.Sync.User.adminUser('http://object-server-url:9080/', admin_token);
var realm = new Realm({
    sync: {
        user: admin_user, 
        url: 'realm://object-server-url:9080/~/my-realm'
    }, 
    schema: [{...}
    }]
});
```

However, attempting to do so returns the following error:

```
let admin_user = Realm.Sync.User.adminUser('http://localhost:9080/', admin_token);
                           ^

TypeError: Cannot read property 'User' of undefined
```

It looks as if the `Sync` object has not been defined. I've already made that npm has successfully installed Realm on my machine, so I'm not entirely sure where is this coming from, or if there is an additional dependency that we need to install?

**Comment by bigfish24** [comment]
The Node.js SDK available publicly does not support synchronized Realms. This is only available as part of our enterprise edition. Feel free to reach out to Ian.ward@realm.io if you would like to evaluate it.

**Comment by mseijas** [comment]
Ah, ok. That would make sense then. I'll make sure to reach out again to Ian to see if I can get access to the enterprise edition. Thanks!
