### ISSUE TITLE
Feature: method to abandon data upon non-additive change to model

### ISSUE THREAD

**Issue by dsjstc** [realm/realm-mobile-platform#61]
[As discussed here](http://stackoverflow.com/questions/40877811/synchronized-realm-how-to-deal-with-non-additive-migration?noredirect=1#comment69006219_40877811), if your model changes in a non-additive way, it appears that you have to manually delete your realm files (presumably with the commandline and root access on the server, and adb shell on the various clients).

In a development/test environment, there's probably no need to preserve the contents of the realm.

It'd be very nice if there were _something_ streamlined to replace the functionality that non-synchronized  realms have with `deleteIfMigrationNeeded`.

**Comment by bigfish24** [comment]
Great feedback and that's a use-case we should support. Can't say yet on when we can deliver, but will put it on the roadmap.

**Comment by gritzko** [comment]
Fixed in newer ROS releases.
