### ISSUE TITLE
Property cannot be marked dynamic because its type cannot be represented in Objective-C

### ISSUE THREAD

**Issue by SureshSc** [realm/realm-mobile-platform#63]
Hi 

I am trying to implement below scenario, but i am facing the issue 

```
class CommentsModel: Object {
  dynamic var commentId = ""
  dynamic var ownerId: UserModel?
  dynamic var treeLevel = 0
  dynamic var message = ""
  dynamic var modifiedTs = NSDate()
  dynamic var createdTs = NSDate()

 //facing issue here 
 dynamic var childComments = List<CommentsModel>()
}

```
I have a comments model which has non optional properties in which childComments is List of same Comments model class. In this when i declare  `dynamic var childComments = List<CommentsModel>()` **it shows me Property cannot be marked dynamic because its type cannot be represented in Objective-C.** 

Please help me how to achieve my requirement

**Comment by jpsim** [comment]
List properties cannot be marked as `dynamic` and should be marked as `let` instead of `var`. See our [Swift docs on Models](https://realm.io/docs/swift/latest/#models) for details.

**Comment by SureshSc** [comment]
Sorry, Now i changed to `let` from `dynamic`. Now i am facing the same issue 

Code 

`class CommentsModel: Object { 
  dynamic var commentId = ""
  dynamic var postId = ""
  dynamic var ownerId: UserModel?
  let childComments: List<CommentsModel>()
  dynamic var type = ""
  dynamic var treeLevel = 0
  dynamic var message = ""
  dynamic var modifiedTs = NSDate()
  dynamic var createdTs = NSDate()
}`
<img width="718" alt="screen shot 2016-12-02 at 12 08 45 pm" src="https://cloud.githubusercontent.com/assets/5052940/20825188/6b94112a-b888-11e6-9471-b723edf95232.png">

I am attaching my code as screen shot as well

**Comment by jpsim** [comment]
```swift
let childComments = List<CommentsModel>()
```

**Comment by SureshSc** [comment]
@jpsim I didnt notice the syntax properly. Thank you once again

**Comment by RajIET** [comment]
Same error come for me and I am using Double property.

**Comment by florianthompson** [comment]
@RajIET I know this is late but for everyone else interested.
We can't make it an optional Double.
Instead initialize them with a value -1 or 0.

**Comment by NabinRai4017** [comment]
![screen shot 2018-01-09 at 12 09 45 pm](https://user-images.githubusercontent.com/28722125/34707533-34b1c80a-f536-11e7-8cc4-638f536942f4.png)
I'm having this issue. what is it? somebody help me!!

**Comment by pipemontoya** [comment]
Could you solve the issue?
