### ISSUE TITLE
Can anyone get the Realm Object Server to run on Ubuntu?

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-mobile-platform#7]
I had a smooth experience installing the ROS on a new Digital Ocean Droplet running Ubuntu 16.04. But I'm unsure how to configure the server so I can view the ROS dashboard on the web.

Does someone have a functioning `configuration.yml` file they could share for an Ubuntu installation?

**Comment by cliftonlabrum** [comment]
I finally got it to work temporarily by editing these lines:

```
root_path: '/var/realm'
#...
public_key_path: '/etc/realm/token-signature.pub'
private_key_path: '/etc/realm/token-signature.key'
```
But now when I run `realm-object-server --configuration /etc/realm/configuration.yml` I get the following error:

```
info: Logging to console at level 'info'.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not create a listening socket: All endpoints failed
Aborted (core dumped)
```

**Comment by cliftonlabrum** [comment]
So I started a new Droplet on Ubuntu, installed the server, and it properly configured everything by default upon installation. I must have mistakenly changed something in `configuration.yml` that messed it up.

So for those looking for help, these are the steps I followed:

**1** - Install a fresh Ubuntu 16.04 Droplet (not a LAMP stack, just a basic Ubuntu install)
**2** - Follow these steps as described in the Realm docs:

```
# Setup Realm's PackageCloud repository
curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash

# Update repositories
sudo apt-get update

# Install the Realm Object Server
sudo apt-get install realm-object-server-de

# Enable and start the service
sudo systemctl enable realm-object-server
sudo systemctl start realm-object-server
```

**3** - Then visit your IP address like this: `http://<your ip>:9080` and you should see the Realm Dashboard login.

**Comment by atom2ueki** [comment]
@cliftonlabrum may I know where you get configuration.yml sample file?

**Comment by jpsim** [comment]
A sample configuration file is included in the release zip in `realm-object-server/object-server/configuration.yml` from the macOS bundle [available here](https://realm.io/docs/get-started/installation/mac).

**Comment by cliftonlabrum** [comment]
@atom2ueki After you install the ROS, the `configuration.yml` file is in `/etc/realm`

**Comment by atom2ueki** [comment]
@cliftonlabrum @jpsim just pin you guys on this issue #100

**Comment by jpsim** [comment]
Looks like @teotwaki is looking into that.

**Comment by RawanA** [comment]
@atom2ueki  can  /etc/realm be open using finder ?
