### ISSUE TITLE
Latest version of Realm Browser on iOS does not scroll tables

### ISSUE THREAD

**Issue by stevewehba** [realm/realm-mobile-platform#71]

**Comment by bigfish24** [comment]
@stevewehba we don't offer a Realm Browser for iOS, is this a third-party library?

**Comment by teotwaki** [comment]
@stevewehba Did you mean the macOS browser? If so, could you please provide a reproduction case? Thanks.

**Comment by teotwaki** [comment]
I'm going to close this, as I'm unsure what the issue is, nor which product OP is talking about.
