### ISSUE TITLE
How to have shared database for users

### ISSUE THREAD

**Issue by Jauzee** [realm/realm-mobile-platform#73]
I want to move my app backend from Firebase to own server based on Realm Mobile Platform and have some questions:

· I want to give read & write access for all app users and wish to have no login required for them. Should I use same login & password for all the users?
· If my *.realm file takes 1 MB does it mean that every app installation increases space on server's disk for 1 MB (or thereabouts)?

**Comment by teotwaki** [comment]
Hi @Jauzee,

1. Yes, it would be possible to do so. We're working on an anonymous user feature. As far as I know, we don't have a public issue tracking this, but we're working on it.
2. If it's a shared Realm (as in, all of your users access the same URI), then there will only be a single copy on the server side. Each client will have their own local copy.
