### ISSUE TITLE
Clarify more on Counters

### ISSUE THREAD

**Issue by monajafi** [realm/realm-mobile-platform#78]
please would you provide a little sample code or more explanation for this statement in the Counter  section description:
"to support this common use case we offer a way to express the intent that you are incrementing (or decrementing) the value, giving enough hints to the merge that it can reach the correct result"

how we can express our intent to merge in android code ? please would you clarify this more

**Comment by bmunkholm** [comment]
@monajafi This feature has not been released yet. The first line under "Counters" says: "Not exposed in client API’s yet". Is that not clear enough? Any suggestions to make it clearer?

**Comment by monajafi** [comment]
sorry I asked question before trying to solve the problem.
we've implemented a counter on client side the code is here: 
[http://stackoverflow.com/questions/41352392/counters-custom-conflict-resolution-in-realm-mobile-platform-for-android/41368707?noredirect=1#comment70071857_41368707](url)
but without having a callback to be notified when sync get completed this method will not work properly.

**Comment by bmunkholm** [comment]
Yeah the real solution is to expose the counter support in the SDK's. Until then the best workaround is to use a list of increment commands and then update the value based on that (as suggested on SO).
