### ISSUE TITLE
Schema mismatch detected: another process has modified the Realm file's schma in an incompatible way

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#80]
I get the following error:

`terminating with uncaught exception of type std::logic_error: Schema mismatch detected: another process has modified the Realm file's schema in an incompatible way`

After I added a new property to my schema. I configured my Realm like the following:

```
private func setDefaultRealmConfiguration(email: String, user: SyncUser) {
        let configuration = Realm.Configuration(syncConfiguration: SyncConfiguration(user: user, realmURL: self.buildRealmURL(email: email)));
        
        Realm.Configuration.defaultConfiguration = configuration;
        Realm.Configuration.defaultConfiguration.deleteRealmIfMigrationNeeded = true;
 }
```

So that means: Delete Realm if migration is needed. Isnt it possible to do that? The server side schema did not change. The new property I added is only on my device, not on server side. Do I always have to write a migration now?

I did not find any option to delete my Realm Object manually on server side.

**Comment by bmunkholm** [comment]
Issues related to a specific SDK (https://github.com/realm/realm-cocoa/issues/new) is best addressed there. I wouldn't mind moving this issue for you, but it would be better if you would do that yourself to ensure proper notifications :-) 
Thanks!

**Comment by jpsim** [comment]
You cannot use `deleteRealmIfMigrationNeeded` with synchronized Realms. That's likely your issue here.

**Comment by Montrazul** [comment]
Yes that was my error. I have to write migrations for synchronized realms.

**Comment by jpsim** [comment]
You also cannot migrate synced Realms. Only add to the schema.

**Comment by Montrazul** [comment]
Wait, what? What if I release a new version which contains heavy changes to the model? Do I have to delete all the data I have and create a new Realm?

**Comment by jpsim** [comment]
You don't have to delete the old Realm, but if you want to make significant and destructive changes to your schema, you cannot do that in a safe way without compromising your ability to synchronize with older clients.

Which is why we support additive changes to your schema, but data migrations cannot be made with synchronized Realms (a.k.a "migration blocks").

We cover this in the [Realm Mobile Platform -> Migrations](https://realm.io/docs/swift/latest/#migrations-1) docs.

> I mean it can happen that you cont need fields anymore or that you have to rename fields or similar stuff. What do you do if you have to do it?

If you don't need a property anymore, you'll still have older clients that can access it, so it can't be deleted. Just stop using it on new clients. An unused property has very little overhead in Realm 😉.

If you need to rename a property, I suggest instead adding a computed property with the name you want, which is backed by the old property with the name you didn't like.

If you _must_ delete the old property, or perform destructive schema changes, or perform a data migration (e.g. "first name + last name" -> "full name"), you'll need to create a new Realm.

**Comment by Montrazul** [comment]
Ok, if you say an unused property has little overhead it will be ok i guess. I see that you need to do it for the most common ways apps are being used. I did not think of it because with our app it is not possible to have older clients. every client needs to have the newest version otherwise it isnt working. Thx for making your reasons clear.

**Comment by jpsim** [comment]
> with our app it is not possible to have older clients. every client needs to have the newest version otherwise it isnt working

That's exactly the type of restriction that we've worked to avoid, which also sets the Realm Mobile Platform apart from other solutions.

Now that you've told me you have this limitation (presumably for a reason other than Realm), I'd suggest creating a new Realm for each version, that way you're not synchronizing data from an incompatible version of your app, which actually _would_ lead to overhead.

**Comment by Montrazul** [comment]
But there would be a problem with creating a new realm (at least I think so). Since realm for now is not able to do selective synchronization I had to create a workaround. My workaround was to create a realm for each user identified by the email address of the user. So every user has its very own realm address, so that every client only synchronizes the data it really needs. 

So creating new realms isnt that easy since they are bound to the email address of a user.

**Comment by astigsen** [comment]
> My workaround was to create a realm for each user identified by the email address of the user.

Why did you need to identify it by the email address? On their own each user can only create Realms with the path prefixed with their userid, so that makes them isolated from each other by default (you can get around that by creating the Realms for them as admin).

So each user could easily have multiple Realms that are all uniquely accessible by them (since they are all stored in the same "folder" based on the users id).

**Comment by Montrazul** [comment]
What you mean it makes them isolated from each other by default? If I just open up a realm using the basic server address:

`"realm://localhost:9080/~/"`

All my users are getting created in one realm under `/~`

**Comment by Montrazul** [comment]
Oh I understand what you meant with "path prefixed with their userid". But what I not understand is what @jpsim meant by simply creating a new realm. If I create a new realm I would lose all data wouldnt I?

**Comment by jpsim** [comment]
> If I create a new realm I would lose all data wouldnt I?

You could copy data from the old Realm to the new Realm, which is the only way to do a "data migration" supported by synced Realms. This is also what you seem to have been trying to do with `deleteRealmIfMigrationNeeded`.

**Comment by Montrazul** [comment]
And how to copy the data from one realm to another?

**Comment by jpsim** [comment]
Just how you'd normally access data from a Realm, read from the old one, write to the new one.

**Comment by Montrazul** [comment]
So I guess you mean something like:

```
let configOld = Realm.Configuration(path: oldpath, readOnly: true);
let realmOld = try! Realm(configuration: configOld);

let configNew = Realm.Configuration(path: newpath, readOnly: false);
let realmNew = try! Realm(configuration: configNew);
```

And then copy around the data?

Wouldnt that also be a solution for old clients and new clients? If you do that for example?

```
let server = "realm://192.168.178.46:9080/~/APP_NAME";
let version = "REALM_VERSION_1";
let url = URL(string: "\(server)/\(version)")!;

let configuration = Realm.Configuration(
            syncConfiguration: SyncConfiguration(user: user, realmURL: url),
            schemaVersion: 1);
```

And after that you could do your migration something like

```
if (version == "REALM_VERSION_2" && !notMigrated) // notMigrated some boolean stored somewhere
{
    // connect to old realm and copy data if neccessary
}
```

**Comment by jpsim** [comment]
yes.

**Comment by michael-mckenna** [comment]
How would this work for shared realms? Let's say you have a shared realm storing usernames. If you want to check if a username exists or not, people who haven't updated to V2 would not be aware of the new usernames that have been added. So would this be a case of forcing the user to update their app so they are on the latest version of the realm config?

**Comment by ianpward** [comment]
Hey @michael-mckenna take a look at this write-up
http://news.realm.io/news/migrations-with-synced-realms/

So if you had two versions of Realms for shared realms you could use our event handling system to trigger a code block that would copy new data from the old schema to the new or vice versa. The trade off is that you would not be using our built-in conflict resolution.

![image](https://user-images.githubusercontent.com/1691481/27522895-3ef61350-59de-11e7-9942-dacd1aa30b97.png)

**Comment by michael-mckenna** [comment]
@ianpward Awesome, thank you.
