### ISSUE TITLE
Sync success or complete event

### ISSUE THREAD

**Issue by monajafi** [realm/realm-mobile-platform#81]
In my app I need to know when the sync process get completed. Could I use notification for this purpose. especially my problem is this: I want to run cached commands after my device get online 
but after going online and before getting the synced data the app queries the local data and runs commands on them. In the case other devices do the same the final results will be wrong
one hack solution is to give some delay for running cached commands to let the app sync data from web first
What  is best workaround for this situation.

**Comment by Montrazul** [comment]
I guess this is also related to [Issue #72](https://github.com/realm/realm-mobile-platform/issues/72)

**Comment by bmunkholm** [comment]
Exactly Issue #72 will solve this.
