### ISSUE TITLE
Help: Switch from another database to realm mobile platform

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#85]
Hi,

the last weeks I was playing around with the realm mobile platform and I came to the conclusion that it is great! So we want to use it!

We already are using the client side realm database but we are currently synchronizing it with a spring backend using a H2 Database. So Clients are Realm, Server is H2. In our next app version we would like to migrate from H2 to realm mobile platform, but ofcourse we dont want to lose any data.

Also there will be some schema changes in the next version. For the client side database realm migrations are working but for realm mobile platform migrations arent supported (for understandable reasons).

So what we now have:

```
Client: Realm schema version 1
Server: H2
```

What we want to have with next Version

```
Client: Realm schema version 5
Server: Realm mobile platform
```

Do you think that there is a way to get the migration working somehow? My first thoughts were that since every client already has a local realm, simply changing the realm object to a synchronized realm giving the target server address would do the trick (since its offline first and the client side data would be synchronizing with the server side) but I really have no idea how the realm migration would fit in there since many things changed in our data model. Also im not sure if simply creating a synchronized realm would take the currently client side existing realm object to synchronize with the server side.

**Comment by bmunkholm** [comment]
Hi @Montrazul 
That's awesome - good to hear!
Currently you can't just convert a local Realm file to a Syncronised one (although we plan to enable that). So I would suggest you make a complete manual copy of the Realm v1 file to a synced Realm v5 file by iterating over all objects and copy them to the new format, including doing the data migrations you want to. How easy that is depends heavily on your models of course. But that would be my first suggestion if its feasible.

**Comment by Montrazul** [comment]
So in theory it would be:

```
let configOld = Realm.Configuration(path: oldpath, readOnly: true);
let realmOld = try! Realm(configuration: configOld);

let configNew = Realm.Configuration(
            syncConfiguration: SyncConfiguration(user: user, realmURL: url),
            schemaVersion: 1);
let realmNew = try! Realm(configuration: configNew);

// now copy what you need from realmOld to realmNew
```

Since the model will change I guess I have to write two migrations. First I will need the migration block for the old realm:

```
let configOld = Realm.Configuration(schemaVersion: 5,
     migrationBlock: { migration, oldSchemaVersion in
           if (oldSchemaVersion < 5) {
               migration.enumerateObjects(ofType: MY_OBJECT.className(), { oldObject, newObject in
                   newObject!["bla"] = "blub";
                   // ...
               });
           }
           // .....
       });
```

Otherwise I would not be able to open the old realm, am I right?
After that is done I need the migration from the old local realm to the new synced realm. And that would simply be a lot of fun with copying objects. 

I guess that wont even take much time so I will try that.

**Comment by bmunkholm** [comment]
Yeah I think that's the easiest. You are right, since your object types are the same (in both Realms), it seems necessary to migrate first, and copy afterwards.
Have fun!
