### ISSUE TITLE
generateCloudKitCert.sh missing in Linux installation

### ISSUE THREAD

**Issue by ewerx** [realm/realm-mobile-platform#86]
According to the docs for iCloud authentication (https://realm.io/docs/realm-object-server/#icloud):

> Create a private key using the generateCloudKitCert.sh script. This script can be found in /etc/realm under Linux installations, and in the realm-object-server directory of the macOS distribution. To generate a key, open a terminal window, navigate to the appropriate directory for your distribution, and run /bin/sh generateCloudKitCert.sh. The output from the command will be a base64 public key string; save it.

I installed Realm Object Server on Ubuntu 16.04 (`realm-object-server-developer=1.0.0-BETA-4.11-449`) and there is no `generateCloudKitCert.sh` in `/etc/realm`. Where can I find it?

**Comment by teotwaki** [comment]
@ewerx Hey, sorry about this. I'll make sure we ship this in the next version.

**Comment by teotwaki** [comment]
In order to unblock you, you can simply use OpenSSL commands to create the needed information keys:

```sh
# sudo required because we're writing in /etc/realm
# Generate a private key for your server
sudo openssl ecparam -name prime256v1 -genkey -noout -out /etc/realm/cloudkit_eckey.pem
# Generate a public key, that will be submitted to CloudKit
openssl ec -in /etc/realm/cloudkit_eckey.pem -pubout
# You can repeat this second command as many times as needed, if you "lose" the public key
```

Then, simply update your `configuration.yml` according to the website documentation, but take care that the path of the private key file is `/etc/realm/cloudkit_eckey.pem`, and not the default of `cloudkit_eckey.pem`.

You should be good to go!

**Comment by istx25** [comment]
@teotwaki: Would you consider your last comment a fix to this issue or a workaround?

**Comment by teotwaki** [comment]
We've updated the documentation and this should no longer be an issue.
