### ISSUE TITLE
"Unable to locate package realm-object-server-de" on Ubuntu 16.04

### ISSUE THREAD

**Issue by matale** [realm/realm-mobile-platform#9]
Hello, I seem to be unable to locate the package on Ubuntu, the commands that come before at https://realm.io/docs/realm-object-server/ complete successfully but installing fails. 
I am running the Desktop Ubuntu could this be an issue? 

john@john-VirtualBox:~$ sudo apt-get install realm-object-server-de
[sudo] password for john:
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package realm-object-server-de

john@john-VirtualBox:~$  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:    16.04
Codename:   xenial

**Comment by teotwaki** [comment]
Hi @matale,

Could you confirm that you have installed the Realm PackageCloud repository, and that is it is active? I didn't see a mention of that in your initial issue. Please remember that you also need to run `sudo apt-get update` in order to refresh the package information in your (installed) repositories.

Thanks,

**Comment by matale** [comment]
Yes I am installing the repository and running the update command.

```
john@john-VirtualBox:~$ curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash
[sudo] password for john: 
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/realm_realm.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
john@john-VirtualBox:~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Hit:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://archive.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Hit:5 https://packagecloud.io/realm/realm/ubuntu xenial InRelease
Fetched 190 kB in 5s (35.1 kB/s)
Reading package lists... Done
john@john-VirtualBox:~$ sudo apt-get install realm-object-server-de
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package realm-object-server-de
john@john-VirtualBox:~$
```

**Comment by teotwaki** [comment]
What hardware platform are you running? 32 or 64 bit? `uname -a`

**Comment by matale** [comment]
Linux john-VirtualBox 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:06:14 UTC 2016 i686 i686 i686 GNU/Linux

**Comment by teotwaki** [comment]
Hi @matale,

Sorry for not getting back to you, I didn't get a notification for some reason. We only support amd64 as of now.

**Comment by chooikw** [comment]
wish to see it on x86_64 soon

**Comment by teotwaki** [comment]
@chooikw We only support amd64/x86_64 (64-bit). We don't support i386/i686 (32-bit).

**Comment by giaesp** [comment]
@teotwaki I've the same issue with Ubuntu 16.10 64bit (Italian)

Linux Aspire 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

One of the last line says

W: The repository 'https://packagecloud.io/realm/realm/ubuntu yakkety Release' does not have a Release file.

Is an Ubuntu version incompatibility?

**Comment by teotwaki** [comment]
@giaesp We only support Ubuntu 16.04. 16.04 is an LTS release, which is why we've decided to support it, as it will be around for quite some time. 16.10 isn't.

**Comment by Nonnis-M** [comment]
@teotwaki I've the same issue with the following configuration:

Linux vmi111164 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
O.S: Linux Ubuntu 16.04 64bit

When I run:
curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash
sudo apt-get update
sudo apt-get install realm-object-server-developer

at this point I get the error:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**E: Unable to locate package realm-object-server-developer**

**Comment by capotej** [comment]
Hi, packagecloud co-founder here, I've tried to reproduce this issue on a fresh Ubuntu 16.04.2 instance and cannot seem to reproduce:

```
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-71-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

root@realm-debug:~# curl -s https://packagecloud.io/install/repositories/realm/realm/script.deb.sh | sudo bash
Detected operating system as Ubuntu/xenial.
Checking for curl...
Detected curl...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/realm_realm.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
root@realm-debug:~# sudo apt-get install realm-object-server-developer=1.4.1-305
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  realm-object-server-developer
0 upgraded, 1 newly installed, 0 to remove and 46 not upgraded.
Need to get 46.2 MB of archives.
After this operation, 158 MB of additional disk space will be used.
Get:1 https://packagecloud.io/realm/realm/ubuntu xenial/main amd64 realm-object-server-developer amd64 1.4.1-305 [46.2 MB]
Fetched 46.2 MB in 2s (20.8 MB/s)
Selecting previously unselected package realm-object-server-developer.
(Reading database ... 53855 files and directories currently installed.)
Preparing to unpack .../realm-object-server-developer_1.4.1-305_amd64.deb ...
Generating RSA private key, 2048 bit long modulus
....+++
...............................................................+++
e is 65537 (0x10001)
writing RSA key
Unpacking realm-object-server-developer (1.4.1-305) ...
Setting up realm-object-server-developer (1.4.1-305) ...
root@realm-debug:~#
```

I've also verified the repository indexes manually, everything looks correct and in working order:

```
​curl -sL https://packagecloud.io/realm/realm/ubuntu/dists/xenial/InRelease
​
​curl -sL https://packagecloud.io/realm/realm/ubuntu/dists/xenial/main/binary-amd64/Packages
​
​curl -sL https://packagecloud.io/realm/pool/xenial/main/r/realm-object-server-developer/realm-object-server-developer_1.4.1-305_amd64.deb
```

Can you try clearing your APT cache and trying again?

`​​rm -rf /var/cache/apt/*` and `rm -rf /var/lib/apt/lists/*`

Thanks!

**Comment by capotej** [comment]
Also, if anyone who is currently experiencing this can paste the full output of their local repository metadata:

`cat /var/lib/apt/lists/packagecloud.io_realm_realm_ubuntu_dists_xenial_InRelease`

and

`cat /var/lib/apt/lists/packagecloud.io_realm_realm_ubuntu_dists_xenial_main_binary-amd64_Packages`

Thanks!

**Comment by capotej** [comment]
cc'ing @Nonnis-M for visibility

**Comment by Seelmi** [comment]
@capotej  even after clearing the cache i still have the same error 
my friend was succesfull in installing it in 5 minutes .. while i've been trying to do so for 2 weeks .
The only difference between me and him is that my Ubuntu 16.04 is running on a Virtual machine while his is running as the Main OS for his PC .
Could that be the problem?

**Comment by capotej** [comment]
@Seelmi I do not think that is the problem, unless those virtual machines are behind a firewall that prevents communication with our servers.

On a failing Ubuntu 16.04 machine, can you paste the cached repository metadata by running: 

` cat /var/lib/apt/lists/packagecloud.io_realm_realm_ubuntu_dists_xenial_InRelease`

and

`cat /var/lib/apt/lists/packagecloud.io_realm_realm_ubuntu_dists_xenial_main_binary-amd64_Packages`

Thanks

**Comment by Nonnis-M** [comment]
My Ubuntu 16.04 is a virtual machine too. I find these files into the /var/lib/apt/lists folder:

packagecloud.io_realm_realm_ubuntu_dists_trusty_main_binary-amd64_Packages
packagecloud.io_realm_realm_ubuntu_dists_trusty_main_binary-i386_Packages
packagecloud.io_realm_realm_ubuntu_dists_trusty_main_source_Sources

but for all of them I get no result when run cat command as you suggested. I've also cleaned the  apt cache but nothing changed.
There is a way to check if the firewall is really locking the access to your server? e.g. make a telnet or similar.

**Comment by teotwaki** [comment]
@Nonnis-M Are you sure you're running 16.04? Trusty is 14.04, no? That's 4 major versions difference. We don't support 14.04 at the moment, so that's a separate issue.

@Seelmi, we would very much appreciate your help moving forward.

**Comment by capotej** [comment]
@Nonnis-M You can use the curl commands I posted to verify that your virtual machine can access our services:

​curl -sL https://packagecloud.io/realm/realm/ubuntu/dists/xenial/InRelease
​
​curl -sL https://packagecloud.io/realm/realm/ubuntu/dists/xenial/main/binary-amd64/Packages
​
​curl -sL https://packagecloud.io/realm/pool/xenial/main/r/realm-object-server-developer/realm-object-server-developer_1.4.1-305_amd64.deb

@Seelmi since your caches are empty after attempting to install, you should also try the above commands and report back

**Comment by Nonnis-M** [comment]
@teotwaki as mentioned in my first answer (14 days ago) this is the output I got with uname command:

Linux vmi111164 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
O.S: Linux Ubuntu 16.04 64bit

**Comment by teotwaki** [comment]
@nonnis-m Sorry, I didn't mean to offend you. I was just replying to the fact that your apt files mention trusty?

@capotej Could this be related to a bug in the os version detection script on machines that were upgraded from one major version to another?

**Comment by gritzko** [comment]
@alebsack @nnrealm guys, can you please verify the install on vmboxed Ubuntu?

**Comment by nnrealm** [comment]
I have done this recently in a VM running 16.04.

**Comment by alebsack** [comment]
@Nonnis-M You can also access the packagecloud page for this repository directly: https://packagecloud.io/realm/realm/install.  From there you can download packages individually.

**Comment by bmunkholm** [comment]
Closing this now due to inactivity. Feel free to reopen if the problem persists. Thanks!
