### ISSUE TITLE
Realm IDs in Website vs Realm Browser

### ISSUE THREAD

**Issue by ArifADS** [realm/realm-mobile-platform#93]
I'm having a problem where I can't access some users in Realm Browser because it is out of update, some User IDs are already deleted, only Website show the correct ones

![screen shot 2017-01-11 at 4 25 00 pm](https://cloud.githubusercontent.com/assets/410781/21867063/90d4d224-d81a-11e6-9317-2b592134f89a.png)
![screen shot 2017-01-11 at 4 25 13 pm](https://cloud.githubusercontent.com/assets/410781/21867064/90f2afce-d81a-11e6-8ee3-6b2d2506fddf.png)

**Comment by bigfish24** [comment]
Sorry about your issue! I have assigned @stel from our team who has been handling browser work to look into this.

**Comment by cliftonlabrum** [comment]
@ArifADS The Realm Browser keeps a static list of all IDs that have been connected to at some point, but it does *not* sync them with the ROS. So if you deleted a user on the server, it will still show up in the Realm Browser's list. Typically the most recently created Realm user will be at the bottom of the Realm Browser list.

I requested more functionality in the Realm Browser here: https://github.com/realm/realm-browser-osx/issues/229

**Comment by ArifADS** [comment]
No. The Realm Browser doesn't show the latest users created. It stopped showing new ones a long time ago. Is there a way to fix this? Make it sync or delete the previous data. 





On Thu, Jan 19, 2017 at 11:57 AM -0500, "Clifton Labrum" <notifications@github.com> wrote:












@ArifADS The Realm Browser keeps a static list of all IDs that have been connected to at some point, but it does not sync them with the ROS. So if you deleted a user on the server, it will still show up in the Realm Browser's list. Typically the most recently created Realm user will be at the bottom of the Realm Browser list.


I requested more functionality in the Realm Browser here: realm/realm-browser-osx#229

**Comment by stel** [comment]
@ArifADS please try to delete the directory at `~/Library/Container/io.realm.realmbrowser` and restart the Browser.

**Comment by istx25** [comment]
@ArifADS, did @stel's recommendation help?

**Comment by stel** [comment]
@ArifADS we didn't get back from you, hope my suggestion to delete Realm Browser's cached data helped to solve your issue.

Realm Browser shows all realms available on the Object Server, it doesn't show users. When you delete the user it's realms are not deleted so you can still access it with admin user.

I'm closing this issue for now, @ArifADS feel free to reopen it or create a new one if you need any further help.
