### ISSUE TITLE
How many connections can be opened simultaneously?

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#98]
I found a configuration where I can set the amount of realm files which are allowed to be opened simultaneously. What if I have an App with 100.000 User using realm mobile platform. Do I have to set the value of simultaneously opened files to a higher value? Whats the performance advantages and disadvantages of that?

**Comment by teotwaki** [comment]
A user session doesn't necessarily need to be backed by an open file. I believe the configuration you found is only an optimisation part of our server (as in, how aggressively should the server close files after they are no longer used by a session).

Even though there is a correlation between number of open connections and open files, there isn't necessarily a 1-to-1 relationship. Our protocol supports multiplexing, and this would allow, for example, a single user to have a 100k files open (though, that wouldn't be ideal ;)).

The real limits are going to come from your system's configuration (how many open file descriptors are allowed), and the computational cost of executing the merge algorithm for such a large number of clients.

Regarding file descriptors: Many thing consume file descriptors. IPC pipes between processes, TCP connections, open files. This means that a new user connecting will consume more than a single file descriptor. You can check how many file descriptors are allowed on your system by running the following command:

```sh
# system wide value
cat /proc/sys/fs/file-max
```

And

```sh
# User-specific soft limit
ulimit -Sn
# User-specific hard limit
ulimit -Hn
```

What this means:

- The value from `/proc/sys/fs/file-max` is how many different file descriptors the kernel will allow, globally, shared amongst all users. You can increase this value (how depends on your distribution).
- The values reported by `ulimit` show the soft limit and hard limit that are applied to the specific user who ran the command. These can be increased as well, usually by editing `/etc/security/limits.conf`.

We've had fun tuning systems to handle up to 500k clients on a single machine. I'm sure if we had better hardware/network and more time, we could've pushed that quite a bit more.

**Comment by istx25** [comment]
Seems like this issue can be closed as @teotwaki gave a rather detailed answer. Feel free to reopen if more of a discussion needs to be had or if there are follow-up questions.
