### ISSUE TITLE
Changing Username and / or Password

### ISSUE THREAD

**Issue by Montrazul** [realm/realm-mobile-platform#99]
I guess there are already tickets for tracking this features but what is currently the recommended way to handle a username and / or password change?

**Comment by istx25** [comment]
Thank you for reaching out, @Montrazul. I'm going to look into what is the currently recommended way to process a username/password change. We appreciate your patience.

**Comment by cliftonlabrum** [comment]
Possible duplicate of https://github.com/realm/realm-mobile-platform/issues/16

**Comment by jpsim** [comment]
Yes @cliftonlabrum is correct. @Montrazul please use the CLI option I shared in https://github.com/realm/realm-mobile-platform/issues/16#issuecomment-257541004 as a current way to do this.
